- redaxo/src/addons/install/pages/packages.add.php
Update der Nummer gefundener Addons.
Kleine optische sache, wäre schön wenn man das sauberer implementiern könnte, funktioniert aber auch so....
> Installer Addon - Nummer der Suchergebnisse

- redaxo/src/addons/import_export/pages/export.php
Wenn das Formular mit Ajax abgeschickt wird, kann die Backup-Datei nicht heruntergeladen werden. Daher sollte es hier deaktiviert werden.
> Pjax deaktivieren

- README.md
Notwendig da bereits einige Leute "Fehler gemeldet" haben, wg. des ZIP Downloads von GH
> Installationsanleitung

- redaxo/src/addons/be_style/assets/javascripts/main.js
- redaxo/src/addons/be_style/plugins/customizer/assets/js/main.js
- redaxo/src/addons/metainfo/assets/metainfo.js
- redaxo/src/core/assets/standard.js
Ziel: Initialisierung von Inhalt, egal wie er geladen wurde.
Der Nutzer soll also nix von PJAX wissen müssen, sondern nur, dass es da ein Event von Redaxo gibt, welches immer ausgelöst wird, wenn es neuen Content gibt.
@staabm Was meinst du dazu? Oder bessere Idee?
fixes #533
> JS: "rex:ready" event

- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
Werden die CommonVars vor den ObjectVars geparst, sind etwa folgende Konstrukte möglich:
`REX_LINK[id="1" widget="1" category="REX_CATEGORY_ID"]`.
Die CategoryId wird damit aufgelöst bevor das Link-Widget zusammengebaut wird.
> replaceCommonVars vor replaceObjectVars, closes #570

- redaxo/src/core/assets/standard.js
when pjax is manually invoked e.g. with `$.pjax({url: url, container: '#contentpjax'})`
> fixed "options.container.trigger" is not a function

- redaxo/src/addons/install/lib/api_core_update.php
- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lib/setup/import.php
- redaxo/src/core/pages/setup.php
Der PR führt quasi die aus R4 bekannte Update-Option im Setup wieder ein.
Dabei wird aber das gleiche Update-Skript verwendet, welches auch vom Installer benutzt wird.
Ohne den PR ist es sehr mühsam, DB-Änderungen zu übernehmen, wenn man per git updated.
> Core-Update in Setup wieder ermöglichen

- redaxo/src/addons/be_style/plugins/customizer/boot.php
Das Icon war bisher außerhalb des Anker-Textes.
> Customizer: Icon von "Link zur Website" klickbar machen.

- redaxo/src/addons/be_style/plugins/customizer/assets/vendor/codemirror/codemirror.css
Das CSS fehlte, um den Fullscreen aktivieren zu können.
https://codemirror.net/demo/fullscreen.html 
https://codemirror.net/addon/display/fullscreen.css
> Customizer: CodeMirror Fullscreen (F11)

- redaxo/src/addons/structure/lib/service_article.php
- redaxo/src/addons/structure/lib/service_category.php
- redaxo/src/addons/structure/plugins/content/lib/content_service.php
Die Methoden in `rex_article_service`,  `rex_category_service`,  `rex_content_service` etc. lassen sich im Frontend nicht nutzen, da überall die Methoden `rex_sql::addGlobalCreate/UpdateFields` aufgerufen werden.
Einzig bei `rex_article_service::articleStatus` gab es einen Workaround, da wurde im Frontend als User "frontend" übergeben (siehe Changes in diesem PR).
Aufgefallen ist das Problem, da @phoebusryan im Frontend Artikel kopieren möchte.
Ich bin mir unsicher, wie wir das Problem am besten lösen sollten. Aber auf jeden Fall sollten die Methoden meiner Meinung nach auch im Frontend nutzbar sein.
Sehe diese drei Variante:
1. Den Workaround von `rex_article_service::articleStatus` an allen relevanten Stellen integrieren
2. Den Workaround so direkt in die …
> addGlobalCreate/UpdateFields: Auch in Frontend funktional gemacht

- .gitignore
- redaxo/src/core/composer.json
- redaxo/src/core/composer.lock
- redaxo/src/core/lib/util/markdown.php
- redaxo/src/core/pages/packages.php
- redaxo/src/core/tests/util/markdown_test.php
- redaxo/src/core/vendor/composer/autoload_classmap.php
- redaxo/src/core/vendor/composer/autoload_namespaces.php
- redaxo/src/core/vendor/composer/autoload_static.php
- redaxo/src/core/vendor/composer/installed.json
- redaxo/src/core/vendor/erusev/parsedown-extra/.travis.yml
- redaxo/src/core/vendor/erusev/parsedown-extra/LICENSE.txt
- redaxo/src/core/vendor/erusev/parsedown-extra/ParsedownExtra.php
- redaxo/src/core/vendor/erusev/parsedown-extra/README.md
- redaxo/src/core/vendor/erusev/parsedown-extra/composer.json
- redaxo/src/core/vendor/erusev/parsedown/.travis.yml
- redaxo/src/core/vendor/erusev/parsedown/LICENSE.txt
- redaxo/src/core/vendor/erusev/parsedown/Parsedown.php
- redaxo/src/core/vendor/erusev/parsedown/README.md
- redaxo/src/core/vendor/erusev/parsedown/composer.json
* [Parsedown](https://github.com/erusev/parsedown) als Basis
* `rex_markdown` um unabhängig vom verwendeten Parser zu bleiben
* Falls Addons keine `help.php` haben, wird stattdessen die `README.md` angezeigt, falls vorhanden
> Markdown-Parser

- redaxo/src/addons/media_manager/package.yml
Zur Zeit wird man nach Klick auf den Button zur "overview" Seite geleitet, was momentan fälschlicherweise die Anleitung ist. Besser wäre, man würde auf die Übersicht der Typen gelangen, sprich zu "types". Noch besser wäre, man würde auf der jeweiligen Seite bleiben, wo man den Knopf gedrückt hat, dazu müsste man aber wahrscheinlich den Cache-Löschen Knopf anders einbinden.
> clear_cache button ziel url update

- redaxo/src/addons/structure/pages/linkmap.php
Prevents xss demonstrated in https://blog.ripstech.com/2016/redaxo-remote-code-execution-via-csrf/
> Sanitize input-parameters in linkmap

- redaxo/src/core/lib/sql/sql.php
Im Rahmen von https://github.com/redaxo/redaxo/pull/926/files ist aufgefallen dass ein escaping hier an vielne Stellen aktuell "fehlt".
> properly escape identifiers in rex_sql

- redaxo/src/addons/mediapool/pages/index.php
- redaxo/src/addons/structure/pages/linkmap.php
- redaxo/src/core/assets/standard.js
Ich habe mir nun #760 nochmal angeschaut und habe einen Workaround für das bestehende Problem gefunden, ohne etwas an der Nutzung der Events zu ändern.
Die Eventhandlers (die am Popup-window hängen) werden im opener zwischengespeichert, und nach Page (Re)loads dann wieder neu registriert.
Die Nutzung durch Addons (markitup, redactor) würde sich wie gesagt nicht ändern, nur dass es nun richtig funktioniert, und die Eventhandler bei Page Loads im Popup nicht mehr verloren gehen.
ping @staabm @phoebusryan @IngoWinter
fixes #760
> Events rex:selectMedia/Link über Page Loads retten

- redaxo/src/addons/mediapool/lib/media.php
`null` sollte hier nicht relevant sein, daher können wir mit dem schnelleren `isset` arbeiten
> optimized media instance pool performance

- redaxo/src/core/lib/sql/sql.php
use fast isset() path for all non-null values and use the "more correct "array_key_exists()" for the 1% which can contain NULL.
7% perf increase in demo-base structure first render, because this method is used a lot.
> speed optimize rex_sql::fetchValue()

- redaxo/src/core/assets/standard.js
try/catch hinzugefügt um foldenden Fehler zu vermeiden
Error: Permission denied to access property „winObjCounter“ 
Ist mehr ein Workaround, imo ist das Ganze komisch gelöst. Evtl. zukünftig mit Modals arbeiten statt Popups?
> Fixed bug mit winObjCounter permission denied

- redaxo/src/core/boot.php
- redaxo/src/core/lib/var_dumper.php
Durch symfony/var-dumper haben wir ja jetzt auch die schicke `dump()`-Funktion integriert.
Hier ist mal ein Vorschlag von mir, sodass die Funktion für Non-Admins und Non-Debug-Mode keine Ausgabe macht.
Man kann die Funktion also auch auf Liveseiten benutzen, ohne dass die normalen User etwas davon sehen.
> dump() ohne Ausgabe für Non-Admins (und Non-Debug-Mode)

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql_select_test.php
closes #965 
Hier mal ein Vorschlag von mir.
Finde es gut, die Option pro Query zu haben. Habe mich allerdings für einen allgemeinen `$options`-Parameter entschieden. Falls mal noch mehr hinzukommen.
Falls wir das so machen wollen, würde ich noch die phpdocs anpassen.
> rex_sql: Abfragen ohne Buffer ermöglichen

- redaxo/src/addons/cronjob/lib/manager_sql.php
fixes #990 replaces #1001
Es wird nun direkt vor Ausführung eines Jobs deren nexttime gesetzt, statt erst danach. So wird sichergestellt, dass die Jobs garantiert erst zum nächsten Zeitpunkt erneut starten.
Der Ablauf ist so:
- Alle Jobs abrufen, die dran sind
- Bei all jenen execution_start setzen
- Anschließend die Jobs nacheinander ausführen. Vor jeder Ausführung nexttime neu setzen
Bei Punkt 1 werden die rausgelassen, die bereits als zur Ausführung bereitstehend (execution_start) markiert wurden, auch wenn sie noch nicht tatsächlich gestartet wurden (nexttime wurde also noch nicht angepasst).
Nach doppelter max_execution_time, bzw. 6 Stunden in Skript-Umgebung, wird davon ausgegangen, dass grundsätzlich etwas schief gegangen ist, und der Job wohl doch nicht ausgeführt wurde.
Bei einem …
> Cronjob: Besseres Handling von nexttime und execution_start

- redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Ich hab bei einem aktuellen Projekt das Problem, dass immer der erste Slice auf einer Seite anders dargestellt wird... und zwar Modulunabhängig. Dies habe ich nun mit dieser Methode gelöst.
> Methode 'getPriority' hinzugefügt

- redaxo/src/core/fragments/core/top.php
Möglicher fix für https://github.com/redaxo/redaxo/issues/1015
> Warnungen vermeiden wenn view-files als url uebergeben werden

- redaxo/src/addons/media_manager/lib/media_manager.php
Wollte mir eigentlich mal ansehen, wie man den Expires-Header setzt, weil wir kürzlich viele Probleme mit generierten Bildern haben. Bin in der 5.3-Beta1 dann darauf gestoßen, dass die Bilder immer generiert und mit Status 200 ausgeliefert werden.
Beim genaueren untersuchen ist mir aufgefallen, dass es die Varable $header in der Funktion rex_media_manager::sendMedia gar nicht gibt.
Das dürfte das Problem aus #1025 sehr wahrscheinlich lösen.
> MediaManager: Bilder werden immer mit Status 200 geliefert.

- redaxo/src/core/update.php
> Beim Core-Update mindestens Version 2.1.2 des Installers erfordern

- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/lib/media_manager.php
Der PR macht den Umbau im Media Manager komplett rückgängig, um BC wieder herzustellen.
Die anderen Änderungen (Typen kopieren, session_abort) sind aber drin geblieben.
Vorschlag ist, das so für die 5.3.0 reinzunehmen, und dann zeitnah (aber in Ruhe) ein Einzelupdate des Media Managers zu erstellen mit einer einfachen Möglichkeit, die Maße des resultierenden Bildes abzufragen etc.
closes #1025
> Media Manager: Revert

- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/lib/media_manager.php
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/media_manager/update.php
closes #707 
Aufruf wäre nun:
```php
$media = rex_media_manager::create($type, $file)->getMedia();
$media->getFormat();
$media->getWidth();
$media->getHeight();
```
> Media Manager: Maße etc. des Cache-Bildes

- bin/.htaccess
- redaxo/src/core/assets/standard.js
- redaxo/src/core/pages/setup.php
In den Releases ist der Ordner nicht drin. Aber wenn man die GitHub-Version nutzt, dann schon.
(Ist mir auf traduko.redaxo.org aufgefallen, wo ich das Repository gecloned habe.)
Ich überlege, ob wir auch noch eine `.gitattributes` hinzufügen sollten, die den bin-Ordner excluded.
Dann wäre er beim Zip-Download über Github auch nicht mehr enthalten, nur noch bei `git clone`.
> /bin-Ordner schützen

- redaxo/src/addons/media_manager/lib/effect_abstract.php
Das scheint #1086 zu fixen. Leider weiß ich aber überhaupt nicht, ob das irgendwelche negativen Folgen hat.
Aktuell wird die Funktion insbesondere nicht nur zusätzlich bei PNGs aufgerufen, sondern zum Beispiel auch bei JPGs. Konnte spontan keine negativen Auswirkungen sehen, was aber nichts heißen muss.
Vorher wurde sie nur bei GIFs genutzt.
/cc @isospin
> Media Manager: imagepalettecopy für alle Bilder aufrufen, nicht nur für gifs

- redaxo/src/core/lib/console/command.php
So können wir ggf. den Style mal allgemein für alle Commands anpassen.
(Alle, die diese Basis-Klasse nutzen.)
Auch können wir bei Bedarf irgendwelche Hilfsmethoden anbieten.
> Basis-Klasse für Commands

- redaxo/src/core/install.sql
- redaxo/src/core/update.php
Die ID wurde nirgends verwendet, sondern es wurde sowieso mit dem Unique-Key über (namespace, key) gearbeitet.
Dadurch, dass rex_config [mit `REPLACE` arbeitet](https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/config.php#L364), und MySQL bei Replace immer löscht und neu anlegt, hat sich die ID auch noch bei jeder Änderung einer Konfiguration geändert.
Daher mein Vorschlag, die ID zu löschen und den Primary Key direkt auf die relevanten Spalten legen.
Hauptgrund dafür ist allerdings, dass ich es dann bei ydeploy einfacher habe, da ich dort nur einzelne Konfigurationen migrieren muss: https://github.com/yakamara/ydeploy/blob/edfbda300d3081ffd15173f3383b7ef594fba2bb/package.yml#L13-L15
Und diese ständig wechselnde ID stört dabei.
> rex_config: ID entfernt, Primary Key direkt auf (namespace, key)

- redaxo/src/core/layout/top.php
Ich fände sie nützlich, um z. B. im JS eines Addons auslesen zu können, ob der Debug-Modus aktiv ist. Für den Safemode gibt es bereits eine solche Klasse, für Debug fehlte sie noch.
> body-Klasse für Debug-Mode hinzugefügt

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
Hier nun mal konkret als Diskussionsgrundlage..
Ich würde `null` für 'kein PK' nehmen, sowohl im Setter, als auch im Getter.
Denke das passt besser zu 'kein PK' als ein leeres Array.
Eine extra Methode `noPrimaryKey` würde ich hier nicht einführen. Wenn `getPrimaryKey` in dem Fall `null` zurück liefert, sollte man diesen Wert auch dem Setter übergeben können. Und dann finde ich die extra Methode überflüssig.
(Vermutlich reden wir hier sowieso über einen sehr theoretischen Fall, da man sehr selten PKs löscht, man ändert sie wenn eher direkt).
> rex_sql_column: Bei Primary Key `null` für 'kein PK' nehmen

- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
- redaxo/src/addons/media_manager/lib/managed_media.php
Gemäß Diskussion in Slack. Muss es aber selbst erst noch testen.
> Media Manager: setSourcePath für Effekte nutzbar machen

- redaxo/src/addons/mediapool/assets/mediapool.js
Fixes permissions problem with window.opener if multiple REDAXO instances are open. Happens sometimes, this is more of a workaround though, not sure what the exact issue is.
> Fixes permissions problem with window.opener

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
* Klein/Groß-Schreibung ignorieren
* jpg vs jpeg
closes #1124
> MP: Extension-Check beim Dateien austauschen gnädiger machen

- redaxo/src/addons/media_manager/lib/effects/effect_flip.php
Ab PHP 5.5+ gibt es intern imageflip(). Dadurch wird das Bild auch wesentlich schneller generiert. Außerdem wird der 1px Versatzbug mit meinem Ansatz behoben + Transparenzen bleiben erhalten.
> updated flip_effect

- redaxo/src/addons/media_manager/lib/effects/effect_filter_sepia.php
Pro: 
* kein BC
* schneller
* übersichtlicher code
* Alphasupport
Nachteile:
* Leichte Farbunterschiede zur vorherigen Version, sind aber saubere "Sepia" Werte.
> faster sepia with imagefilter()

- redaxo/src/addons/media_manager/lib/effects/effect_filter_greyscale.php
Auch hier Umbau zum nativen imagefilter()
* ist wesentlich schneller
* übersichtlicher im Code
* Alphasupport
Hier würde ich überlegen, noch IMG_FILTER_BRIGHTNESS mit einzubauen, da man darüber feinere S/W Einstellungen hinbekommt. Aber vermutlich wäre ein eigener Brightness Effekt angebracht
> faster greyscale using imagefilter()

- redaxo/src/addons/phpmailer/pages/config.php
- Die Konfiguration in Spalten organisiert 
- Selects mit BS-Select Class versehen.
> PHPMailer Style: Collumns + Select-Styling

- redaxo/src/addons/phpmailer/lib/mailer.php
Original wird mit Versionsnummer übertragen, das sollte vermieden werden.
> PHPMAILER :: XMailer auf REXMailer gesetzt

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
Auch wenn die Reihenfolge der Spalten eigentlich nicht wichtig ist, fände ich es trotzdem cool, wenn man die Position angeben könnte.
Bevor ich aber die eigentliche Implementierung umsetze, erstmal die Frage, ob wir das überhaupt drin haben wollen.
Habe hier im PR mal die Api angedeutet, wie ich es mir vorstelle.
> rex_sql_table: Positionierung der Spalten

- redaxo/src/core/lib/select.php
Vorschlag zur Vereinfachung von `countOptions()`.
aktuell ist noch "unklar" warum die vorherige Implementierung so "aufwändig" ist und ob sich ggf. irgendwelche addons o.ä. auf diese Implementierung verlassen.
Falls dem so wäre müsste man den hier bestimmten count mit einer anderen Methode zurückliefern.
Refs #998.
ist noch ungetested.
> fixed countOptions()

- redaxo/src/core/assets/standard.js
plus Option um Verhalten gezielt zu steuern (in beide Richtungen)
closes #1180
> Pjax: Bei Formularen nach oben scrollen

- redaxo/src/core/lib/rex.php
- redaxo/src/core/pages/system.settings.php
ggf. könnte es probleme geben falls irgendwo jemand ein bestimmtes format für die version erwartet... bin mir unsicher. alternativ könnte man extra für die system seite und error page ne andere methode machen.
allerdings betrifft es sowieso nur `-dev` versionen, daher passts vllt auch so...
> show current commit hash in rex-version

- redaxo/src/core/lib/list.php
Possible untested fix for https://github.com/redaxo/redaxo/issues/1232
> Quote "rows" which is a reserved keyword on mariadb

- redaxo/src/addons/structure/plugins/version/boot.php
Sicherstellen dass man aus "vorschau" fenstern des frontends über xss nicht auch im backend manipulieren kann.
Durch noopener kann javascript aus deom frontend nicht desseen opener manipulieren. Dies wäre heute möglich wenn es eine xss lücke im frontend gibt und das aktuelle fenster über die vorschua funktion aus dem backend geöffnet wurde
> Prevent leaking the opener into the frontend

- redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
History kann wieder verwendet werden. Achtung! Bei Verwendung von Blöcks werden ggf. einige Slices in der Gegenüberstellung nicht angezeigt. Sie werden aber wiederhergestellt
https://github.com/redaxo/redaxo/issues/1171
> ignore: history_user hinzugefügt

- redaxo/src/core/boot.php
Aktuell kann man den Path-Provider erst in der boot.php eines Addons update-sicher setzen.
Das ist aber meist zu spät.
Daher hier der Vorschlag, bereits in der index.php einen alternativen Path-provider an die core/boot.php übergeben zu können.
Die index.php-Dateien werden bei Updates ja auch nicht angerührt, daher ist die Methode update-sicher.
> Alternativen Path-Provider von index.php aus setzen können

- redaxo/src/core/lib/util/path.php
- redaxo/src/core/lib/util/path_default_provider.php
Ich bin gerade bisschen am testen mit alternativen Path-Providern, da wir überlegen Redaxo bei unseren Yakamara-Projekten etwas umzustrukturieren (unter anderem die geschützen ordner raus aus dem doc-root).
Dabei ist mir aufgefallen, dass manche Pfade besser von `frontend()` ausgehen, als von `base()`. `frontend()` ist gedacht als Doc-Root, bei uns `/public`. `base()` ist das Basisverzeichnis, Projekt-Root.
Außerdem ist mir aufgefallen, dass noch eine Methode fehlt um zu definieren, wo der `bin`-Ordner liegt. Auch wenn die Methode aktuell gar nicht verwendet wird, halte ich sie für sinnvoll. Bisher könnte nur der Installer sie gebrauchen im Update-Skript, wo überhaupt die `bin/console` angelegt wird. Allerdings zum Ausführungszeitpunkt des Update-Skripts wird die Methode noch gar nicht …
> path-provider: Bessere Vererbung und eigene Methode für bin-Ordner

- redaxo/src/addons/metainfo/functions/function_metainfo.php
Das Feld 'Callback' fehlt bisher in der Funktions-Definition
> Ermöglichen, das Feld 'Callback' per PHP zu setzen

- redaxo/src/core/lib/sql/sql.php
fixed #1248
Beim letzten if-Block bin ich mir unsicher, ob dieser überhaupt noch ausgegeben wird, bei meinem Test geht bereits Whoops! dazwischen, aber ich habe mich zunächst am Original orientiert.
> rex_sql: dump() nutzen für debug/error Ausgaben

- redaxo/src/core/lib/login/login.php
fixes #1054 
Ich habe die Warnung bei mir nie.
Denke aber, so sollte das gelöst sein, oder?
https://stackoverflow.com/questions/8549757/why-session-object-destruction-failed
> Session-ID nur neugenerieren, wenn vorhanden

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/pages/media.php
* Benutzer mit eingeschränkten MP-Rechten dürfen nicht in "Keine Kategorie" hochladen
* Benutzer mit eingeschränkten MP-Rechten dürfen trotzdem die Multi-Aktionen (schieben, löschen) machen
closes #1202
> Mediapool Rechte korrigiert

- redaxo/src/core/lib/util/socket/socket.php
fixes #784
Mit `error_get_last` bin ich nicht zum Ziel gekommen, war leer.
Auch ist es so, dass die letzte Warning nicht zum eigentlichen Fehler führt, es werden öfters gleich drei geworfen (siehe Issue), und dabei ist die erste die interessanteste. 
Daher fange ich die nun ab.
> rex_socket: Bessere Fehlermeldungen

- redaxo/src/core/lib/util/socket/socket.php
Ich glaube, zurzeit kommt zwar niemals bei `fsockopen` eine Exception, aber sauberer ist es so trotzdem. Und könnte sich in der Zukunft ja auch mal ändern, dass es doch Exceptions geben kann.
> rex_socket: Error-Handler immer zurücksetzen

- .travis.yml
- E-Mail Notifications wieder aktiv, jetzt wo der master branch geschützt ist (hatte die mal deaktiviert, da es zu oft gebimmelt hat wegen cs etc.)
- MariaDB-Builds vorgezogen, da die langsamer sind
Frage: Müssen wir wirklich 10.1 und 10.2 testen? Bei Mysql testen wir ja auch nicht mehrere Versionen?
(Ich habe keine Ahnung, was es da so für Unterschiede gibt. Frage mich aber auch, ob es dann immer mehr Builds gibt, wenn weitere Versionen rauskommen? Oder immer nur die letzten beiden unterstützen?)
> Travis Anpassungen

- redaxo/src/addons/phpmailer/pages/config.php
- redaxo/src/addons/users/pages/users.php
closes #1245
closes #1270
Im PHPMailer konnte ich es bei mir gar nicht reproduzieren, dass das Passwort-Feld vorausgefüllt wird. Daher die Frage an @alexplusde: Ist das so für dich gelöst?
Auch ping an @skerbis: Bei dir löst es das Problem definitiv noch nicht im Edge?
> autocomplete=new-password nutzen

- redaxo/src/addons/media_manager/lib/managed_media.php
Mediapath muss original bleiben, nur der sourcePath muss aufs Error-Bild gelenkt werden.
fixes #1222
> MM: Bei Benutzung von mediapath bekam man teilweise fälschlicherweise das Error-Bild

- redaxo/src/addons/structure/functions/function_rex_url.php
- redaxo/src/addons/structure/plugins/content/pages/content.php
- redaxo/src/addons/structure/tests/function_rex_url_test.php
- redaxo/src/core/lib/response.php
ping @joachimdoerr @staabm 
`==` war in der Tat falsch, müsste wenn `!=` sein.
Allerdings passte die Art des Vergleichs auch allgemein nicht.
Beispiel `'foo'`: bei `(int) 'foo' == 'foo'` kommt `true` raus.
#1293
> rex_redirect: Korrektur Validierung & rex_response nutzen

- redaxo/src/core/lib/console/application.php
So werden Fatal Error auch durch Symfony behandelt. Insbesondere greift so auch die Unterscheidung, ob man `-v` nutzt oder nicht.
Die beiden oberen Aufrufe waren vor der Änderung, die unteren danach:
> Console: Fatal Error auch abfangen

- redaxo/src/addons/media_manager/install.php
- redaxo/src/addons/media_manager/lang/de_de.lang
- redaxo/src/addons/media_manager/lang/en_gb.lang
- redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/pages/settings.php
- redaxo/src/addons/media_manager/update.php
closes #1192
Ich glaube, ich würde eher nicht den [Link](http://marcjschmidt.de/blog/2013/10/25/php-imagepng-performance-slow.html) aufnehmen. Vielleicht ist der mal nicht mehr erreichbar etc.
> PNG-Kompression: Default-Wert und Hinweis

- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
- redaxo/src/addons/structure/plugins/history/boot.php
- redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
Löst das Problem des Issues nicht komplett, sondern nur auf Coreebene. AddOn Blöcks muss da noch nachziehen @tgoellner
Die Werte in den Slices werden nun beim EP SLICE_SHOW übergeben und müssen nicht mehr einzeln abgefragt werden, was dazu führt, dass die HistoryDaten falsch sind (waren, wenn das in bloecks angepasst ist)
https://github.com/redaxo/redaxo/issues/1206
> sql-Objekt an SLICE_SHOW übergeben und Abgleich history Tabelle

- redaxo/src/core/default.config.yml
- redaxo/src/core/lib/login/login.php
Session Cookie paramter können jetzt via config.yml customized werden (je frontend/backend).
Per Default wird das Session Cookie für Frontend/Backend via httponly gegen zugriffe aus javascript heraus geschützt.
Sobald das backend HTTPS only eingestellt wäre, könnte man dies auch auf den session cookie ausweiten.
SameSite ist noch nicht im php mit nativen Mitteln möglich daher ist dies hier erstmal nicht implementiert.
Refs #1209 
Zum testen muss der Cache  gelöscht werden, damit die neuen defaults greifen.
----
session cookie ist jetzt http-only - dies sollte unbedingt in den release notes auftauchen da dies ggf. bisher funktionierendes javascript beeinträchtigen könnte
> Erlauben die session cookie parameter via config.yml zu setzen

- redaxo/bin/update-requirements
Wir nutzen die letzte Pjax 1.x-Version.
Habe zurzeit keine Zeit (und sehe auch keine direkte Notwendigkeit), 2.x zu testen.
Daher vorerst nicht mehr updaten.
> Pjax nicht updaten

- redaxo/src/core/boot.php
- redaxo/src/core/functions/function_rex_escape.php
- redaxo/src/core/lib/fragment.php
Nach der Diskussion gestern in Slack hier nun also ein Vorschlag für eine `rex_escape`-Funktion.
Der Code ist adaptiert aus Twig:
https://github.com/twigphp/Twig/blob/103cae817d68b56ddcb50c051a6ed7980d746409/lib/Twig/Extension/Core.php#L880-L1106
Allerdings beschränkt auf UTF-8, und ohne die Möglichkeit weitere Escaper-Strategien hinzuzufügen.
Frage: Wollen wir überhaupt diese unterschiedlichen Strategien, oder wollen wir nur "html"?
Habe erst überlegt, die Funktion als `escape`-Methode in `rex_string` zu implementieren, aber denke an dieser Stelle ist eine echte Funktion durchaus sinnvoll, braucht man ja auch wirklich sehr oft.
Weitere Frage: Soll ich alle Stellen im Code anpassen? Folge wäre, bei allen unseren Addons würde die Rex-Mindestversion ansteigen auf 5.4 (also zumindest alle, …
> Neue Funktion rex_escape

- redaxo/src/core/backend.php
- redaxo/src/core/lib/response.php
This adds a Clear-Site-Data header to the logout response which will
delete all relevant data in the caches which may contain potentially
sensitive content.
See https://w3c.github.io/webappsec-clear-site-data/#header for the
definition of the types.
Durch diesen Header werden alle daten im browser von der website gelöscht um die privatsphäre des users zu schützen.
siehe u.a. https://github.com/nextcloud/server/pull/5490
> Send 'Clear-Site-Data' http header on backend logout

- .travis.yml
Wenn man mehrere PRs kurz hintereinander mergt, können manche Jobs nicht beendet werden, da der Commit nicht mehr erreichbar ist.
Dann bekomme ich eine Error-Mail von Travis. (Der letzte PR geht aber erfolgreich durch -> erneute Mail)
Daher nun doch bisschen wieder erhöht.
> travis: git-depth auf 3

- redaxo/src/core/default.config.yml
- redaxo/src/core/lib/login/login.php
this is implemented via manually rewriting of the cookie headers, as
php-src does not yet natively support the SameSite cookie attribute.
Closes #1209.
> use SameSite=Strict for the rex_login session cookie

- redaxo/src/core/console.php
- redaxo/src/core/lib/console/application.php
- redaxo/src/core/lib/console/command.php
- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/packages/package.php
- redaxo/src/core/packages.php
Gestern bin ich über ein größeres Problem bei YDeploy gestolpert, welches ich bisher leider irgendwie gar nicht bedacht habe.
Thomas hat ein Addon geupdated, `ydeploy:diff` ausgeführt, und commitet.
Ich habe anschließend gepullt, und wollte die Änderungen migrieren.
Während der Ausführung von `ydeploy:migrate` wird Redaxo aber ja auch geladen, inklusive Addons.
Somit wurde von dem geupdateten Addon die neue `boot.php` geladen, die DB war aber ja noch alt, da ich sie ja gerade erst updaten wollte. Daher schlug die Migration fehl.
Daher ist nun meine Idee, dass Konsolenkommandos optional im Single-Package-Modus laufen können, dann wird nur der Core und das Package, dass den Command bereitstellt, geladen.
Um das zu ermöglichen, müssen die Kommandos doch über die `package.yml` registriert …
> Konsolenkommandos: Optionaler Single-Package-Modus

- redaxo/src/addons/media_manager/lib/effects/effect_filter_sharpen.php
closes #1343 
Tritt nur auf, wenn man die Felder leer macht. Default sind sie gefüllt (in 5.3 eventuell nicht, da gab es einen Bug mit den Default-werten)
> MM: Fehler in sharpen-Effekt beseitigt

- redaxo/src/core/console.php
- redaxo/src/core/lib/console/application.php
Mir ist aufgefallen, dass wenn der Autoload-Cache noch nicht da ist, die Commands nicht gefunden werden, da die Addons ja jetzt erst direkt vor Ausführung des Commands geladen wurden.
Daher habe ich es jetzt so geändert, dass immer (frühzeitig) alle Addons gelistet werden. Und nur das Booten geschieht später, und halt ggf. begrenzt auf ydeploy.
> Console: Alle Packages immer listen, aber ggf. nur ydeploy booten

- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/package.yml
detect content type in managed_media like we do in function_rex_mediapool.php
https://github.com/redaxo/redaxo/blob/a6db3cd0a94fd9bb4aea65a59aaf42457834be6f/redaxo/src/addons/mediapool/functions/function_rex_mediapool.php#L290-L297
> mpool: finfo php extension soll optional sein

- redaxo/src/core/pages/login.php
fixes #1336 
@Hirbod kannst du das bestätigen?
Das Entfernen des name-Attributs ist unnötig. Das später kommende hidden-Feld gewinnt immer.
Und der Chrome bietet so aber an, das Passwort zu speichern
> Passwort speichern im Chrome ermöglicht

- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/default.config.yml
- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lib/login/backend_password_policy.php
- redaxo/src/core/lib/login/password_policy.php
- redaxo/src/core/pages/profile.php
- redaxo/src/core/tests/login/password_policy_test.php
closes #1331, closes #1361 
Das mal als Ansatz. Man könnte so in der config.yml paar einfache feste Regeln festlegen. Und bei Bedarf kann man aber auch die Klasse erweitern, wenn man noch komplexere Logik reinbringen möchte (zum Beispiel ob das Passwort schon mal verwendet wurde etc.).
@staabm was meinste dazu?
Wie sieht es aus mit dem Default-Wert? Soll es default überhaupt Regeln geben, oder so wie bisher, alles frei?
> Passwortregeln

- redaxo/src/addons/structure/plugins/history/assets/history.js
Das ist ein sehr nerviges [Flexbox-Issue](https://github.com/philipwalton/flexbugs#14-flex-containers-with-wrapping-the-container-is-not-sized-to-contain-its-items), speziell im Safari <11. Ich habe lange rumprobiert, denke aber, dass man es nicht behoben kriegt, ohne das Flexbox-Layout grundlegend umzustruktieren und damit vermutlich Einschränkungen hinnehmen zu müssen. Denn aktuell funktioniert das Layout ziemlich gut, und ohne Flexbox wäre manches nicht so einfach machbar.
Mir ist nur ein Bugfix eingefallen, der gut anwendbar ist, ohne die anderen Browser zu beeinträchtigen: Per JS wird gemessen, ob die Kindelemente 0 px hoch sind (Ergebnis des Flexbox-Issues). Ist das der Fall, wird der umliegende Container gemessen, der die richtige Höhe vorgibt, und diese wird ihm nochmal dediziert …
> History: Bugfix für Flexbox-Probleme

- redaxo/src/addons/users/pages/users.php
Wundere mich eigentlich, dass das noch keiner gemeldet hat, nervt mich schon länger.
Wenn man einen neuen Benutzer anlegt, ist immer das dritte Feld fokussiert.
> Benutzerverwaltung: Autofocus auf erstes Feld

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/package.yml
* blocked_extensions erweitert um pht, htaccess und htpasswd
* Zusätzlich wenn Dateiname mit Punkt beginnt, durch _ ersetzen
> Mediapool security fixes

- redaxo/src/addons/phpmailer/pages/config.php
... id="phpmailer-password" type="password" ...
> PHPMailer: Passwort nicht im Klartext anzeigen - config.php

- redaxo/src/addons/mediapool/package.yml
Siehe https://github.com/FriendsOfREDAXO/uploader/issues/4
/cc @pixelpaul @pixeldaniel
> svg und mp4 im Medienpool-Upload erlauben

- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/lib/media_manager.php
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/media_manager/update.php
Das Problem tritt auf, wenn der MediaPath über Effekte angepasst wird, dass passiert zurzeit in den beiden Effekten `mediapath` und `yfeed`.
Genauer gesagt sind es zwei Probleme, die dabei auftreten:
Angenommen, wir haben einen MM-Typen der der mediapath-Effekt nutzt (also den Pfad zu den Original-Dateien ändert, nicht mehr `/media`).
Nun rufen wir eine Datei `test.jpg` über diesen Typen auf.
Problem 1:
Der MM bildet den Cache-Pfad, dieser enthält zurzeit aber den MediaPath (gehasht). Bevor die Effekte nicht ausgeführt wurden, kennt der MM aber nicht den tatsächlichen, umgebogenen MediaPath. Daher wird ein falscher Cache-Pfad gebildet. Da die Datei dort aber nicht existiert, werden die Effekte ausgeführt.
Danach prüft der MM erneut den Cache-Pfad, dieses Mal mit dem richtigen MediaPath. …
> Media Manager: Fehlerhaftes Caching

- .travis.yml
Die aktuelle Version enthält Bugs, weshalb die Builds zurzeit rot werden.
Habe eine Env-Variable in den Travis-Settings abgelegt, sodass wir zukünftig die Version ohne Commit/Pr steuern können.
> CS-Fixer-Version über Travis-Env-Variable steuern

- redaxo/src/addons/debug/lib/sql_debug.php
Wenn das Debug Addon aktiviert ist, wurden bei jedem Aufruf diese Warnungen geloggt.
> | Warning | Declaration of rex_sql_debug::execute(array $params = Array) should be compatible with rex_sql::execute(array $params = Array, array $options = Array)
| Warning | Declaration of rex_sql_debug::setQuery($qry, array $params = Array) should be compatible with rex_sql::setQuery($query, array $params = Array, array $options = Array)
> Debug Addon: Methodensignatur angeglichen

- redaxo/src/core/tests/util/socket_response_test.php
Fixed PHP-CS-Fixer Recommendation
```
1) redaxo/src/core/tests/util/socket_response_test.php (php_unit_construct)
---------- begin diff ----------
--- Original
+++ New
@@ @@
$this->assertSame('Value2', $response->getHeader('Key2', 'default'), 'getHeader($key, $default) returns the value of the key');
-        $this->assertSame(null, $response->getHeader('Key3'), 'getHeader($key) returns null for non-existing keys');
+        $this->assertNull($response->getHeader('Key3'), 'getHeader($key) returns null for non-existing keys');
$this->assertSame('default', $response->getHeader('Key3', 'default'), 'getHeader($key, $default) returns $default for non-existing keys');
}
public function testGetBody()
{
$body = "body1\r\nbody2";
$response = $this->getResponse("HTTP/1.1 200 OK\r\nKey: …
```
> Fixed PHP-CS-Fixer Recommendation

- redaxo/src/addons/media_manager/lib/media_manager.php
- redaxo/src/addons/media_manager/tests/media_manager_test.php
Das Resultat von `$this->media->getMediaFilename()` kann sich über die Effekte ändern, vor allem wenn der mediaPath neu gesetzt wird.
Gecacht werden muss aber gerade über den original übergebenen Dateinamen, damit beim zweiten Aufruf der MM die Cache-Datei findet, ohne die Effekte zu durchlaufen.
@tbaddade Bitte testen, ob damit unsere Probleme behoben sind.
> Media Manager: Original-Filename für Cache-Pfad nutzen

- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/package/uninstall.php
Console Command um Package zu de-installieren
> Added Console Command package:uninstall

- redaxo/src/core/lib/console/cache/clear.php
- redaxo/src/core/lib/console/command.php
- redaxo/src/core/lib/console/package/activate.php
- redaxo/src/core/lib/console/package/deactivate.php
- redaxo/src/core/lib/console/package/install.php
- redaxo/src/core/lib/console/package/uninstall.php
- redaxo/src/core/tests/console/command_test.php
Hier der "Vorher (oben) / Nachher (unten)"-Vergleich:
Da ich denke, dass man das auch noch in anderen Commands gebrauchen kann (zum Beispiel eben in cache:clear), habe ich es als allgemeine Methode in der Command-Klasse angelegt.
> Console: Besseres Dekodieren der i18n-Messages

- redaxo/src/core/lib/csrf_token.php
http://symfony.com/blog/cve-2017-16653-csrf-protection-does-not-use-different-tokens-for-http-and-https
Ich verstehe es nicht hundertprozentig, aber vermute, dass es uns auch betrifft. Jedenfalls sollte es nicht schaden, die Tokens zwischen http/https zu trennen.
> CSRF-Tokens unterscheiden nach http/https

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lib/request.php
- redaxo/src/core/lib/rex.php
- redaxo/src/core/pages/setup.php
Closes https://github.com/redaxo/redaxo/issues/1340.
Erstmal nur eine "einfache Warnung" im setup. Ein "richtiges Notificationscenter" kann später noch etabliert werden.
> Warnung ausgeben im Setup, wenn kein HTTPS verwendet wird.

- redaxo/src/addons/cronjob/lib/command/run.php
- redaxo/src/core/lib/console/cache/clear.php
- redaxo/src/core/lib/console/package/activate.php
- redaxo/src/core/lib/console/package/deactivate.php
- redaxo/src/core/lib/console/package/install.php
- redaxo/src/core/lib/console/package/uninstall.php
Die Klassen gehören meiner Meinung nach nicht zur public Api, darauf soll man sich nicht verlassen können, dass die Klassen so existieren.
(Nur die Kommandos selbst gehören zur Public Api).
> Commands als internal classes markieren

- redaxo/src/core/assets/standard.js
Finde das störend, wenn man das Formular ausfüllt, und per Tab von Feld zu Feld springt, dass man beim Passwortfeld doppelt Tab drücken muss, um das nächste Feld zu erreichen.
Mir ist gerade passiert, dass ich ohne zu schauen, Tab einfach gedrückt habe, dann losgetippt, und gewundert, warum das Feld leer blieb (da Focus auf Toggle-Button).
> Toggle-Button in Passwortfeldern ohne Tabindex

- redaxo/src/core/lib/login/backend_login.php
Bisher wurden die Tokens nur bei explizitem Logout gelöscht. Und beim Sessionablauf php-seitig natürlich auch.
Aber nicht, wenn die Session gemäß unserer Einstellung aus der config.yml abgelaufen ist.
> CSRF-Tokens löschen bei Zeitbasierter Logout

- redaxo/src/addons/cronjob/pages/log.php
Maskierte Zeilenumbrüche \n aus dem Log als HTML <br /> ausgeben
> Systemlog: Zeilenumbrüche darstellen

- redaxo/src/core/lib/util/logger.php
- redaxo/src/core/pages/system.log.php
* In Data-Ordner statt Cache-Ordner (closes #1546)
* Zeilenumbrüche ausgeben
> System-Log: Pfadänderung & Zeilenumbrüche

- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/lib/media_manager.php
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/media_manager/tests/media_manager_test.php
Und täglich grüßt das Murmeltier.. :(
Vielleicht passt es dieses Mal dann endlich..
@isospin Kannst du bestätigen, dass der Fix bei dir auch funktioniert?
> Cache-Path bei Nutzung von rex_media_manager::create() korrigiert

- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/tests/managed_media_test.php
Der SourcePath wird bereits in mit setMediaPath gesetzt und dort ist auch der file_exists-check mit drin. Daher muss die Zeile hier weg.
> MM: Errorbild kommt nicht bei nicht existenten Dateien

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_select_test.php
Der Counter kann mit der Methode `next()` über das Ende der vorhandenen Daten hinaus erhöht werden. Sobald dieser Fall eingetreten ist, kann mit `hasNext()` nicht mehr festgestellt werden, ob tatsächlich noch Daten vorhanden sind. 
Hiermit wird das Problem behoben
> rex_sql: Fehler bei Counter-abfrage beheben

- redaxo/src/addons/structure/plugins/content/lang/de_de.lang
- redaxo/src/addons/structure/plugins/content/lang/en_gb.lang
- redaxo/src/addons/structure/plugins/content/pages/templates.php
Beim Löschen eines Templates der Hinweis in welchen Artikeln es benutzt wird.
closes #1477
> Template löschen: Hinweis welche Artikel es benutzen

- .travis.yml
Ich wollte nicht noch einen weiteren build dazunehmen. Mariadb mit php 7.2 sollte wohl die wichtigste variante sein
> Travis: Mariadb mit php 7.2 testen

- redaxo/src/addons/users/pages/users.php
user-verwaltung: wenn user admin ist und man deaktiviert die admin-checkbox, wird die rollen-selectbox nicht aktiviert (bug fix javascript, da jetzt mit selectpicker und nicht mehr einfache multiselectbox)
> User-Verwaltung: Rollen-Select wird nicht reaktiviert

- redaxo/src/core/lib/sql/sql.php
Bezug auf Issue "rex_sql->getRow: Docs missverständlich (#1572)". Der Text legt nahe, dass nach dem Auslesen des Satzes mit getRow() und dem nächsten Auslesen mei getRow() der Satzzeiger weiterbewegt wird. Passiert aber nicht, sondern nur beim ersten getRow()-Aufruf zur Initialisierung. Dokumentationstext angepasst mit Hinweis auf notwendigen Aufruf von next()
closes #1572
> Kommentar zu rex_sql::getRow() korrigiert (#1572)

- redaxo/src/core/pages/setup.php
closes #861
Vergleicht nach `https://www.redaxo.org/`, weil es zu Problemen kommt, wenn keine Domain in der `default.config.yml` eingetragen wird.
> Aktuelle Webserver-Adresse automatisch eintragen

- redaxo/src/core/functions/function_rex_other.php
Nach dem Cache-Löschen ist zwar die Cache-Datei von `rex_config` gelöscht, aber die alten Config-Werte sind noch php-seitig in der Klasse gecacht.
> rex_delete_cache(): rex_config zurücksetzen

- redaxo/src/addons/backup/lib/backup.php
Ich denke, es ist hier sinnvoll, vor dem EP den Cache zu löschen, damit im EP nicht mit alten Cache-Dateien gearbeitet wird.
Bisher wird nur weiter unten der Cache gelöscht, nach dem Import der zum Backup gehörenden PHP-Datei. Denke dort muss es auch bleiben.
Daher als zusätzlicher Aufruf.
> Import Backup: Cache löschen vor EP

- redaxo/src/core/lib/login/backend_login.php
Wenn man im Frontend z.B: über
if(rex_backend_login::hasSession()){
...
}
nur wissen möchte ob es eine Backend Session gibt, sollte das nicht automatisch dazu führen dass generell mal eine neue Session gestartet wird, oder?
> hasSession() sollte keine Session starten

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
fixes #1630 
Der erste Fulltext-Index wird jeweils mit im Haupt-Alter-Statement erstellt, alle weiteren dann separat.
> rex_sql_table: Fulltext-Indexe separat erstellen

- redaxo/src/core/lib/login/complex_perm.php
Siehe Slack (@Hirbod), aktuell sieht man in der Message nicht, bei welcher Klasse die Registrierung scheitert.
> rex_complex_perm: Bessere Exception-Message

- redaxo/src/addons/project/package.yml
Ich überlege gerade, ob es sinnvoll ist, das "project"-Addon default spät zu laden.
Im Normalfall rate ich davon ab, `load: early/late` in Addons zu nutzen. Das gilt aber vor allem für veröffentlichte Addons. Dort sollte man es eher bei der von Redaxo erzeugten Ladereihenfolge gemäß Abhängigkeiten belassen.
(Nicht zu verwechseln mit dem EARLY/LATE-Parameter bei den EPs, der bei Bedarf jederzeit gerne verwendet werden kann. Es geht nur um die Gesamt-Lade-Steuerung des Addons in der `package.yml`).
Ich denke aber, das project-Addon ist etwas anderes, und da kann es ganz praktisch sein, wenn die Fragmente daraus zum Beispiel definitiv greifen. Das wäre hiermit erreicht, da der project-Fragmente-Ordner somit auch als letztes registriert werden würde, und der letzte gewinnt.
Es kann auch …
> project-Addon spät laden

- redaxo/src/core/lib/util/string.php
- redaxo/src/core/tests/util/string_test.php
Überall wo die Methode bisher verwendet wird, werden die Attribute als HTML-Attribute ausgegeben.
Somit sehe die Änderung als Bugfix an, nicht als bc break.
> rex_string::buildAttributes: Werte wurden nicht escaped

- redaxo/src/addons/structure/lib/linkmap/linkmap.php
- redaxo/src/addons/structure/lib/linkmap/var_link.php
- redaxo/src/addons/structure/lib/linkmap/var_linklist.php
Hintergrund: In einem aktuellen Projekt leiten wir manche Artikel auf die erste Kindkategorie weiter. Die Redaktion hat jetzt zur besseren Übersicht, da kein Artikelinhalt hinterlegt ist, die Artikelnamen gelöscht. Somit erscheinen in den Widgets die Namen nicht mehr und man geht fälschlicherweise davon aus, dass in dem Widget nichts mehr zugewiesen ist. So werden zumindest noch die Ids angezeigt
> In den Link-Widgets die Artikel-Ids ausgeben

- redaxo/src/addons/mediapool/pages/media.php
Der EP erlaubt, in der Formularansicht bzw. Detailansicht eines Bildes im Medienpool in der Sidebar rechts eigene Informationen einzufügen. Der Default (Anzeige des Bildes) kann ersetzt, ergänzt oder entfernt werden. Referenz: Issue closes #1683
> EP MEDIA_DETAIL_SIDEBAR hinzugefügt

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/tests/mediapool_functions_test.php
In den blocked_extensions haben wir nur `php3` bis `php7`.
Teils werden aber auch Extensions wie `php71` ausgeführt. Daher nun ein generischer Check auf alle `phpX`-Extensions.
> Medienpool: Alle PHP-Extensions blockieren

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lib/setup/setup.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/update.php
Mein Vorschlag für einen allerersten Schritt in Richtung utf8mb4.
So wird für die Connection schon mal utf8mb4 genutzt, sodass überhaupt theoretisch 4-byte-zeichen gespeichert werden können.
Ich denke, das sollte eigentlich komplett kompatibel sein.
Im Issue gab es viel Zustimmung für die allgemeine Anhebung der Mindest-Mysql-Version, um utf8mb4 zu ermöglichen. Somit würde ich hier auch nicht zweigleisig fahren, sondern zumindest für die Connection einheitlich utf8mb4 nutzen.
Falls wir den Weg so gehen wollen, würde ich noch in der update.php des Cores einen Check einbauen und ein Update mit einer älteren Mysql-Version verhindern.
ref #638
> utf8mb4 für die sql-connection nutzen

- redaxo/src/core/lib/form/form.php
closes https://github.com/redaxo/redaxo/issues/1700
> rex-form: Keine führenden/nachfolgenden whitespaces speichern

- redaxo/src/core/lib/util/i18n.php
behebt eine Warnung `Warning: Invalid argument supplied for foreach() in C:\xampp7.1.4\htdocs\redaxo\redaxo\src\core\lib\util\i18n.php on line 169`.
Ursache ist vermutlich dass meine `config.yml` noch nicht auf dem aktuellsten Stand ist, d.h. es könnte sein dass diese Warnung nur in Entwicklungssystemen auftritt.
Da der Fix einfach ist, hab ich es mal hier reingestellt, ob man das wirklich so übernehmen sollte können wir diskutieren.
> Warnung beheben wenn lang_fallback nicht definiert ist

- redaxo/src/core/backend.php
closes #1747 
Der `Clear-Site-Data`-Header löscht im Browser die Cookies mit. Damit ist auch der neue CSRF-Token für den erneuten Login ungültig.
Ein anschließender Reload/Redirect auf die Login-Page behebt das Problem.
> Reload nach Logout

- redaxo/src/core/lib/login/perm.php
Die Perms werden bei der Ausgabe noch automatisch durch `rex_select` escaped.
> Kein doppeltes Escaping der Perms

- redaxo/src/addons/mediapool/boot.php
Gerade in letzter Zeit kam vermehrt die Frage auf, wie man die Funktionen denn im Frontend nutzen kann.
Ich denke, wir sollten sie daher auch im Frontend immer einbinden, damit sie direkt zur Verfügung stehen.
refs #1614
> MP-Funktionen auch im Frontend einbinden

- redaxo/src/core/backend.php
Aktuell konnte man sich nicht abmelden. Der Logout-Vorgang wurde hierbei teilweise indirekt durch den "Clear-Site-Data"-Header vorgenommen.
refs #1753
> Logout Fix

- redaxo/src/core/default.config.yml
- redaxo/src/core/pages/setup.php
Nach dem Update auf eine neue Redaxo-Version würde in der Config `use_https` auf `true` gesetzt. Dies soll beim Update, falls der Eintrag noch nicht in der `config.yml` vorhanden ist, immer `false` sein.
Bei einer Erst-Installation soll dieser Wert weiterhin `true` vorschlagen (HTTPS für Frontend und Backend).
// cc @tbaddade @staabm
> HTTPS default nicht aktiv

- redaxo/src/addons/users/lib/role.php
> Warning: count(): Parameter must be an array or an object that implements Countable
refs #1667
> Countable-Warning (php 7.2) vermeiden

- redaxo/src/core/update.php
Damit man nach dem Update in der config.yml die neuen Optionen direkt zur Verfügung hat.
> Beim Core-Update die config.yml aktualisieren

- redaxo/src/addons/structure/pages/index.php
refs #994
/cc @darwin26, @skerbis, @elpschulzo, @alexplusde, @DanielWeitenauer
Ist nicht als allumfassende Lösung gedacht, aber aus meiner Sicht macht es das zumindest besser, als den Status Quo.
Wenn alle Mountpoint aus der selben Oberkategorie stammen, oder alle aus dem Root, dann werden sie nun nach Prio sortiert.
Wenn sie aus unterschiedlichen Ebenen stammen, dann weiterhin nach Name, mangels schneller Alternativen.
> Mountpoints nach Prio sortieren, wenn gleiche Oberkategorie

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/mediapool/pages/upload.php
closes #1483
Wir brauchen das zwingend in einem Projekt, bisher muss es @dergel dort immer händisch reinmanipulieren.
> Medienpool: Optionale MimeType-Whitelist

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
In gewisser Weise ist das ein BC Break.
Aber das war so doch totaler Quatsch. Ein erster Parameter `$FILE`, der nicht genutzt wurde, und stattdessen wurde hartkodiert mit `$_FILE['file_new']` gearbeitet.
(`$userlogin` wurde auch nicht genutzt, da ist die Änderung unproblematisch.)
> rex_mediapool_updateMedia: Parameter korrekt nutzen

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/pages/media.php
Der allgemeine Fix ist problematisch (leere File-inputs löschen), da kommt es im Backend dann zu Notices, da übertragene leere File-inputs != gar nicht übertragene File-inputs.
Ich schlage vor, Pjax für die Uploadformulare einfach generell zu deaktivieren.
closes #1674
Im heute erschienenen Safari 11.1.1 ist der Fix übrigens leider noch nicht enthalten, obwohl es in der Safari Technology Preview ja bereits gefixt ist.
> MP: Pjax deaktivieren für Upload-Formulare

- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
In templates war es interessanterweise schon deaktiviert
> Rechtschreibprüfung in Modul ein/ausgabe deaktiviert

- redaxo/src/core/lib/form/config_form.php
- redaxo/src/core/lib/form/form.php
- redaxo/src/core/lib/form/form_base.php
Durch die neue Basisklasse hatte sich die Reihenfolge im Konstruktor bisschen geändert, loadBackendConfig wurde früher aufgerufen. Darin wird aber ein EP aufgerufen, der unter anderem vom MM genutzt wird. Und durch den frühereren Aufruf fehlte nun die Initialisierung des SQL-Objekts in rex_form.
Dadurch kam es zu einer Exception beim Hinzufügen eines MM-Types.
Daher lasse ich nun die Kindklassen die Methoden aufrufen am Ende des Konstruktors.
closes #1801
> fix rex_form

- redaxo/src/core/lib/packages/addons/addon.php
- redaxo/src/core/lib/packages/plugins/plugin.php
- redaxo/src/core/lib/util/i18n.php
- redaxo/src/core/tests/util/i18n_test.php
closes #1802 
Waren gleich zwei Probleme:
- Zum Einen haben wir leere Übersetzungen als vorhanden angesehen (also `key = ` mit leerem Value)
- Zum Anderen funktionierten die Fallbacks nicht bei diesen Kurzformen innerhalb der Packages, wo man den Package-Präfix weglassen kann
/cc @schuer
> Fallback-Übersetzungen korrigiert

- redaxo/src/core/lib/util/string.php
- redaxo/src/core/tests/util/string_test.php
refs https://github.com/redaxo/redaxo/pull/1687#issuecomment-389761965
Ich hab noch mal über die BC-Break-Problematik von `rex_string::buildAttributes` mit @tbaddade gesprochen.
Das Problem ist halt, dass er die Methode oft verwendet im Frontend, und oftmals URLs da reinwirft, so wie sie aus den url-Funktionen von Redaxo kommen.
```php
$attributes = [
'href' => $article->getUrl(),
'data-foo' => getFoo(),
];
rex_string::buildAttributes($attributes);
```
Das Escaping aus 5.6 ist also vom Prinzip hilfreich für uns, da die Attributes bisher nicht escaped übergeben wurden.
Ausnahme sind halt die URLs, weil Redaxo da leider bereits `&amp;` nutzt. 
Damit das oben weiter funktioniert, müsste man nun also `$article->getUrl([], '&')` schreiben. Und vor allem muss man alle Stellen finden.
Daher …
> rex_string::buildAttributes: Doppeltes Escaping von "&" vermeiden

- redaxo/src/addons/backup/lib/backup.php
- redaxo/src/core/functions/function_rex_other.php
closes #1819 
Eingeführt hatte ich das in https://github.com/redaxo/redaxo/pull/1624, da mir aufgefallen war, dass nach einem DB-Import rex_config noch die alten Werte enthält.
Ich denke, ich würde das nun aber doch aus `rex_delete_cache` wieder ganz rausnehmen, da es eben Probleme macht. Stattdessen muss man `rex_config::refresh()` selbst aufrufen, wenn man direkt was an der `rex_config`-Tabelle ändert.
> rex_delete_cache: rex_config nicht neu laden

- redaxo/src/addons/backup/lib/cronjob.php
vorher: `1 old backups deleted`
jetzt: `1 old backup(s) deleted`
siehe https://github.com/redaxo/redaxo/issues/1765#issuecomment-397955248
> Schönere Statusmeldung wenn nur 1 Backup gelöscht wird

- redaxo/src/core/lib/list.php
Closes https://github.com/redaxo/redaxo/issues/1724
Ungetestet!
> "start" als Fallback Cursorname in rex_list wg Rückwärtskompatibilität

- redaxo/src/core/lib/list.php
Damit die Url weniger kryptisch wirken
Closes https://github.com/redaxo/redaxo/issues/1839
> rex_list verwendet kürzere hashes in urls

- redaxo/src/addons/metainfo/extensions/extension_content_sidebar.php
- redaxo/src/addons/structure/plugins/content/boot.php
- redaxo/src/addons/structure/plugins/content/package.yml
Da die Metadaten nicht vom Addon Metainfo abhängen.
Als Vorbereitung für Anpassungen auf dem Weg zu Structure 3.
> Sidebar Metadaten verschieben

- redaxo/src/core/lib/error_handler.php
- redaxo/src/core/lib/util/editor.php
Aktuell bekommt man Fehler, wenn kein Editor ausgewählt wurde.
Außerdem schlage ich vor, den Editor immer an whoops weiterzugeben, denn auch wenn kein Editor ausgewählt wurde, können die `rex://`-Pfade ja trotzdem verlinkt werden.
Dafür brauchen wir aber noch diesen Fix upstream: https://github.com/filp/whoops/pull/582
> Fehler vermeiden, wenn kein Editor ausgewählt

- redaxo/src/core/lib/util/editor.php
Ein `rex://`-Pfad zum Beispiel kann ja nicht von den normalen Editor-URLs geöffnet werden.
Daher das Default-Handling für Pfade mit `://` unterbinden.
Die Pfade werden also nur verlinkt, wenn Extensions dazu eine URL liefern.
> Editor-Url: Default keine "URLs" verlinken

- redaxo/src/core/lib/console/db/connection_options.php
Mir ist aufgefallen, dass `mysqldump` keine `--database`-Option hat.
Daher nun die Datenbank ohne Optionsname, das wird so von `mysql` und `mysqldump` unterstützt.
Beispiele:
```
// import
redaxo/bin/console db:conn | xargs mysql < dump.sql
// export
redaxo/bin/console db:conn | xargs mysqldump > dump.sql
```
> db:connection-options: auch mysqldump unterstützen

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
"Skriptfehler" könnte man als leser auch auf Javascript beziehen. Daher ein wenig präzisiert.
> Erklärung bzgl. debug-mode präzisiert

- redaxo/src/core/lib/autoload.php
Ungetestet. Hier erstmal als PR um die Idee festzuhalten.
Ziel: schnelleres autoloading
> ClassMapAuthoritative=true im ComposerClassloader verwenden

- redaxo/src/core/pages/system.report.html.php
https://github.com/redaxo/redaxo/pull/1928#issuecomment-408586766
Mein Vorschlag ist nun erstmal die booleschen Werte neutral als yes/no auszugeben (so wie in der markdown- und cli-Variante), ohne grün/rot und so.
Wenn jemand möchte, kann er sich aber auch gerne an eine bessere Darstellung machen, bei der rüber kommt, was der aktuelle Zustand und was der Sollzustand ist, mit eventuellem Erklärtext.
Darum möchte ich mich jetzt aber gerade nicht kümmern, mir geht es ja erstmal weniger darum, das System über den Bericht zu prüfen, sondern mehr darum, anderen schnell mitteilen zu können, was für ein System man vorliegen hat. Daher hier erst mal dieser Vorschlag, um der Verwirrung vorzubeugen.
> Systembericht: Boolesche Werte neutral als yes/no

- redaxo/src/core/lib/util/i18n.php
Ungetestet.
Todo
War sichtbar in messungen aus https://github.com/redaxo/redaxo/issues/1919
> I18n::translate() mikro-Optimierungen

- redaxo/src/core/pages/profile.php
https://github.com/redaxo/redaxo/issues/1973
1. Sortierung der Sprachen
2. Änderung ist sofort nach Speichern sichtbar.
Vorher: 
Nachher:
> Profil-Settings: Language

- redaxo/src/core/lib/response.php
fixes #1949 
Der Chrome kann scheinbar keine fonts preloaden ohne das "crossorigin"-Attribute. Das sorgte aktuell dafür, dass die fonts (mindestens im Chrome) doppelt geladen wurden.
siehe: [bugs.chromium.org comment 13/14](https://bugs.chromium.org/p/chromium/issues/detail?id=678429#c14)
> fix font preload

- .travis.yml
Stattdessn habe ich https://prettyci.com/ zum test installiert, was via github [checks-tab](
https://blog.github.com/2018-05-07-introducing-checks-api/) funktioniert.
Prettyci ist in wenigen Sekunden abgelaufen und blockiert auf diese art auch keinen travis job.
Somit werden die anderen travis jobs schneller fertig
> Codestyle CI job entfernt

- redaxo/src/addons/cronjob/lib/manager_sql.php
Wenn die lokale Zeit nicht GM ist kann es zu einem Versatz kommen und der nächste Cronjob könnte erst verspätet ausgeführt werden.
> Datenbank UNIX_TIMESTAMP könnte andere lokale Zeit haben

- redaxo/src/core/lib/response.php
- redaxo/src/core/lib/util/i18n.php
- redaxo/src/core/pages/profile.php
- redaxo/src/core/pages/setup.php
- redaxo/src/core/pages/system.settings.php
- redaxo/src/core/tests/util/i18n_test.php
Erlaubt es anderssprachige Übersetzungen zu ermitteln, ohne die "default-locale" umstellen zu müssen.
damit man in situationen wie
https://github.com/redaxo/redaxo/blob/fc666da432c9be44ceef57b917ef81a01131fa12/redaxo/src/core/pages/profile.php#L40-L43
nicht die system locale-umstellen und wieder re-storen muss.
> rex_i18n::msgInLocale() hinzugefügt

- redaxo/src/core/lib/error_handler.php
Ich weiß nicht so ganz genau, wann das auftritt, aber hatten das letztens bei Jan, und bei mir kam es auch gerade vor.
Ich glaube, wenn der Weg über die shutdown-Function geht, kann das vorkommen.
> Error Handler: Frames haben teils keine Datei/Zeile

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/pages/setup.php
nur eine warnung als hinweis an den user. kein blocker o.ä. sodass das setup weiterhin normal durchgeführt werden kann, mit den gleichen php versionen wir auch unter R5.6
> Im Setup warnen, wenn eine veraltete PHP Version verwendet wird

- redaxo/src/addons/be_style/plugins/customizer/boot.php
Sodass Templates/Module etc. per default auch gehighlighted werden
> 'textarea.rex_code' zu den default CodeMirror selektoren hinzugefügt

- redaxo/src/core/lib/rex.php
vorher konnte der git hash nicht auf windows ermittelt werden, da bereits `which git` auf einen `unkown internal command "which"` fehler gelaufen ist
> Git Versionsnummer bestimmung auf Windows Servern ermöglichen

- .php_cs.dist
- redaxo/src/addons/debug/lib/api_function_debug.php
- redaxo/src/addons/debug/lib/sql_debug.php
- redaxo/src/addons/structure/lib/structure_element.php
- redaxo/src/addons/structure/lib/var_article.php
- redaxo/src/addons/structure/lib/var_category.php
- redaxo/src/addons/structure/plugins/content/lib/var_template.php
- redaxo/src/core/lib/api_function.php
- redaxo/src/core/lib/autoload.php
- redaxo/src/core/lib/base/factory_trait.php
- redaxo/src/core/lib/base/instance_pool_trait.php
- redaxo/src/core/lib/base/singleton_trait.php
- redaxo/src/core/lib/config.php
- redaxo/src/core/lib/error_handler.php
- redaxo/src/core/lib/login/complex_perm.php
- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/packages/plugins/plugin.php
- redaxo/src/core/lib/util/formatter.php
- redaxo/src/core/lib/util/socket/socket.php
- redaxo/src/core/lib/util/stream.php
- redaxo/src/core/lib/var/var.php
- redaxo/src/core/vendor/filp/whoops/src/Whoops/Exception/FrameCollection.php
- redaxo/src/core/vendor/symfony/debug/ErrorHandler.php
- redaxo/src/core/vendor/symfony/debug/Exception/ContextErrorException.php
Als früher Vorgriff auf https://wiki.php.net/rfc/deprecations_php_7_4.
(Auch wenn da noch nichts entschieden ist)
> self::class und static::class nutzen

- redaxo/src/addons/mediapool/lib/form_element/media.php
- redaxo/src/addons/mediapool/lib/form_element/medialist.php
- redaxo/src/addons/structure/lib/linkmap/form_element/linklist.php
- redaxo/src/addons/structure/lib/linkmap/form_element/linkmap.php
- redaxo/src/core/lib/form/elements/prio.php
Die neu eingeführte Klasse `rex_config_form` erzeugt ein "whoops" beim `$form->addLinkmapField`. Grund ist die Klasse `rex_form`, in der der Parameter `$table`erwartet wird. Hier muss noch auf die gemeinsame BAsisklasse `rex_form_base`geändert werden.
> Parametertyp falsch: rex_form_widget_linkmap_element

- redaxo/src/core/default.config.yml
Siehe http://symfony.com/blog/cve-2013-5750-security-issue-in-fosuserbundle-login-form wg mögliche. Dos attacken
Closes https://github.com/redaxo/redaxo/issues/353
Ungetestet
> 4096 Zeichen maximale Passwortlänge per Default

- redaxo/src/core/lib/response.php
closes https://github.com/redaxo/redaxo/issues/2031
> Warnung behoben wenn der Http-Client keinen Http-User-Agent sendet

- redaxo/src/addons/media_manager/fragments/mmeffectslist.php
- redaxo/src/addons/media_manager/pages/effects.php
- redaxo/src/addons/media_manager/pages/types.php
Bezug: #1444
Die Typenliste ist um die Anzeige der Effekte je Typ erweitert. Die Effekte werden als Titel 
unterhalb der normalen Tabellenzeile eingeblendet.
* Hinter dem Typ-Titel (Spalte2) sind zwei Button, mit denen (a) die Effekt-Details (ursprünglicher
Issue #1444) und (b) der Bilderlink (Zusatzwunsch von @medienfeuer) eingeblendet werden. Das auf Typ-Ebene.
* Zusätzlich sind vergleichbare Button in der Titelzeile, die die Anzeige für die gesamte Tabelle
ein- bzw. ausschalten.
Das nötige JS und CSS wird über `types.php` bzw. `effects.php` mit ausgegeben. Document-Ready wird nicht benötigt, da die JS-Funktionen über onclick aktiviert werden. 
Alle Zusatzelemente innerhalb der Tabelle werden in den eh vorhandenen Callbacks eingeschleust
- $list->setColumnFormat('name', 'custom', …
> Erweiterte Listenansicht für Effekte im Medien-Manager

- redaxo/src/core/lib/error_handler.php
In https://github.com/redaxo/redaxo/pull/1948 ist zu sehen dass bei uncaught exceptions dennoch ein travis build als erfolgreich gewertet wird. Dies wird hier behoben.
> Non-Zero exit-code verwenden bei unbehandelten Exceptions

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lang/es_es.lang
- redaxo/src/core/lang/sv_se.lang
Mit der technischen Meldung kann ein Nutzer im Frontend nichts anfangen. Auch ungeübte Entwickler scheitern daran, zu verstehen, was nötig ist. Mit dieser einfachen Instruktion soll die Usability verbessert werden.
> verständlichere CSRF-Meldung

- redaxo/src/core/lib/response.php
should be used e.g. for maitenance mode redirects
> response :; Adds 307 HTTP_MOVED_MOVED_TEMPORARILY

- redaxo/src/addons/structure/plugins/content/lib/minibar_element_structure_content.php
Dies verhindert entsprechende Fehler, die sonst in den folgenden Zeilen auftreten würden.
> Direkt nach dem Setup sind keine Artikel vorhanden.

- redaxo/src/core/pages/system.settings.php
closes #1900 
versions infos aus der system page entfernen da bereits in der minibar enthalten
siehe https://github.com/redaxo/redaxo/issues/1900#issuecomment-415737777
Vorher
Nachher
die 2 kisten wurden rückstandslos entfernt, da die infos in der minibar enthalten
> REX und DB Version aus system/settings entfernt

- .travis.yml
See https://changelog.travis-ci.com/linux-builds-run-on-vms-by-default-77106
> Travis: sudo: false is the new default

- .travis.yml
7.3 ist in den letzten zügen und falls probleme mit mariadb und 7.3 vorhanden sind, sollten wir sie jetzt checken
> Build mariadb with 7.3

- redaxo/src/core/lib/var/var.php
Um dem User beim lesen des generierten PHP codes zu unterstützen.
Dies zum Beispiel in whoops-stack frames
closes https://github.com/redaxo/redaxo/issues/2152
> Kommentare in generated rex-code ergänzen

- redaxo/src/core/lib/console/db/set_connection_options.php
mir scheint als wäre das ein tippfehler.. mich wundert wie der da hinkommt, da ich eigentlich das ganze getestet hatte
> make db:set_connection_options work

- redaxo/src/addons/phpmailer/boot.php
Um unnötiges fileio zu vermeiden
> phpmailer: filetime nur ermitteln wenn auch benutzt

- redaxo/src/core/lib/autoload.php
zum testen in der boot.php nach der registrierung des autoloaders und vor der registrierung des error-handlers eine exception werfen.
vor diesem patch:
es wird eine autoload.cache datei geschrieben die nur einen bruchteil aller klassen enthält.
solange diese halb-gefülle cache datei existiert laufen "einfache" http requests auf einen error seite, wenn diese den autoload cache nicht neu schreiben dürfen. dies passiert bisher z.b. im initialen setup oder wenn ein enduser das frontend besucht.
nach diesem patch:
es wird keine autoload.cache datei geschrieben. ein besuch durch einen frontend user wird eine neue autoload.cache datei erzeugen (da noch keine exisitiert). ein weiteres request im backend wird erneut versuchen den autoloader cache zu bauen.
Refs #2149
> Autoloader cache nicht schreiben, wenn ein error auftritt

- redaxo/src/core/lib/autoload.php
Zum zeitpunkt des intialen setups hat der aktuelle user noch keine admin session. daher wird im falle eines fehlers während des setups ein error dazu führen, dass man manuell den autoload.cache vom dateisystem löschen muss.
Mit diesem fix ist das im initialen setup nicht mehr nötig
hängt zum teil mit #2149 zusammen
> Regenerieren des autoload-cache während des setups erlauben

- redaxo/src/core/lib/select.php
fixes https://github.com/redaxo/redaxo/issues/2188
hier wurde das verhalten wiederhergestellt, wie zuvor in R5.6.
entgegen der argumentation in #2188 wollte ich nicht in `rex_escape` alles nach string casten, da ich der meinung bin dass int/float etc. den typ nicht ändern sollte
> Rückwärtskompatibilität in rex_select wiederhergestellt

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
mit dieser änderung wird verhindert dass extensions wie .php.txt o.ä. beim upload nicht erlaubt sind.
addons die `rex_mediapool_isAllowedMediaType()` verwenden, lehnen diese dateinamen dann auch automatisch ab.
im file-sync gibt es das problem nicht. eine my.php wird nach my.php_1 umbenannt beim sync, eine my.php.txt wird umbeannt in my.php_1.txt
closes https://github.com/redaxo/redaxo/issues/2075
> mediapool: double extension vulnerablility vermeiden

- redaxo/src/addons/structure/plugins/content/pages/content.php
Wird nicht mehr ungesetzt. Hat niemanden bisher gestört.
> Altes IE todo entfernt

- redaxo/src/addons/be_style/plugins/customizer/boot.php
Ungetestet 
Um path-traversal attacken zu unterbinden
> Customizer: Theme name auf gültige Zeichen prüfen

- redaxo/src/addons/phpmailer/lib/mailer.php
https://github.com/redaxo/redaxo/pull/2246
Bislang werden die Meldungen nur in englisch ausgegeben. Diese Änderung ermöglicht die Ausgabe der Debug-Meldungen in der jeweiligen Sprache.
> PHPMailer::Debug-Medungen in korrekter Sprache

- redaxo/src/addons/backup/lib/backup.php
Beim exportieren ist `sql->escape` der bottleneck.
https://blackfire.io/profiles/592016d2-fc28-4bd3-a34b-dced62bb7002/graph
Durch die Änderungen wird unnötiges escaping vermieden, wenn das format bekannt ist in dem gespeichert wird und dort keine zu escapenden zeichen enthalten sein können
> Backup: Export beschleunigen fuer datums-typen

- .travis.yml
da er aktuell fehlschlägt und prettyci ja auch im bugfix branch läuft
beispiel siehe https://github.com/redaxo/redaxo/pull/2263
> Codingstandards travis job entfernt

- redaxo/src/core/backend.php
informationen im browser löschen, wenn jemand versucht eine url aufzurufen, die einen backend login erfordert, aber keine gültige session existiert.
auf diesem weg löschen wir die daten auf dem rechner, damit niemand aus den ggf. gecachten inhalten was raussuchen kann (z.b. in einem inet kaffee, wenn der berechtigte admin sich nicht ordentlich abgemeldet hat - aber die session mittlerweile bereits abgelaufen ist, aber noch lokale Daten auf dem Rechner vorhanden sind)
~~Ungetestet~~
> Core: client-seitige daten löschen, wenn session abgelaufen ist

- redaxo/src/core/boot.php
In der boot-phase ist jegliches IO zuviel.
daher hier besser mit `@` operator arbeiten und dafür 2x `file_exists` einsparen.
> Core: Weniger file-operationen im bootstrap

- redaxo/src/core/lib/response.php
Bisher wurden via http-range mindestens 8 bytes ausgegeben, auch wenn weniger angefordert wurden.
> http range - chunksize

- redaxo/src/addons/structure/lib/structure_element.php
- redaxo/src/addons/structure/plugins/content/lib/article_content.php
spart file operationen ein.
auf der startseite der demo sind das 38 function calls zu file_exists().
die 24% perf verbesserung sind vermutlich eine schlechte lüge von blackfire.
Refs #2297
> Struktur: Optimistisches caches lesen

- redaxo/src/core/lib/var_dumper.php
> optische Überlagerungen in dump() vermeiden, fixed #2311

- redaxo/src/addons/structure/update.php
Das Struktur-Addon nutzt nun `rex_sql_table` in den `install.php`-Dateien.
Die werden bei einem Update aber nicht automatisch geladen, sondern das muss man selbst machen in der update.php
Die update.php gibt es nur in Addons, nicht in Plugins. Daher muss man dort auch Plugin-Updates steuern.
> Struktur: install.php in update.php einbinden

- redaxo/src/core/fragments/core/top.php
Ungetestet
Fix für https://github.com/redaxo/redaxo/issues/2325
> Asset-Bundling: Assets ausserhalb des redaxo asset-path nicht streamen

- redaxo/src/addons/phpmailer/lib/mailer.php
- redaxo/src/core/lib/login/login.php
- redaxo/src/core/lib/response.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/lib/util/file.php
- redaxo/src/core/lib/util/socket/socket.php
- redaxo/src/core/lib/util/stopwatch.php
ziel ist ein grober performance überblick. hier kann z.B. aus sysadmin-vogelperspektive gesehen werden, ob locks die performance beeinflussen, das filesystem langsam ist, oder externe operationen die meiste zeit verbrauchen.
wer in-detail schwachstellen finden will muss einen richtigen profiler verwenden.
details zur idee im verlinkten issue.
Beispiel:
closes https://github.com/redaxo/redaxo/issues/2333
> Server timing api anbinden

- redaxo/src/addons/users/pages/users.php
With MySQL 8, `admin` has become a reserved word, see https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-8-0-A
It becomes nonreserved again with MySQL 8.0.12, see https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-A
Use quoted to avoid exceptions!
> fix(users): quote `admin`, reserved in MySQL 8

- redaxo/src/core/lib/form/elements/checkbox.php
rex_escape anstelle von htmlspecialchars
fix for https://github.com/redaxo/redaxo/issues/2346, close
> rex_escape anstelle von htmlspecialchars

- redaxo/src/core/lib/be/controller.php
Analog zur Readme-Ausgabe in der Addons-Page sollten aus meiner Sicht allgemein bei Markdown-Pages Sprachvarianten unterstützt werden.
Beispiel:
```yaml
pages:
title: Mein Addon
subpages:
foo: { title: Foo }
readme: { title: Hilfe, subPath: Readme.md }
```
Wenn es eine `Readme.de.md` gibt, wird diese stattdessen genommen.
Refs #1862
> Markdown-Pages: Sprachvariante unterstützen

- redaxo/src/addons/be_style/lib/be_style.php
- redaxo/src/addons/be_style/lib/command/compile.php
Im Namespace muss bei uns immer aus `_` ein `-` werden, da unsere Api-Doc-Lib ein `_` auch als Namespace-Trenner interpretiert.
> fix phpdoc

- redaxo/src/core/lib/autoload.php
Aus meiner Sicht sollte sich der Autoloader bei aktiviertem Debug-Modus genauso verhalten, wie wenn ein Admin eingeloggt ist.
> Autoloader-Reload aktivieren bei Debug-Modus

- redaxo/src/core/lib/response.php
- redaxo/src/core/lib/util/stopwatch.php
hier mal eine max-perf-optimierte variante der rex_stopwatch.
hier kostet uns eine stopwatch nur ~3-fn calls, sollte also quasi gar nicht mehr ins gewicht fallen.
motiviert aus der diskussion in https://github.com/redaxo/redaxo/pull/2360#issuecomment-450579198
> Performanceoptimierte rex_stopwatch

- redaxo/src/core/lib/util/stopwatch.php
closes https://github.com/redaxo/redaxo/issues/2357
> Duplizierte Logik zwischen rex_timer und rex_stopwatch reduziert

- redaxo/src/core/fragments/core/top.php
- redaxo/src/core/layout/top.php
- redaxo/src/core/lib/view.php
- redaxo/src/core/tests/view_text.php
Motivation:
in tinymce müssen wir für 5.7 das immutable flag abschalten um https://github.com/redaxo/redaxo/issues/2341 zu lösen
Beispiel-Aufruf mit allen Optionen:
```php
rex_view::addJsFile(
rex_url::addonAssets('tinymce4', 'tinymce/tinymce.min.js'),
[rex_view::JS_IMMUTABLE => false, rex_view::JS_ASYNC => true, rex_view::JS_DEFERED => true]
);
```
refs https://github.com/redaxo/redaxo/issues/2269
> rex_view: async/defered optionen für javascript dateien unterstützen

- redaxo/src/core/pages/system.settings.php
Vertauscht Backendsprachenauswahl und Errormail, so dass anschließend die E-Mailbenachrichtigung bei Fehlern daran anschließen kann. 
fix für: https://github.com/redaxo/redaxo/issues/2406
Neue Darstellung:
>  Reihenfolge der Elemente im System

- redaxo/src/core/backend.php
- redaxo/src/core/layout/top.php
Weil die Minibar im Backend per default sichtbar ist, wird im <body> die Klasse `rex-minibar-is-visible` angebracht. Kurz vor der Ausgabe der Seite wird geprüft, ob die Minibar zwischenzeitlich ausgeblendet worden ist, etwa von einem AddOn oder der aktuellen Seite. In dem Fall wird die zuvor gesetzte Klasse wieder entfernt.
fixes #2400
> Minibar: Klasse für CSS im body anbringen, wenn sichtbar

- redaxo/src/addons/be_style/plugins/customizer/assets/css/styles.css
- redaxo/src/addons/be_style/plugins/customizer/assets/js/main.js
Dieser PR verbessert die Position und das Verhalten des Links zur Website:
- Schriftgröße und vertikale Ausrichtung mit anderem Text im Header (Nutzer, abmelden).
- Horizontale Ausrichtung mit Seiteninhalt.
- Auspünkteln nach 300px. Damit passt es gerade noch gut ins kleinste Desktop-Layout.
- Umstellung auf absolute Positionierung, weil etwas robuster als floats zuvor.
fixes #1091
> Customizer: Styles für Link zur Website angepasst

- redaxo/src/addons/debug/boot.php
Alle debugging extensions des addons erfordern ChromePHP und dies funktioniert nur im browser.
closes https://github.com/redaxo/redaxo/issues/2442
> Console: Fixed 'PHP Notice: Undefined index: REQUEST_URI'

- redaxo/src/addons/install/lib/api_package_add.php
- redaxo/src/addons/install/lib/api_package_download.php
- redaxo/src/addons/install/lib/api_package_update.php
```
------ ---------------------------------------------------------------------- 
Line   addons/install/lib/api_package_download.php                           
------ ---------------------------------------------------------------------- 
21     Access to undefined constant                                          
rex_api_install_package_download::GET_PACKAGES_FUNCTION.              
45     Access to undefined constant rex_api_install_package_download::VERB.  
48     Access to undefined constant rex_api_install_package_download::VERB.  
49     Access to undefined constant                                          
rex_api_install_package_download::SHOW_LINK.                          
------ ---------------------------------------------------------------------- 
```
gefunden via phpstan …
> installer warnings gefixed

- redaxo/src/core/fragments/core/top.php
Damit in entwickler dev-tools die assets dateien anhand des dateinamens besser/schneller identifiziert werden können
> Asset-Bundling im debug-mode deaktivieren

- redaxo/src/core/lib/config.php
Fixed phpstan Warnung
```
------ ------------------------------------------- 
Line core/lib/config.php                        
------ ------------------------------------------- 
303    Constant REX_CONFIG_FILE_CACHE not found.  
304    Constant REX_CONFIG_FILE_CACHE not found.  
329    Constant REX_CONFIG_FILE_CACHE not found.  
330    Constant REX_CONFIG_FILE_CACHE not found.  
350    Constant REX_CONFIG_FILE_CACHE not found.  
------ ------------------------------------------
```
Quer gesucht.. kein addon gefunden, z.b. Bei FOR dass diese konstante verwendet
> rex_config: property statt lokaler Konstante verwenden

- redaxo/src/addons/structure/lib/linkmap/var_link.php
- redaxo/src/addons/structure/lib/linkmap/var_linklist.php
Das Problem kam durch #2476 rein.
Habe zum Beispiel auf der Systempage (Linkmap für Startartikel) ein Whoops bekommen.
> Linkmap: Whoops vermeiden, wenn keine aktuelle Kategorie

- redaxo/src/addons/mediapool/assets/mediapool.js
- redaxo/src/addons/mediapool/pages/index.php
fixes #2471
Ursache war [dieser Commit](https://github.com/redaxo/redaxo/pull/2160/commits/818c27813eda24bf401b04c0cb778a9ed0d89fc7)
Empfinde den Fix als bisschen hacky. aber selectMedia() erwartet seit dem Commit ein input-Feld mit dem opener-field. Das gibt es an dieser Stelle aber (bisher) nicht.
> MP: "Hinzufügen und übernehmen" korrigiert

- redaxo/src/core/.phpstorm.meta.php
So kann PhpStorm teils sinnvolle Werte vorschlagen.
Drei Beispiele:
> .phpstorm.meta.php erweitert

- redaxo/src/addons/be_style/boot.php
- redaxo/src/core/backend.php
- redaxo/src/core/lib/view.php
- redaxo/src/core/tests/view_test.php
Es werden zunächst nur die großen Framework libs als auch die Dateien vom core als immutable ausgeliefert.
Hintergrund:
wir wollen das risiko minimieren falls der neue Mechanismus noch Probleme mitbringt.
Die jetzt immutable behandelten libraries sollten sich nur durch core-updates ändern und sind aber auch zugleich verantwortlich für den großteil des javascripts des Backends.
Closes https://github.com/redaxo/redaxo/issues/2512
> Immutable opt in

- redaxo/src/core/fragments/core/top.php
Damit nach updates von paketen geänderte css/js dateien sofort neu zum browser übertragen werden (auch wenn immutable nicht genutzt wird)
Ungetestet
> R5.6 verhalten wiederhergestellt wenn assets nicht immutable sind

- redaxo/src/addons/tests/bin/setup.php
- redaxo/src/core/lib/util/file.php
- redaxo/src/core/tests/util/log_file_test.php
Ungetestet 
Ist Ggf. Auch ein Fix bzgl https://github.com/redaxo/redaxo/issues/2140
> Atomic-Writes in rex_file::put() verwenden

- redaxo/src/addons/structure/plugins/content/boot.php
- redaxo/src/core/fragments/core/fe_ooops.php
close #1107
Screenshot
@eaCe Da ich gern die schwarze Zeile weg haben wollte, könnten wir ja erst einmal die FE Ooops nutzen. Später können wir gern es noch wie in deinen Screens farbig machen.
> Meldung "no startarticle" nutzt den FE Ooops.

- redaxo/src/addons/phpmailer/composer.json
- redaxo/src/addons/phpmailer/composer.lock
- redaxo/src/addons/tests/composer.json
- redaxo/src/addons/tests/composer.lock
- redaxo/src/core/boot.php
- redaxo/src/core/composer.json
- redaxo/src/core/composer.lock
- redaxo/src/core/update.php
> Mindestphp version anheben auf php 7.1

- redaxo/src/addons/phpmailer/boot.php
fixed: https://github.com/redaxo/redaxo/issues/2538
Zur Info: Es wurde immer die filetime des Logs gesetzt, anstelle des eigentlichen Sendezeitpunktes.
> PHPMailer::Errormail Setze aktuelle Zeit

- redaxo/src/core/backend.php
This reverts commit e281e1a1e5c19a7aa93f8c8717e73ebd53317a19.
wg. endlosschleifen die manchmal auftauchen im Firefox
(z.b. wenn man eingeloggt ist, den cookie löscht und dann in der minibar ein lazy-element triggert)
> Revert "Clear-Site-Data: "executionContexts" (#2615)"

- redaxo/src/core/frontend.php
Im setup leiten wir bereits vom frontend aufs backend um. Im backend werden diese header immer verwendet (ist bereits so).
Daher wird hier nur noch im frontend der noindex header ergänzt, wenn der debug-mode aktiv ist
Closes https://github.com/redaxo/redaxo/issues/2670
Ungetestet
> Im debug mode das frontend vor seo crawlern verstecken

- redaxo/src/core/lib/console/config/get.php
Die Ausgabe sollte mit einer Newline enden.
Oben vorher, unten nachher.
Bei mir wird bei fehlender Newline also diese "%" ausgegeben, andere Terminals würden den neuen Befehl tatsächlich auf der gleichen Zeile beginnen.
Würde ich in 5.7.1 mit reinnehmen.
> Command config:get: writeln statt write

- redaxo/src/core/backend.php
closes #2664
So könnte man zumindest vermeiden, dass der Browser versucht die .map unter der falschen URL zu laden. So wird sie gar nicht mehr geladen.
> immutable assets: sourceMappingURL entfernen

- .travis.yml
da es aktuell regelmäßig failed.
habe dem travis support geschrieben um das problem zu prüfen.
> allow-failures on php7.1 with mariadb 10.1

- redaxo/src/addons/backup/lib/backup.php
Vorher
Nachher
bitte *nicht squashen* beim merge
=> ca. 45% weniger Speicherbedarf
> Speicheroptimierung bei Backups / weniger Speicherbedarf

- redaxo/src/addons/phpmailer/lib/mailer.php
- redaxo/src/addons/phpmailer/package.yml
Es konnte zu einem Crash kommen, wenn die Laufzeit für PHP-Skripte serverseitig niedriger eingestellt ist, als im PHPMailer. 
Das Default-Timeout 300 vom PHPMailer erscheint mir viel zu hoch. 
Der PR setzt den PHPMailer Timeout auf 30
Fixes: https://github.com/redaxo/redaxo/issues/2699
> PHPMailer: Timeout auf 10 gesetzt.

- .travis.yml
wg. folgenden errors:
https://travis-ci.org/redaxo/redaxo/jobs/567468540
> travis: allow php 7.4snapshot to fail

- redaxo/src/addons/metainfo/assets/metainfo.js
fixes #2794
Das Problem bestand, seitdem dort bootstrap-select verwendet wird.
> Metainfo: datetime-Selects wieder disabled entsprechend Checkbox

- redaxo/src/core/lib/form/config_form.php
> rex_config_form: $namespace korrekt in form-hash einbeziehen

- redaxo/src/addons/be_style/lib/scss_compiler.php
Diese option gibt es im upstream compiler nicht mehr
> SCSS: strip_comments option wird nicht mehr unterstützt

- redaxo/src/addons/metainfo/boot.php
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/lib/table_manager.php
statt globaler konstanten
Hintergrund: klassen konstanten sind autoload'dable und deshalb besser für tools zu verstehen
> rex_metainfo_table_manager konstanten definieren

- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
fixes #2792
Es wird nun einheitlich das unix-timestamp-format genutzt, wie im Frontend (da kommen die Daten via `rex_article`).
> rex_article_content: Einheitliches Format für createdate/updatedate

- redaxo/src/addons/be_style/install.php
Revert #2658
Erläuterung siehe [hier](https://github.com/redaxo/redaxo/pull/2658#issuecomment-520241257).
Ich habe es nun auch getestet, und in der Tat kommt man so nicht bis zum eigentlichen Rechtecheck im Setup.
Da ich gerade nicht recht weiß, wie man es stattdessen am besten löst, erstmal von mir nur ein Revert.
Die Änderung wurde ja vor allem für das Entwickeln an der git-Version gemacht, und ich denke da ist die UX bei der ZIP-Version wichtiger.
---
Diese Meldung bekommt man sonst direkt beim Setup aufrufen, wenn die Schreibrechte noch nicht passen:
**rex_functional_exception:** Unable to copy file from "/Users/gharlan/workspace/redaxo/redaxo/src/addons/be_style/vendor/bootstrap/assets/javascripts/bootstrap.js" to "/Users/gharlan/workspace/redaxo/assets/addons/be_style/javascripts/boo …
> Revert "be_style: rex_copy() return wert während installation auswerten"

- redaxo/src/addons/structure/lib/service_category.php
Alle anderen EPs nutzen "clang", nicht "clang_id". Daher hier nun auch.
Siehe auch https://github.com/yakamara/redaxo_yrewrite/issues/265.
> EP CAT_MOVED: clang_id -> clang

- redaxo/src/addons/metainfo/lib/input/datetime.php
> ERROR: InaccessibleProperty - redaxo/src/addons/metainfo/lib/input/datetime.php:61:16 - Cannot access private property rex_input_date::$daySelect from context rex_input_datetime
4874        return $this->dateInput->daySelect;
> Metainfo inputs: datetime getters funktionieren jetzt

- redaxo/src/core/lib/login/login.php
ERROR: InvalidPropertyAssignmentValue - redaxo\src\core\lib\login\backend_login.php:89:27 - $this->user with declared type 'rex_sql' cannot be assigned type 'rex_user'
$this->user = new rex_user($this->user);
ERROR: InvalidPropertyAssignmentValue - redaxo\src\core\lib\login\backend_login.php:92:39 - $this->impersonator with declared type 'rex_sql' cannot be assigned type 'rex_user'
$this->impersonator = new rex_user($this->impersonator);
> fixed psalm warning in backend_login

- redaxo/src/core/lib/rex.php
ERROR: InvalidArgument - redaxo\src\core\lib\rex.php:381:29 - Argument 2 of exec expects array<array-key, mixed>, string() provided
@exec($command, $output, $exitCode);
ERROR: NullArgument - redaxo\src\core\lib\rex.php:381:38 - Argument 3 of exec cannot be null, null value provided to parameter with type int
@exec($command, $output, $exitCode);
> fix psalm warnings in rex::getVersionHash()

- redaxo/src/addons/media_manager/pages/effects.php
warnings siehe commit.
hintergrund: alle pfade durch diese datei haben erwartet dass $type_id definiert ist.
daher jetzt mit exception - dann klappts auch mit der statischen analyse
refs https://github.com/redaxo/redaxo/pull/2629
> fix phpstan warning bzgl. $type_id

- redaxo/src/core/pages/system.clangs.php
Refs https://github.com/redaxo/redaxo/pull/2629
Initial wird clang-id auch auf 0 gehandelt, falls nicht via REQUEST übergeben
Fixes phpstan warnings
------ ------------------------------------------ 
455  Line   core/pages/system.clangs.php              
456 ------ ------------------------------------------ 
457  44     Variable $clang_id might not be defined.  
458  49     Variable $clang_id might not be defined.  
459  50     Variable $clang_id might not be defined.  
460  76     Variable $clang_id might not be defined.  
461  77     Variable $clang_id might not be defined.  
462  143    Variable $clang_id might not be defined.  
463  145    Variable $clang_id might not be defined.  
464  159    Variable $clang_id might not be defined.  
465  194    Variable $clang_id might not be …
> Clang-id nicht unset()‘ten. Unnötiger 3. zustand

- redaxo/src/core/lib/error_handler.php
In der Release 5.8 ist der Safe-Mode über Whoops nicht mehr aktivierbar. Der Redaxo-Whoops-Header liegt im "Hintergrund".
Besteht wohl seit PR Composer Update (#2788), wo die Zeile im Upstream dazu kam.
https://github.com/redaxo/redaxo/blob/6a535df0350b8d480013bfdccee7ebd8e3764657/redaxo/src/core/vendor/filp/whoops/src/Whoops/Resources/css/whoops.base.css#L17
> Whoops: Safe-mode war nicht aktivierbar

- redaxo/src/core/boot.php
Wenn ich psalm bei mir lokal ausführe erhalte ich immer diese Warnung:
> PHP Warning:  session_cache_limiter(): Cannot change cache limiter when headers already sent in /Users/gharlan/workspace/redaxo/redaxo/src/core/boot.php on line 31
Da es in der cli eigentlich so oder so keinen Sinn hat, habe ich den Aufruf da nun ganz unterdrückt.
> In cli nicht session_cache_limiter aufrufen

- phpstan-bootstrap.php
- psalm.xml
* Explizit nur unsere Standard-Addons scannen, sonst hagelt es bei mir lokal Fehler aus den sonstigen Addons, die ich hier noch in der Installation liegen habe
* Die Functions beschränken auf .php-Dateien, denn bei mir wurde irgendeine js-datei geladen
> Psalm: Dateien besser filtern

- redaxo/src/core/pages/setup.php
replaces #2885
Gerne kann die Datei auch aufgeteilt werden. Ist aber nicht total trivial, da die Steps nicht ganz chronologisch durchlaufen werden, und die Steps unter bestimmten Bedingungen wieder zurückgesetzt werden.
Daher von mir erstmal nur die early-returns.
> Setup: Early-Returns verwenden

- redaxo/src/addons/be_style/plugins/redaxo/boot.php
Seit #2813 wurde die Variable `$plugin` überschrieben, und deswegen stimmten die Pfade zu den Favicons nicht mehr.
> Favicon-Urls korrigiert

- psalm-utils.php
- psalm.xml
- redaxo/src/core/lib/util/type.php
Noch Ungetestet.
Hoffnung ist, dass wir damit psalm mitteilen können welche typen variablen zur laufzeit haben
https://psalm.dev/docs/annotating_code/assertion_syntax/
~~Inspiriert von https://github.com/webmozart/assert/pull/102~~
> psalm typeinfos für rex_type::cast()

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
> rex_sql_table::alter(): Originaltabellenname in Fehlermeldung, wenn Tabelle noch nicht existiert

- redaxo/src/addons/backup/boot.php
Should fix
> INFO: ArgumentTypeCoercion - redaxo/src/addons/backup/boot.php:4:39 - Argument 1 of rex_cronjob_manager::registertype expects class-string<rex_cronjob>, parent type string(rex_cronjob_export) provided
377    rex_cronjob_manager::registerType('rex_cronjob_export');
Todo
> Use class-string instead of a plain string

- redaxo/src/addons/cronjob/lib/form.php
```
INFO: PropertyNotSetInConstructor - redaxo/src/addons/cronjob/lib/form.php:18:13 - Property rex_cronjob_form::$intervalField is not defined in constructor of rex_cronjob_form and in any methods called in the constructor
private $intervalField;
```
> fix psalm warning

- redaxo/src/core/lib/form/elements/prio.php
Behebt folgenden Fehler:
Ich habe ein eigenes AddOn mit einer rex_form-Eingabe und verwende damit ein "prio"-Feld.
Das funktioniert auch wunderbar, allerdings mit einer Einschränkung:
Wenn ich einen Datensatz komplett lösche, dann wird das prio-Feld nicht neu ausgewertet. Lösche ich also bei 3 Datensätzen den mit der prio = 1, dann beginnt meine rex_list-Ausgabe mit den übrig gebliebenen 2 Datensätzen bei prio = 2...
> Prio auch nach Löschen eines Datensatz neu organisieren

- redaxo/src/addons/cronjob/plugins/optimize_tables/lib/cronjob.php
closes #2982
(die Meldung kommt im Fehlerfall, der Fehlerfall ist aber auch durch das escaping korrigiert.)
> cronjob/optimize_tables: fix escaping, add message

- .github/workflows/csfix.yml
```
- Your workflow file was invalid: The pipeline is not valid. .github/workflows/csfix.yml (Line: 27, Col: 11): Unexpected symbol: '$keyword_found'. Located at position 43 within expression: steps.vars.outputs.pr_branch != 'null' && $keyword_found
```
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions
> try to fix "Unexpected symbol: '$keyword_found'" error

- .github/workflows/push.yml
- .travis.yml
dieser build darf failen, da er es auch unter travis CI bereits gemacht hat
ich habe ihn nur umgestellt um eine ungefähre gleichverteilung an jobs zwischen GithubActions und TravisCI zu erreichen.. d.h. ich werde jetzt erstmal keine weiteren Jobs umstellen.
> use GithubActions for phpstan-analysis

- .travis.yml
Es scheint wohl Probleme mit `mariadb:10.1` auf `bionic` zu geben, weil die Abhängigkeiten scheinbar nicht korrekt aufgelöst werden.
(siehe https://mariadb.com/kb/en/library/unable-to-install-mariadb-101-on-ubuntu-1804-after-apt-remove-purge-mysql/)
wird vermutlich auch das Problem aus https://github.com/redaxo/redaxo/pull/3011#issuecomment-557489228 sein.
> Fix travis mariadb error

- redaxo/src/core/default.config.yml
- redaxo/src/core/lib/util/editor.php
fügt eine neue `config.yml` property `editor_basepath` hinzu. Damit kann der Dateipfad zum Öffnen einer Datei im Editor gemappt/umgeschrieben werden.
closes #2625
> Added editor_basepath property

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/pages/setup.php
fixes #2767 
Bei einem Aufruf über http werden die Felder deaktiviert und eine Warnung/Hinweis ausgegeben.
vorher:
nachher:
> setup: only allow https settings via https call

- redaxo/src/core/lib/response.php
should fix
```
ERROR: InvalidReturnType - redaxo/src/core/lib/login/api_user_impersonate.php:10:21 - The declared return type 'rex_api_result' for rex_api_user_impersonate::execute is incorrect, got 'void'
public function execute()
```
see https://github.com/vimeo/psalm/issues/2213
> psalm: mark never returning methods

- .github/FUNDING.yml
Bei GitHub Sponsor erscheint eine Fehlermeldung, wenn nicht registrierte Benutzer hinterlegt sind.
> Sponsor: remove non-registered users

- .github/workflows/push.yml
Maximize stability in ci builds.
Make sure our build does not depend on external package releases
> Use fixed phpstan version

- .github/workflows/push.yml
> ##[warning]Input 'extension-csv' has been deprecated with message: The extension-csv property will not be supported after February 1, 2020. Use extensions instead.
> Gh-action: get rid of deprecated configs

- redaxo/src/core/lib/be/controller.php
es kann durchaus legitim sein, keine rechte auf das php error log zu haben.
daher warning unterdrücken und weiter.
closes https://github.com/redaxo/redaxo/issues/3052
> prevent warnings when the error log is not readable by the apache user

- redaxo/src/addons/be_style/lib/command/compile.php
- redaxo/src/addons/cronjob/lib/command/run.php
- redaxo/src/core/lib/console/db/connection_options.php
- redaxo/src/core/lib/console/db/dump_schema.php
- redaxo/src/core/lib/console/system/report.php
- redaxo/src/core/lib/console/user/create.php
- redaxo/src/core/lib/console/user/set_password.php
Seit SF 4.4 ist es deprecated, keinen Exit code zu returnen.
In SF 5 würde es dann zu einem Fehler führen.
> Exit code immer explizit angeben

- redaxo/src/core/lib/var/var.php
- redaxo/src/core/tests/var/var_test.php
closes #676
Konnte mich nicht entscheiden, ob der Varname oder der Klassenname sinnvoller ist, daher habe ich beide übergeben.
Oder lieber nur eins von beiden?
> REX_VARs: Var-Name an Callback übergeben

- redaxo/src/addons/install/lib/api_package_upload.php
Es nervt mich immer, wenn man eine neue Version hochlädt, dass man dann auf der Addonliste landet, statt in den Addon-Details, wo man die hochgeladene Version dann nochmal sieht.
> Installer: Nach Addon-Version hochladen, auf Addon-Details landen

- redaxo/src/addons/mediapool/lib/media.php
- redaxo/src/addons/mediapool/lib/media_category.php
- redaxo/src/addons/structure/lib/structure_element.php
Aktuell wurde bei `$cat->getChildren()` die Cache-Datei immer wieder neu generiert, wenn die Kategorie keine Kinder hat. Somit traten auch unnötige Datenbankabfragen auf.
Das war die Ursache für die langsamen `rex_category_select`, somit: fixes #2128
> Leeres Array aus Cache akzeptieren

- redaxo/src/core/assets/standard.js
Erläutert, dass dieses Cookie im Zuge des Setups von REDAXO erzeugt wird. closes #3042
> Präfix "rex_htaccess_check" als Indikator für Quelle

- .github/workflows/push.yml
- README.md
Quote https://psalm.dev/articles/php-or-type-safety-pick-any-two
Tracking type coverage in public projects
Many public GitHub projects (Psalm included) display a small badge showing how much of the project’s code is covered by PHPUnit tests, because test coverage is a useful metric when trying to get an idea of a project’s code quality.
Hopefully, if you’ve got this far, you think type coverage is also important. To that end, I’ve created a service that allows you to display your project’s type coverage anywhere you want.
Psalm, PHPUnit and many other projects now display a type coverage badge in their READMEs.
You can generate your own by adding --shepherd to your CI Psalm command. Your badge will then be available at
https://shepherd.dev/github/{username}/{repo}/coverage.svg
This …
> psalm: activate shepherd.dev mode to collect type coverage

- redaxo/src/core/lib/console/application.php
Eine Whitelist, die `db:set-connection` ohne das Laden von packages ausführt.
closes #3102
> Console: disable package loading for db:set-connection

- .github/workflows/csfix.yml
Auto-commit Doesnt work with checkout v2  right now, see https://github.com/stefanzweifel/git-auto-commit-action/pull/33
> Auto-cs-fixer: Going back to actions/checkout@v1

- redaxo/src/core/lib/config.php
Wenn man in rex_config Werte löscht und danach die keys erneut setzt kann es beim Speichern in der Datenbank zu einem SQL-Error kommen.
Long Story short....
In meinem Case passiert folgendes:
`rex_config::removeNamespace('media_manager')`
`rex_config::set('media_manager', 'jpg_quality', 85)`
`rex_config::set('media_manager', 'png_compression', 5)`
`rex_config::set('media_manager', 'webp_quality', 85)`
erst wird durchs entfernen vom Config-Namespace
```php
$deleteData = [
'media_manager' => ['interlace', 'png_compression', 'webp_quality']
]
```
durch das neu setzen mit `rex_config::set` verschwinden die Keys wieder daraus und es bleibt
```php
$deleteData = [
'media_manager' => []
]
```
beim Speichern/Sync mit der DB wird an folgender Stelle das SQL-Statement mit leeren Klammern erzeugt …
> rex_config: error beim speichern in db

- redaxo/src/addons/install/lib/api_package_add.php
- redaxo/src/core/pages/packages.php
Aber nur wenn man in der Erfolgsmeldung über den Link "Zur Addonverwaltung" geht.
closes #2216
> Addon nach Download markieren

- redaxo/src/core/lib/api_function.php
Ich bin mir nicht ganz sicher, aber hätte jetzt gesagt, dass die statische Methode `rex_api_function::hasMessage()` immer aufrufbar sein sollte, auch wenn es gar keine aktuelle Api-Func gibt.
Oder was meint ihr?
Aktuell kommt es da zur Exception.
> rex_api_function::hasMessage() immer aufrufbar machen

- redaxo/src/addons/install/pages/packages.add.php
- redaxo/src/addons/install/pages/packages.update.php
- redaxo/src/addons/install/pages/packages.upload.php
Aktuell ist es so, wenn man in der Liste ein Addon weit unten anklickt, dann landet man in den Details auch entsprechend unten.
Da sollte aber immer nach oben gescrollt werden.
> Installer: Bei Aufruf Details nach oben scrollen

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lang/es_es.lang
- redaxo/src/core/lang/it_it.lang
- redaxo/src/core/lang/nl_nl.lang
- redaxo/src/core/lang/pt_br.lang
- redaxo/src/core/lang/sv_se.lang
- redaxo/src/core/tests/util/formatter_test.php
Im Englischen hatten wir aktuell zum Beispiel ein komisches Format: 2020-Jan-15.
Habe es auf dieser Basis angepasst: https://3v4l.org/OGXnn
- In deutsch aber trotzdem weiterhin "15. Jan. 2020", auch wenn der Intl-Formatter für MEDIUM im deutschen das reine Zahlenformat angibt
- In Portugiesisch hingegen habe ich das Zahlenformat, da das andere so extrem lang ist
> Datumsformat vereinheitlicht für Sprachen

- redaxo/src/addons/install/lang/de_de.lang
- redaxo/src/addons/install/lang/en_gb.lang
- redaxo/src/addons/install/lang/es_es.lang
- redaxo/src/addons/install/lang/pt_br.lang
- redaxo/src/addons/install/lang/sv_se.lang
- redaxo/src/addons/install/lib/api_core_update.php
- redaxo/src/addons/install/lib/api_package_update.php
closes #2633
**Vorher**
**Nachher**
Ich hoffe, es macht die Meldungen zumindest etwas verständlicher.
> Installer-Messages verbessert

- .travis.yml
Seit https://github.com/redaxo/redaxo/pull/3016 nutzen wir für fast alle Builds wieder trusty.
(Wir nutzen da YAML-Referenzen, deswegen wir es in die anderen Builds vererbt.
Ich teste jetzt hier auch allgemein nochmal durch, bei welchen builds es noch notwendig ist, was anderes als bionic zu nutzen (ggf. hat sich ja was verändert).
> travis: php 8 testen; bionic nutzen, wo möglich

- redaxo/src/core/lib/util/log_file.php
- redaxo/src/core/tests/util/log_entry_test.php
Durch meinen anderen PR kam hier ein Problem rein, wenn das letzte Log-Daten-Element leer ist.
> rex_log_file: Notice vermeiden

- .dependabot/config.yml
nur noch über security fixes "informieren".
Anpassung anhand config reference https://dependabot.com/docs/config-file/#allowed_updates
refs #3165  
refs #3166
> dependabot: only security fixes

- redaxo/src/addons/users/pages/roles.php
Bei den Mehrfachselects für die Perms ist es nervig, wenn sie scrollen.
Mit den neuen Strukturrechten wird man leicht über 10 kommen.
Finde es angenehmer, wenn die Selects dann auch entsprechend größer sind, deswegen nun 20 als max. Size.
> Perm-Selects: Max-Zeilen von 10 auf 20

- redaxo/src/addons/backup/vendor/tar.php
fixes #3183
Also `octdec` meckert über invalide Zeichen. Daher habe ich geschaut, was für Zeichen enthalten sind, und gesehen, dass die meisten der dort ausgelesenen Strings als letztes ein "\x00" haben.
Vermutlich ein Trenner im Tar zwischen den verschiedenen Werten.
Theoretisch könnte ich also jeweils ein Byte weniger auslesen. Da ich mich mit tar aber nicht auskenne und mir das nicht ganz geheuer war, habe ich lieber mit rtrim gearbeitet.
Bin mir nicht wirklich sicher, aber vermute, dass es so passt. Bei mir kommen die Meldungen jedenfalls nicht mehr und die tars werden scheinbar korrekt entpackt.
> tar: deprecated-message vermeiden

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
> Medienpool: php 7.4 notice bei upload vermeiden

- redaxo/src/addons/mediapool/install.php
- redaxo/src/addons/mediapool/uninstall.php
Seit 5.9 binden wir in der update.php die install.php ein.
So wird es zum Problem während des Core-Updates, dass hier der Cache gelöscht wird, da im Cache-Ordner benötigte Dateien für das Core-Update liegen.
Das Cache-Löschen hat Jan hier eingeführt: https://github.com/redaxo/redaxo/commit/82eeb6c8ae4b81714581c46f7368c80fd62d2038#diff-91420c7e4017130d603003ff56855cabR20
Ohne genau zu verstehen, warum das damals nötig war, denke ich nicht, dass es jetzt noch notwendig ist.
> MP: Cache nicht löschen in install.php

- redaxo/src/core/install.php
- redaxo/src/core/update.php
Da wir inzwischen dort auch rex_sql_table verwenden.
Außerdem war mir aufgefallen, dass ein Setup mit Aktualisierung der DB auf utf8mb4, die Core-Tabellen gar nicht umgestellt wurden, nur die Addons.
> Core-Update: install.php einbinden

- redaxo/src/addons/tests/bin/setup.php
closes #3227 
Problem sind nicht die tests selbst, sondern das setup (aus `tests/bin/setup.php`)
"Kurze" Workflow Erklärung:
erst wird im Setup eine mini config.yml erzeugt und in data abgelegt
https://github.com/redaxo/redaxo/blob/9ade306e8a7cdce0605a11ffebf6cb4f62737af1/redaxo/src/addons/tests/bin/setup.php#L27
dann wird die boot.php eingebunden, die schließlich die config.yml.cache anlegt (gemergt mit der default ist `setup:true`)
https://github.com/redaxo/redaxo/blob/9ade306e8a7cdce0605a11ffebf6cb4f62737af1/redaxo/src/addons/tests/bin/setup.php#L30
dann zum Ende speichert der `setup:false` mit in die config.yml in data.
https://github.com/redaxo/redaxo/blob/9ade306e8a7cdce0605a11ffebf6cb4f62737af1/redaxo/src/addons/tests/bin/setup.php#L70-L71
Status nach Setup:
data/core/config.yml => …
> fix flickering tests

- redaxo/src/addons/phpmailer/pages/system.log.phpmailer.php
$addon = rex_addon::get('phpmailer'); Wird nicht benötigt
> Phpmailer: log : Zeile entfernt

- redaxo/src/core/lib/setup/import.php
closes #3234
Focuspoint sollte seine Abhängigkeit trotzdem unbedingt notieren.
Aber das enlist hier ist trotzdem sinnvoll, gerade für optionale Abhängigkeiten mit class_exists, dass dann in den install.php auch alle Klassen bereits bekannt sind
> Setup: Vor Reinstallation der Addons, diese listen

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
Wenn man zu einer Tabelle einen PK hinzufügen wollte, die vorher noch keinen hatte, dann kam es zu einem Fehler, weil fälschlich `DROP PRIMARY KEY` ausgeführt wurde.
> rex_sql_table: Fix für PK zu existierender Tabelle hinzufügen

- redaxo/src/addons/backup/CHANGELOG.md
- redaxo/src/addons/backup/lib/backup.php
- redaxo/src/addons/backup/package.yml
Das Backup-Addon exportiert aktuell `NULL`-Values falsch, für Varchars als `''`, für integers als `0`, etc.
Das muss schon Ewigkeiten so sein, aber scheinbar hat es bisher nirgends zu einem Problem geführt.
In 5.9 haben die Templates aber die nullable `key`-Spalte mit Unique-Index. Es kann also mehrere Zeilen mit key=null geben.
Beim Export wird es zu `''`.
Beim Import gibt es dann einen Fehler, da es bei nullable unique nur mehrere NULL-Values geben kann, aber eben nicht mehrere leere Strings.
> Backup: Null-Values als solche exportieren

- redaxo/src/addons/be_style/plugins/customizer/package.yml
declare zip dependency because we use ZipArchive in https://github.com/redaxo/redaxo/blob/57609dff9493a33c2d598ff5f84284e77968a9df/redaxo/src/addons/be_style/plugins/customizer/install.php#L18
triggered in slack
does not resolve the initial reported problem, but should solve installing the plugin on systems without zip extension and print a proper warning.
> be_style/customizer: declare zip dependency

- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/lib/table_manager.php
- redaxo/src/addons/metainfo/package.yml
Wenn man Metainfos über die GUI anlegt, bekommen TEXT-Spalten keinen Default-Wert.
Bei Nutzung von `rex_metainfo_add_field`, was auch verwendet wird bei "Standardfelder erstellen", wird hingegen versucht einen leeren String als Default zu setzen.
Dieser PR vereinheitlicht das Verhalten, indem der Ausschluss an eine zentralere Stelle wandert.
Aufgefallen ist es bei Nutzung von YDeploy und Mischung von MariaDB und MySQL.
Denn MariaDB unterstützt Default-Values bei TEXT-Spalten, MySQL hingegen nicht.
> Metainfo: TEXT-Spalten ohne Defaults

- redaxo/src/core/boot.php
- redaxo/src/core/lib/packages/manager.php
Bei tiefer verschachtelten Abhängigkeiten konnte es dazu kommen, dass nicht alle Packages tiefer im Baum untereinander noch die richtige Reihenfolge erhalten haben.
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1581015964136000?thread_ts=1580991000.108600&cid=C1BAXLN2F
> Package-Ladereihenfolge korrigiert

- redaxo/src/core/lib/sql/sql.php
Man kann die Params im Array entweder mit dem Punkt vorne dran, oder auch ohne übergeben.
`:key` vs. `key`
Unsere fullquery in der Debugausgabe hat sie aber nur ersetzt, wenn sie ohne Doppelpunkt übergeben wurden.
> SQL-Debugausgabe: Parameter in fullquery richtig ersetzen

- redaxo/src/core/lib/sql/table.php
rex_sql_table setzt beim Erstellen von Tabellen nur `CHARSET=utf8(mb4)`, und belässt die Collation bei der zugehörigen Default.
Beim Wechsel des Charsets (über das Setup) setzt rex_sql_table hingegen explizit die Collation `utf8(mb4)_unicode_ci`.
Diese ist auch vor `_general_ci` vorzuziehen (bessere Vergleiche/Sortierungen für verschiedene Sprachen).
Aufgefallen ist es mir beim lokalen Ausführen der Unittests. Da Testen wir auch Foreign Keys auf varchars. Und ich hatte da nun einen Mischmasch von _unicode_ci und _general_ci, weswegen die Tests fehlschlugen.
Daher wird nun auch beim Erstellen von Tabellen explizit _unicode_ci verwenden.
> Einheitliche Collation _unicode_ci verwenden

- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/mediapool/pages/media.detail.php
- redaxo/src/addons/mediapool/pages/upload.php
- redaxo/src/core/lib/setup/setup.php
- redaxo/src/core/lib/util/file.php
- redaxo/src/core/tests/util/file_test.php
`mime_content_type` liefert für SVGs, die keinen `<?xml`-Tag enthalten, den Typ `image/svg`.
Der ist aber unüblich und wird von Browsers nicht korrekt behandelt.
Um es allgemein zu lösen, gibt es nun eine neue Methode `rex_file::mimeType`, die an allen Stellen verwendet wird.
Diese enthält auch die Sonderbehandlung für CSS und JS, die wir an einer Stelle im MM hatten.
Es ist zwar in gewisser Weise auch ein neues Feature, da aber die Intention eher ist, Bugs zu beseitigen, würde ich es so in bugfix mergen.
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1582125071115100
https://github.com/yakamara/redaxo_yrewrite/issues/332
> Neue Methode rex_file::mimeType(), um svg-Problem zu lösen

- .github/workflows/csfix.yml
- .github/workflows/push.yml
- .gitignore
- composer.json
- phpstan.neon.dist
- psalm.xml
Ich schlage vor, im Root eine composer.json anzulegen für die Tools, die wir verwenden.
So kann man sie leicht lokal ausführen, mit der selben Version, wie wir sie bei den Actions nutzen.
> composer.json im Root für Tools

- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
#2785 Svgs werden nun auch im convert2img beachtet und verarbeitet
wir sind mittlerweile der meinung dass der convert2img filter impliziert dass man eine pixelgrafik haben will um z.B. anschließend weitere pixel-bild-effekte darauf anzuwenden.
svgs können dabei qualität verlieren aber dafür kann man eben auch image effekte anwenden.
wer svgs nicht darüber handeln will muss dieser vorm aufruf der mediamanager urls explizit abfragen, siehe zum Beispiel https://github.com/redaxo/redaxo/blob/621f24af5869198224d2b1c6c13a36316a7faedf/redaxo/src/addons/mediapool/pages/media.list.php#L303-L305
> svg auch convert2img verarbeiten

- redaxo/src/addons/backup/lib/backup.php
closes #3180 
Sortierung der Datei-Backups nicht mehr anhand des Timestamps, sondern anhand des Dateinamens.
> Backup: archive anhand des dateinamens sortieren

- redaxo/src/core/lib/console/setup/run.php
die eol warnings aus dem backend setup werden jetzt auch in dem console setup angezeigt
refs #3317
> console: setup eol warnings

- redaxo/src/core/pages/setup.php
- redaxo/src/core/pages/setup.step1.php
- redaxo/src/core/pages/setup.step2.php
- redaxo/src/core/pages/setup.step3.php
- redaxo/src/core/pages/setup.step4.php
- redaxo/src/core/pages/setup.step5.php
- redaxo/src/core/pages/setup.step6.php
- redaxo/src/core/pages/setup.step7.php
die große lange setup page in einzelne teilseiten aufgeteilt.
ich habe dabei nur die einzelnen logiken extrahiert die die pages rendern (damit die steuerungslogik klarer wird wg. early returns etc. in der pages/setup.php
die eigentlichen validierungslogiken hab ich bewusst in der pages/setup.php belassen damit nicht auch noch die logik verändert werden müssen. so wird bereits genug code bewegt
> split setup steps into separate files

- redaxo/src/addons/structure/lib/service_article.php
- redaxo/src/addons/structure/lib/service_category.php
- redaxo/src/addons/structure/plugins/content/lib/content_service.php
dieser code war nötig für BC zu alten REX versionen.. mitlerweile sind die min redaxo versionen aber aktuell genug
`rex::getEnvironment()` gibts seit R5.4
> removed unnecessary bc code

- redaxo/src/addons/structure/pages/index.php
- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lib/setup/setup.php
- redaxo/src/core/pages/setup.php
- redaxo/src/core/pages/setup.step4.php
closes https://github.com/redaxo/redaxo/issues/2712
Das passwort Eingabefeld wird nicht mehr vorgefüllt.
Wenn man ein neues Passwort eingibt wird dieses benutzt, ansonsten bleibt das "vorherige" bestehen.
> hide password in setup

- redaxo/src/core/lib/console/setup/run.php
- redaxo/src/core/lib/setup/setup.php
- redaxo/src/core/pages/setup.step3.php
- redaxo/src/core/pages/setup.step5.php
`rex_setup` ohne rendering, stattdessn nur die logik
> remove html markup from checkPhpSecurity() & checkDbSecurity()

- redaxo/src/addons/media_manager/pages/settings.php
- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
- redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
- redaxo/src/addons/structure/plugins/content/pages/templates.php
- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lib/form/form.php
Generischen Tooltip hinzufügen, den wir auf allen "übernehmen"/"speichern" knöpfen nutzen können.
Button labels selbst wurden nicht angepasst, da wir uns nicht auf labels einigen konnten die besser sind als die bisherigen
closes https://github.com/redaxo/redaxo/issues/772
> add save/apply button titles

- redaxo/src/addons/install/lib/api/api_core_update.php
- redaxo/src/addons/install/lib/package/package_update.php
- redaxo/src/addons/media_manager/install.php
- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/media_manager/pages/settings.php
- redaxo/src/addons/phpmailer/install.php
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/packages/package.php
Idee ist, dass man bei der Installation nicht jeden Config-Wert prüfen muss, und ggf. initialisieren, sondern, dass man einfach in der package.yml die Default hinterlegen kann.
Diese Default-Werte werden gar nicht in der DB gespeichert. Wobei mir in dem Moment, wo ich es gerade schreibe, auffällt, dass das vielleicht doch nicht so eine gute Idee ist.
So lassen sie Default-Werte schwieriger ändern.
Also sollte ich die ggf. doch besser bei Installation auch in die DB schreiben.
Edit: Erledigt!
Aber erst mal grundsätzlich: Wollen wir überhaupt sowas?
> Default-Config in package.yml ermöglichen

- redaxo/src/addons/install/lib/command/download.php
- redaxo/src/addons/install/package.yml
und da isser der `install:download` command um AddOns aus dem Installer via console zu **downloaden**.
`redaxo/bin/console install:download <addonkey> <version>`.
Version ist optional, wenn keine angegeben wird, werden alle verfügbaren Versionen aufgelistet und man per choice() eins auswählen.
> console: added install:download

- redaxo/src/addons/install/lib/api/api_core_update.php
fixes #3291
Bei @alexplusde hatte das so scheinbar geholfen, auch wenn ich immer noch nicht wirklich kapiere, weshalb.
> Core-Update: Doppel-rename statt löschen+rename

- redaxo/src/addons/install/lib/api/api_core_update.php
- redaxo/src/addons/install/lib/api/api_package_upload.php
- redaxo/src/addons/install/lib/archive.php
- redaxo/src/addons/install/lib/package/package_download.php
fixes #2286
Zumindest bei Alex trat der Fehler aus dem Issue genau dann auf, wenn der Tempordner noch aus einem früheren Versuch existierte.
Das sollte nun nicht mehr passieren.
> Installer: Temp-Dateien besser löschen, Abbruch bei Entpack-Fehler

- redaxo/src/addons/install/lib/command/download.php
im `install:download` wird noch eine html-formatierte Fehlermeldung ausgegeben.
refs #3353
> console: install:download - decode html

- redaxo/src/addons/install/lib/command/update.php
- redaxo/src/addons/install/package.yml
_die command maschine hat wieder zugeschlagen._
command `install:update` updated ein AddOn mit Updates von redaxo.org.
`redaxo/bin/console install:update <addonkey> <version>`:
- addonkey: z.B. "yform"
- version: z.B. "1.2.3"
Die Versionsangabe ist optional, wenn keine angegeben ist, werden mögliche Versionen zur Auswahl gestellt (gleich wie im Backend auch sind).
refs #2080
> Installer: command install:update

- redaxo/src/addons/phpmailer/package.yml
auf manuelle Auswahl. DF User scheinen mit Auto ein Problem zu haben, daher schlage ich als Default-Setting jetzt manuell vor. 
closes: https://github.com/redaxo/redaxo/issues/3006
Bestehende Settings werden nicht verändert
> PHPMailer:: setzen der default Verschlüsselung

- redaxo/src/addons/mediapool/pages/media.detail.php
- redaxo/src/addons/mediapool/pages/media.list.php
Der MP benötigt inzwischen R5.10, somit brauchen wir den Fallback für alte MM-Versionen nicht mehr.
> MP: Fallback für alte MM-Versionen entfernt

- redaxo/src/addons/tests/bin/setup.php
ist mir grad mal aufgefallen, da ich in letzter Zeit mal die tests lokal habe laufen lassen, dass eine `redaxo/data/config.yml` angelegt wurde mit dem Inhalt `error_email: info@redaxo.org`.
schätze die kann also weg
> tests: remove unnecessary file creation

- redaxo/src/core/composer.json
- redaxo/src/core/composer.lock
- redaxo/src/core/lib/util/string.php
- redaxo/src/core/vendor/composer/installed.json
Da wir das polyfill-intl-normalizer-Paket inzwischen sowieso drin haben, habe ich es als explizite Abhängigkeit reingesetzt, und daher die Fallback-Variante entfernt
> Normalizer direkt nutzen

- redaxo/src/core/functions/function_rex_other.php
Schlage vor, dass wenn man den Cache löscht, auch der Opcache geleert wird.
Komme von: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1583144983472800
> Cache löschen: auch Opcache leeren

- redaxo/src/core/boot.php
- redaxo/src/core/lib/error_handler.php
Ich glaube, dass das nicht 100% korrekt ist, aber es ist aus meiner Sicht schwierig hier 100% korrekt zu sein.
Und ich denke, dass das meist die korrekten Ergebnisse liefert.
Vorher:
Nachher
> disable `html_errors`

- redaxo/src/addons/structure/plugins/content/pages/content.edit.php
Beim Speichern eines Slices, erscheint seit 5.9 nicht mehr die Erfolgsmeldung im Block.
Ausgelöst durch https://github.com/redaxo/redaxo/commit/a82804e57ecdfe4f996041fe05c68f07e159a4fc#diff-817fc14243239fae826c8273436ff958
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1583258965133600
> Slice-Message nicht verwerfen

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/install.php
fixes #3412
* Die `filename`-Spalte hat nun einen Unique-Index (somit gleichzeitig ein kleiner Schritt für #2786 @alexplusde)
* Bei der suche nach einem freien Dateinamen wird nicht mehr nur nach den physischen Dateien geschaut, sondern auch nach den Datensätzen aus rex_media
> Mediapool: filename unique + bessere Dateinamensgenerierung

- redaxo/src/addons/cronjob/pages/cronjobs.php
Der slideDown/Up-Effekt erscheint nun nur noch, wenn man den Typ wechselt, initial sind sie sofort da.
> Cronjob: Typspezifische Parameter initial sofort erscheinen lassen

- redaxo/src/addons/backup/lib/cronjob.php
Das Mailadress-Feld klappt erst auf, wenn man "Per Mail versenden" aktiviert. 
War bisschen komisch mit dem Feld dazwischen.
Deswegen ist "Per Mail versenden" nun eins weiter runter gerutscht.
> Backup-Cronjob: Bessere Feldreihenfolge

- redaxo/src/addons/structure/plugins/content/lib/api_module.php
- redaxo/src/addons/structure/plugins/content/lib/api_template.php
Wenn man REX_MODULE_KEY verwendet und es keiner gesetzt wurde, dann kommt aus der Datenbank `null` zurück und da der typehint einen string erwartet kracht es hier.
Dirk hat das gleiche Problem bei `REX_TEMPLATE_KEY` gemeldet, ich kann es aber nicht reproduzieren. Für mich müsste eigentlich wenn an beiden Stellen fliegen, da die ziemlich identisch sind...
**TypeError:** Return value of rex_module::getKey() must be of the type string, null returned
**File:** redaxo/src/addons/structure/plugins/content/lib/api_module.php
**Line:** 55
<details>
<summary>Stacktrace</summary>
| Function                                     | File                                                                       | Line     |
| -------------------------------------------- | …
> fix rex_module::getKey()

- redaxo/src/core/lib/console/application.php
refs #3287 
ich weiß net warum das doch so drin gelandet ist.... Bin mir sicher wir hatten das in Hannover anders besprochen ; bin bestimmt einfach wieder verpeilt gewesen oder habe gefroren, wer weiß :stuck_out_tongue_winking_eye: 
aktuell sorgt der check dafür, dass ein hard exit gemacht wird, wenn der console user nicht der owner der files ist.
> console: wrong user - no hard exit

- redaxo/src/core/composer.json
- redaxo/src/core/composer.lock
- redaxo/src/core/lib/util/string.php
- redaxo/src/core/tests/util/markdown_test.php
- redaxo/src/core/tests/util/string_test.php
- redaxo/src/core/vendor/composer/installed.json
- redaxo/src/core/vendor/voku/anti-xss/CHANGELOG.md
- redaxo/src/core/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php
- redaxo/src/core/vendor/voku/portable-ascii/CHANGELOG.md
- redaxo/src/core/vendor/voku/portable-ascii/src/voku/helper/ASCII.php
- redaxo/src/core/vendor/voku/portable-utf8/CHANGELOG.md
- redaxo/src/core/vendor/voku/portable-utf8/src/voku/helper/UTF8.php
Das Problem, auf welches ich in https://github.com/redaxo/redaxo/pull/3428 gestoßen bin, wurde gefixt:
https://github.com/voku/anti-xss/issues/55
Außerdem konnte man aktuell im Markdown auch in Code-Blöcken keine script-Tags notieren.
Das ist nun möglich:
https://github.com/voku/anti-xss/issues/56
> Update AntiXSS und escapte script-tags erlauben

- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
In https://github.com/redaxo/redaxo/pull/571 wurde die Reihenfolge eigentlich schon mal getauscht, seitdem werden `REX_ARTICLE_ID` etc. vor den eigentlichen REX_VARs wie `REX_VALUE[x]` ersetzt.
Dabei wurden aber nicht die zusätzlichen einfachen Vars der Slices mit nach oben verschoben.
Das hole ich nun nach.
Einserseits will man die innerhalb der echten Vars nutzen können: `REX_CONFIG["REX_MODULE_ID.foo"]`
Andererseits sollen sie gerade nicht im Inhalt der Values ersetzt werden. Aktuell wird ja erst `REX_VALUE[]` ersetzt, und dann `REX_MODULE_ID` etc. Wenn der Redakteur also in einem Block `REX_MODULE_ID` verwendet, wird es auch ersetzt.
Wenn er den Block dann wieder öffnet, sogar auch im Textfeld, es erscheint also nicht mehr der eingegebene Text.
> Module: Einfache Var-Ersetzungen vor den richtigen REX_VARs

- redaxo/src/core/lib/console/package/activate.php
- redaxo/src/core/lib/console/package/deactivate.php
- redaxo/src/core/lib/console/package/delete.php
- redaxo/src/core/lib/console/package/install.php
- redaxo/src/core/lib/console/package/uninstall.php
- redaxo/src/core/pages/packages.php
wenn man ein AddOn in den `src/addons/` ordner legt, kennen die `package:` commands dieses nicht, da dies noch nicht, wie auf Addon-Page passiert, gesynct ist.
> console: sync packages with filesystem

- redaxo/src/core/boot.php
- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
```php
rex_sql_table::get($table)
->ensurePrimaryIdColumn()
->ensureColumn(new rex_sql_column('title', 'varchar(255)'))
->ensureGlobalColumns()
->ensureColumn(new rex_sql_column('revision', 'tinyint(1)'))
->ensure();
```
Bei diesem Code wechselt bei jeder Ausführung die `revision`-Spalte die Position.
Sie wechselt immer zwischen ganz hinten nach `updateuser` und der Position nach der ersten "global column", also nach `createdate`.
> rex_sql_table: Teils falsche Spaltenreihenfolge bei ensureGlobalColumns

- redaxo/src/core/pages/packages.php
fixes #3449
Addons ohne Version lassen sich nicht installieren, deswegen muss man es an den anderen Stellen nicht berücksichtigen, denke ich.
> Addonverwaltung: Whoops vermeiden, wenn Version nicht gesetzt

- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/mediapool/pages/sync.php
- redaxo/src/core/assets/standard.js
fixes #3457 
.size() gibt es in jQuery net mehr
> Note: This method has been removed in jQuery 3.0. Use the .length property instead.
siehe [jquery docs](https://api.jquery.com/size/)
dieser fehler ist vermutlich seit #3095 vorhanden.
> fix accesskey shortcuts

- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/addons/structure/plugins/content/pages/templates.php
Beim weiterentwickeln des debug-addons ist mir aufgefallen, dass hier ein Dreher bei den i18n-keys drin war.
es gibt nur i18n-key mit `delete_template` aber nicht `template_delete`.
(In der Liste der getriggerten ExtensionPoints)
> structure: wrong i18n keys

- redaxo/src/addons/install/lib/install.php
- redaxo/src/addons/install/package.yml
eine kleine Klasse, abgeleitet aus den Commands, damit man einfacher in Skripten AddOns downloaden und updaten kann.
(use-case für mich; vereinfachen der demos)
Beispiele für die Doku
```php
$installer = new rex_install();
// lade yform in der Version 3.2.1 herunter.
$installer->downloadAddon('yform', '3.2.1');
// update yform auf die Version 3.2.1
$installer->updateAddon('yform', '3.2.1');
```
> Installer: added rex_install

- .github/workflows/push.yml
https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/
> actions: start mysql manually

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
Die Columns wurden zwar in den DB richtig sortiert, nur im table-objekt waren sie danach nicht richtig.
> rex_sql_table: column sorting korrigiert

- redaxo/src/core/pages/setup.php
- redaxo/src/core/pages/setup.step6.php
Beim Setzen eines Passworts werden überall die Passwortregeln geprüft, nur im Web-Setup nicht (im Console-Setup schon).
Ich denke, wir sollte die auch im Web-Setup testen.
Ich musste dafür an der Stelle das Prehashing rausnehmen (so, wie wir es auch schon an den anderen Stellen gemacht haben). Beim Login ist es weiterhin drin.
> Setup: Passwortregeln berücksichtigen

- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
man muss die Resolution setzen bevor das man Bild einlest, ansonsten wird diese Methode ignoriert
> $imagick->setResolution wurde ignoriert

- redaxo/src/addons/users/lang/de_de.lang
- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/backend.php
- redaxo/src/core/install.php
- redaxo/src/core/lib/console/user/create.php
- redaxo/src/core/lib/console/user/set_password.php
- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/pages/profile.php
Als Admin kann man optional explizit eine Passwortänderung bei einem User anfordern.
Sobald der sich dann einloggt, muss er das Passwort ändern (genauso wie bei der Passworterneuerung über die Passwortregeln).
Geht bei neuen und vorhandenen Benutzern.
Bei neuen Benutzern ist die Checkbox default angehakt.
> Optional explizit Passwortänderung erfordern

- redaxo/src/addons/debug/boot.php
- redaxo/src/core/lib/be/controller.php
- redaxo/src/core/lib/fragment.php
Ich weiß nicht, wie weit wir hier gehen wollen (es hat ja auch minimalen Einfluss auf die normalen Aufrufe ohne Debug-Modus, und es macht den Code weniger gut lesbar finde ich).
Aber mal so als Idee, paar weitere Stellen zu messen.
Aktuell: Layout-Dateien, Fragmente, Pages
Fürs Frontend wären dann noch die einzelnen Templates und Module interessant.
> Weitere Stellen mit rex_timer messen

- redaxo/src/addons/debug/lib/extension_debug.php
- redaxo/src/core/lib/extension.php
- redaxo/src/core/lib/login/user.php
Aktuell haben die EPs eine Sonderrolle, und sind nicht von der 1ms-Grenze betroffen.
Bin mir unsicher, ob das gut ist oder nicht.
Einerseits sieht man in der Timeline so ganz gut, wie der EP-Ablauf aussieht.
Anderseits können das manchmal aber auch recht viele werden, und es stellt sich mir die Frage, warum gerade die EPs da eine Sonderrolle bekommen. Und sie haben ja auch noch eine separate Seite mit Details, wo alle gelistet sind.
Daher zur Diskussion hier eine Änderung, sodass die EPs auch über den normalen Mechanismus gehen, wie die anderen Stellen.
So kann aber passieren, dass gar kein EP mehr auftaucht:
Wie gesagt: bin mir unsicher, ob wir das so ändern sollten, oder nicht.
> Debug-Timeline: EPs über normalen rex_timer-Mechanismus

- redaxo/src/core/backend.php
- redaxo/src/core/lib/login/user.php
refs https://bugs.chromium.org/p/chromium/issues/detail?id=762417
closes https://github.com/redaxo/redaxo/issues/3352
mittels browser detect wird der cache von google chrome nicht mehr geleert wg. des im issue genannten chrome bugs.
getestet in Chrome Canary und Firefox Nightly
> added google chrome workaround for slow clear-site-data bug

- redaxo/src/core/lib/util/timer.php
Ich schlage vor, nur noch im Debug-Modus zu messen.
Das Debug-Addon arbeitet sowieso nur im Debug-Modus, und auf die Server-Timing-Daten in den Devtools (`Server-Timing`-Header) kann man bei Adminaufrufen ohne Debug-Modus denke ich auch verzichten
> rex_timer::measure: nur im Debugmode messen

- redaxo/src/core/lib/system_report.php
Das ist insbesondere wichtig, da der Systembericht ja auch in Whoops verwendet wird, und wenn es da dann zu einem Fehler kommt, kommt die einfache Oops-Seite.
fixes #3566
> Systemreport: SQL-Fehler abfangen

- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
- redaxo/src/addons/structure/plugins/content/lib/var_template.php
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/core/lib/util/timer.php
In der REX_VAR war es recht tricky, aber habe eine funktionierende Variante gefunden.
`rex_timer::measure()` kann dort nicht verwendet werden, da sonst das `require ..` statement in der closure wäre, und somit nicht mehr im gleichen Variablen-Scope wie das äußere Template.
> Templateausführung messen

- composer.json
- psalm.xml
- redaxo/src/addons/install/lib/command/download.php
- redaxo/src/addons/install/lib/command/update.php
- redaxo/src/core/lib/console/package/activate.php
- redaxo/src/core/lib/console/package/deactivate.php
- redaxo/src/core/lib/console/package/delete.php
- redaxo/src/core/lib/console/package/install.php
- redaxo/src/core/lib/console/package/uninstall.php
Das Plugin analysiert nun die Consolen-Argumente/Optionen.
> psalm: add symfony plugin

- redaxo/src/addons/structure/plugins/content/lib/article_content.php
- redaxo/src/addons/structure/plugins/content/lib/content_service.php
Vorher wurde da im Frontend einfach eine Fehlermeldung ausgegeben per `echo`, die den vollen Pfad zum Cache-Ordner enthielt. Da man das ja nicht machen sollte, sehe ich das als Bugfix.
> Artikel-Content-Generierung: Exception bei Fehlern

- redaxo/src/core/lib/util/file.php
fixes #595
touch() lässt sich nur nutzen, wenn man der Owner der Datei ist.
> touch(): Fehler unterdrücken

- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/be_style/package.yml
- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/debug/package.yml
- redaxo/src/addons/install/package.yml
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/users/package.yml
Aufgefallen war das Problem bei einigen, da ich den Installer ja auch einzeln zur Verfügung gestellt habe für R>=5.7. Und R5.7 ist noch kompatibel zu PHP>=5.5, aber die einzeln veröffentlichte Installer-Version benötigt schon PHP>=7.1.
> Addons: PHP-Mindestversion setzen

- redaxo/src/core/lib/form/elements/container.php
Paar Zeilen weiter das `assert()` löste sonst teils aus.
Daher nun ein schnelles Abbrechen bei `null`, da die Methode da sowieso nichts macht.
> fix AssertionError

- .tools/bin/update-requirements
- .tools/bin/update-root-composer
- .tools/bootstrap.php
- .tools/constants.php
- composer.json
- phpstan.neon.dist
- psalm.xml
Behebt diese Probleme:
- Lokal gab es vorher bei phpstan bei mir immer Fehler, wenn nicht alle Addons/Plugins aktiviert waren
- Für die Analyse wurde für symfony/yaml zum Beispiel die Dateien aus `/vendor` statt aus `redaxo/core/vendor` genommen, es wurde also unter Umständen mit anderen Versionen analysiert, als die eigentlich in Redaxo liegen
Und der PR stellt das Repo nun unter `redaxo/source` zur Verfügung.
> root composer.json

- .github/workflows/csfix.yml
- .github/workflows/push.yml
- .github/workflows/visual-tests.yml
see 
- https://github.community/t5/GitHub-Actions/Don-t-run-actions-on-draft-pull-requests/m-p/55316/highlight/true#M9508
- https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
> Note: By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.
> trigger github-actions when PR leaves DRAFT state

- redaxo/src/core/lib/var_dumper.php
Bei Verwendung von UiKit im Front- und Backend wurde die Ausgabe von `<samp>` von uikit übernommen. Durch Zuordnung eines eigenen Stils für `expanded` kann das gelöst werden.  
fixes https://github.com/redaxo/redaxo/issues/3627
vorher: 
Nachher:
> debug() expanded design fix

- .github/workflows/cs-fix.yml
- .github/workflows/visual-tests.yml
inspired by https://github.community/t5/GitHub-Actions/Stop-github-actions-running-on-a-fork/m-p/51555#M8236
damit wir niemanden abschrecken da der PR nie grün wird, oder sich jemand verausgabt den Build grün zu bekommen, obwohl es in forks technisch aktuell gar nicht möglich ist
-> weniger verwirrung
> GithubAction: dont run jobs on forks, because we are not allowed to commit

- redaxo/src/addons/be_style/boot.php
While preloading a primary font is best practice, preloading a less important icon font is not
The UI works great without the icons, so we dont need them prioritized that much
> Dont preload font-awesome

- redaxo/src/addons/debug/boot.php
`!(rex_server('REQUEST_URI') || rex::getConsole())` wird nicht mehr benötigt, da wir keinen anderen Zugriffspunkte außer console und web-sapi haben.
> Debug: remove unnecessary check

- redaxo/src/core/lib/console/config/set.php
- redaxo/src/core/tests/console/config/set_test.php
closes #3673 
aktuell lässt sich ein boolesches `false` nur durch  
`php redaxo/bin/console config:set --type="bool" debug.enabled 0`
setzen.
Ich würde als Anwender erwarten, dass ich ein `false` auch "ausgeschrieben" setzen kann.
`php redaxo/bin/console config:set --type="bool" debug.enabled false`
> Console: config:set allow boolean string

- redaxo/src/core/pages/system.log.redaxo.php
Erweiterung der Redaxo-Log-Darstellung um Success (grün).
Bisher:
```
rex_logger::factory()->log('Error', 'Error-Eintrag');
rex_logger::factory()->log('Notice', 'Notice-Eintrag');
rex_logger::factory()->log('Warning', 'Warning-Eintrag');
```
Neu: 
`rex_logger::factory()->log('Success', 'Success-Eintrag');`
> Redaxo-Log-Eintrag um Success erweitern

- redaxo/src/core/console.php
fixes #3693
Wir fragen bei dem Cache-Handling der package.yml zwar `rex::getConsole()` ab, aber das war zu dem Zeitpunkt noch gar nicht befüllt.
> rex::getConsole() befüllen vor Laden der Addons

- redaxo/src/core/lib/sql/column.php
- redaxo/src/core/lib/sql/schema_dumper.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
refs https://github.com/redaxo/redaxo/issues/3700
in der CLI getestet:
```bash
$ php redaxo/bin/console db:dump-schema rex_webvitals
rex_sql_table::get(rex::getTable('webvitals'))
->ensureColumn(new rex_sql_column('id', 'int(11)', false, null, 'auto_increment'))
->ensureColumn(new rex_sql_column('uri', 'text'))
->ensureColumn(new rex_sql_column('article_id', 'int(11)'))
->ensureColumn(new rex_sql_column('clang', 'int(11)'))
->ensureColumn(new rex_sql_column('cls', 'int(11)', true, null, null, 'cumulative layout shift'))
->ensureColumn(new rex_sql_column('fid', 'int(11)', true, null, null, 'first input delay'))
->ensureColumn(new rex_sql_column('lcp', 'int(11)', true, null, null, 'largest contentful paint'))
->ensureColumn(new rex_sql_column('ttfb', 'int(11)', true, null, null, 'time to …
```
> take mysql comments into account in `rex_sql_column`

- redaxo/src/addons/structure/plugins/content/pages/templates.php
fixes #3730
Der Fehler entstand, wenn man das Default-Template löschen wollte, und es aber bei keinem Artikel hinterlegt ist.
> Template-Lösch-Fehler korrigiert

- redaxo/src/core/pages/system.settings.php
Seit https://github.com/redaxo/redaxo/pull/3639 hat die Editor-Einstellung einen eigenen Block.
Bei der Speicherroutine des oberen Block müssen diese Zeilen daher weg, sonst wird beim Speichern oben der Editor immer genullt.
> Systemeinstellungen: Editor nicht nullen

- redaxo/src/core/lib/login/password_policy.php
- redaxo/src/core/tests/login/password_policy_test.php
In unserer Default-Config haben wir manche Regeln nur mit "min 0", zur leichteren Anpassung:
https://github.com/redaxo/redaxo/blob/fc198811bbfb6447c9a54c34aa59e3a974671fa7/redaxo/src/core/default.config.yml#L33-L37
Vorher sah dann die Meldung aber so aus:
Dieser PR ändert es in:
> Passwortregeln: "min 0" ignorieren

- redaxo/src/core/lib/console/assets_sync.php
closes https://github.com/redaxo/redaxo/issues/3714
Getestet indem man 
- eine datei verändert
- speichert (damit sich die filemtime ändert)
- die datei vom inhalt her wieder auf den stand von zuvor zurück verändert
- erneut speichert
-> jetzt hat man dateien die inhaltlich identisch sind, aber mit gleichem content-hash.
-> vor dem PR wurden diese dateien kopiert. Jetzt nach der Änderung nicht mehr
> assets:sync: compare file hash additional to the filemtime

- redaxo/src/core/lib/sql/table.php
Warum da genau nun ein `INNER`-Join nötig ist, habe ich nicht verstanden. Aber jedenfalls funktioniert es so wieder, und eigentlich wäre vorher auch schon ein `INNER` korrekter gewesen.
> mysql 8.0.21: Fix für Abfrage der Fremdschlüssel

- .idea/php.xml
- .idea/redaxo.iml
- .travis.yml
- composer.json
- phpunit.xml.dist
- psalm.xml
- redaxo/src/addons/media_manager/tests/media_manager_test.php
- redaxo/src/addons/structure/plugins/content/tests/article_content_test.php
- redaxo/src/addons/structure/tests/article_test.php
- redaxo/src/addons/structure/tests/category_test.php
- redaxo/src/core/tests/console/config/set_test.php
- redaxo/src/core/tests/extension_test.php
- redaxo/src/core/tests/login/backend_login_test.php
- redaxo/src/core/tests/sql/sql_select_test.php
- redaxo/src/core/tests/sql/sql_table_test.php
- redaxo/src/core/tests/sql/sql_test.php
- redaxo/src/core/tests/util/dir_test.php
- redaxo/src/core/tests/util/file_test.php
- redaxo/src/core/tests/util/finder_test.php
- redaxo/src/core/tests/util/i18n_test.php
- redaxo/src/core/tests/util/log_file_test.php
- redaxo/src/core/tests/util/socket_proxy_test.php
- redaxo/src/core/tests/util/socket_test.php
- redaxo/src/core/tests/util/sortable_iterator_test.php
- redaxo/src/core/tests/util/timer_test.php
- redaxo/src/core/tests/var/var_config_test.php
- redaxo/src/core/tests/var/var_property_test.php
Ich denke bei PHPUnit brauchen wir keine fixe Version.
Und die neueren Versionen sind besser auf die neueren PHP-Versionen abgestimmt.
-> mal schauen, ob die aktuellen probleme bei den php8-tests dadurch gelöst werden.
> phpunit: auch v8 und v9 zulassen

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
fixes #3828
Ich habe es grob mit Blackfire getestet, und es scheint keinerlei Auswirkung zu haben (auch bei 1000 Queries nicht).
> rex_sql: lastInsertId zwischenspeichern

- redaxo/src/core/lib/util/dir.php
fixes #3823
Aktuell habe ich es jetzt so, dass die Warnings unterdrückt werden, aber der Returnwert bleibt gleich.
Also wer den Aufruf in ein `if ()` packt, wird weiterhin `false` erhalten, wenn ein Ordner letztlich nicht gelöscht werden konnte.
Bin mir nicht ganz sicher, aber denke das würde ich auch beibehalten.
> rex_dir::delete(): ignore warning

- redaxo/src/addons/structure/plugins/content/boot.php
- redaxo/src/addons/structure/plugins/content/lib/article_not_found_exception.php
Im Moment ist es nicht so leicht, aus dem Template oder sogar erst aus einem Modul heraus umzuschwenken auf den 404-Artikel (mit 404 Statuscode).
Man könnte auf den Fehlerartikel weiterleiten. Das wäre aber ja eine 30x-Weiterleitung auf eine 404-Seite, und es würde sich somit die Adresse im Browser ändern.
Ich möchte aber den Fall lösen, dass die Adresse stehen bleiben soll, und aber die 404-Seite mit 404-Code erscheinen soll.
Aktuell müsste man dazu den Output Buffer leeren, und dann selbst per `rex_article_content` stattdessen den Fehlerartikel ausgeben, und dann müsste man eventuell auch noch per exit abbrechen.
Mit diesem PR wäre es stattdessen möglich im Template/Module die neue `rex_article_not_found_exception` zu werfen, und das content-Plugin würde dann darauf reagieren und …
> Einfache Möglichkeit, aus Template/Module auf Fehlerseite zu leiten

- redaxo/src/addons/users/pages/users.php
Wenn man die neuen Passwortregeln nutzt, die Checks gegen die vorher verwendeten Passwörter machen, dann kann man aktuell keinen neuen Benutzer anlegen.
Grund: Die Benutzerseite arbeitet mit id=0 für Benutzeranlage, die Passwort-Rules-Api erfordert dort aber `null`.
> Benutzer erstellen: Fehler bei neuen Passwortregeln

- redaxo/src/addons/install/pages/packages.add.php
Beim Update eines Addons erscheint eine Warnung bei Entwicklungsversionen.
Diese Ausgabe fehlt bei der Erstinstallation eines Addons.
> Unstable-Warnung auch für Addon-Erstinstallation

- .github/workflows/cs-check.yml
- .github/workflows/cs-fix.yml
- .github/workflows/rexlint.yml
- .travis.yml
- composer.json
- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/be_style/composer.json
- redaxo/src/addons/be_style/package.yml
- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/debug/package.yml
- redaxo/src/addons/install/package.yml
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/phpmailer/composer.json
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/users/package.yml
- redaxo/src/core/boot.php
- redaxo/src/core/composer.json
- redaxo/src/core/update.php
Ich schlage vor, nun mal wieder die PHP-Version zu erhöhen, und zwar direkt um zwei Versionen auf min. 7.3.
PHP 7.2 erhält noch 2 Monate Sicherheitsfixes: https://www.php.net/supported-versions.php
Ich würde die aber trotzdem schon weglassen. Ich habe ja auch schon öfters gesagt, dass ich lieber seltenerer größere Sprünge mache, als kontinuierlich kleine.
Aus meiner Sicht brauchen wir auch nicht vorher eine Version mit Warnung rausbringen. Man sieht ja beim Update dann, dass es nicht geht, und bleibt dann halt erst mal bei R5.11, wenn man die PHP-Version wirklich noch nicht hochsetzen kann/mag.
(Eventuell würde ich noch eine 5.11.1 rausbringen. Falls ich das mache, könnte man da dann natürlich schon doch noch die Warnung einbauen.)
> Min-PHP erhöhen auf 7.3

- redaxo/src/addons/cronjob/lib/command/run.php
Dies ist ein Teil-Revert von https://github.com/redaxo/redaxo/pull/3865.
An der Stelle war `VALUE_OPTIONAL` korrekt, man darf also `cronjob:run --job` ohne weiteren Wert aufrufen, und bekommt dann interaktiv eine Auswahl der Jobs.
> Cronjob-Command: job-Option benötigt keinen Wert

- .github/dependabot.yml
Ich schlage vor, das Intervall auf `weekly` umzustellen. 
Wir brauchen ja nicht dringend taggleiche Updates, und manche Libs updaten sehr oft. Daher würde ich das bei uns reduzieren wollen.
Falls man mal schneller ein Update haben möchte, kann man ja auch immer noch hier manuell den Prozess starten:
https://github.com/redaxo/redaxo/network/updates
> Dependabot: weekly updates

- redaxo/src/core/lib/sql/sql.php
wenn ein neuer user direkt nach clonen des repositories phpunit startet, ohne das setup durchlaufen zu haben, fehlen die datenbank zugangsdaten und phpunit endet weniger hilfreich mit
```
$ vendor/bin/phpunit -v
PHPUnit 9.4.0 by Sebastian Bergmann and contributors.
Could not connect to database
```
um in diesem fall dem developer hinweise zu geben, werden in diesem fall eine aussagekräftigere fehlermeldung ausgegeben.
Vorschlag mit diesem PR:
```
$ vendor/bin/phpunit -v
PHPUnit 9.4.0 by Sebastian Bergmann and contributors.
Could not connect to database.
Consider starting either the web-based or console-based REDAXO setup to configure the database connection settings.
```
> DX: Hinweis ergänzt wenn keine datenbank connection aufgebaut werden kann

- redaxo/src/core/tests/util/formatter_test.php
Auf windows schlagen diese Tests ohne die Änderungen fehl, da wg. überlauf des max-int wertes komplett andere ergebniss entstehen
> skip `rex_formatter` tests which require 64bit php on 32bit php

- redaxo/src/core/tests/console/config/get_test.php
ohne diesen fix werden newlines nicht normalisiert, was dazu führt dass unter windows diese tests fehlschlagen
aufgefallen in https://www.youtube.com/watch?v=e_ohxyAvKAU
vor dem PR:
```diff
1) rex_command_config_get_test::testKeyFound with data set #0 ('false\n', 'setup')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'false\n
+'false\r\n
'
C:\xampp7.3\htdocs\redaxo\redaxo\src\core\tests\console\config\get_test.php:20
2) rex_command_config_get_test::testKeyFound with data set #1 ('"root"\n', 'db.1.login')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'"root"\n
+'"root"\r\n
'
C:\xampp7.3\htdocs\redaxo\redaxo\src\core\tests\console\config\get_test.php:20
3) rex_command_config_get_test::testPackageKeyFound
Failed asserting that two …
```
> tests: normalize newlines to make tests work consistently on windows

- redaxo/src/core/lib/var/var.php
- redaxo/src/core/tests/var/var_test.php
Dieser Commit gleicht die verwendeten Parameter beim Aufruf von
htmlspecialchars_decode an die Parameter an, die rex_escape fuer
das Escaping mittels htmlspecialchars nutzt. Dadurch wird eine
Inkonsistenz bzgl. der Interpretation von Quotes behoben und damit
eine freie Kombination von rex_var::toArray und rex_escape ermoeglicht.
Siehe Issue #3886 für eine ausführlichere Diskussion des Problems.
> rex_var::toArray Dekodierung an rex_escape anpassen

- redaxo/src/core/lib/util/markdown.php
- redaxo/src/core/tests/util/markdown_test.php
Dies ist teilweise ein Backport von https://github.com/redaxo/redaxo/pull/3833 (nicht enthalten ist die Header-ID-Präfixänderung).
Zusätzlich: fixes #3931
Wenn Überschriften Quotes enthalten, bleiben die in der Sprungnavi erhalten, und werden nun korrekt behandelt.
> Markdown TOC: Handling von HTML/Markdown/SpecialChars innerhalb der Überschriften

- .github/workflows/cs-check.yml
- .github/workflows/cs-fix.yml
- .github/workflows/rexlint.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
`https://github.com/ramsey/composer-install` impliziert dependency caching, daher wirds damit einfacher.
> ramsey/composer-install is a GitHub Action to streamline installation of Composer dependencies in workflows. It installs your Composer dependencies and caches them for improved build times.
> Use ramsey/composer-install@v1 to simplify GithubAction workflow

- .idea/inspectionProfiles/Project_Default.xml
- .idea/php.xml
- .idea/redaxo.iml
Aktiviert den nativen psalm/phpstan support in PhpStorm (2020.3 EAP).
Zukünftig könnten wir dann (zumindest bzgl. phpstorm) an den meisten Stellen auch auf den `psalm-`-Präfix verzichten, und direkt die genaueren Typen über `@param` etc. angeben.
https://blog.jetbrains.com/phpstorm/2020/10/phpstorm-2020-3-eap-2/
> PHPStorm-Settings: psalm/phpstan aktiviert

- .tools/phpstan/baseline.neon
- composer.json
- phpstan.neon.dist
Upstream issues
- https://github.com/phpstan/phpstan/issues/3069
- https://github.com/phpstan/phpstan/issues/3549
hinzufügen einer phpstan baseline die via composer scripts generiert werden kann.
`composer phpstan` prüft die code base und meldet fehler
`composer phpstan-baseline` ignoriert alle in der codebase gefunden fehler für zukünftige phpstan-scans
feedback aus https://github.com/redaxo/redaxo/pull/3535 übernommen
> increase phpstan level to 5 and generated a baseline

- .tools/psalm/RexTypeReturnProvider.php
- redaxo/src/addons/structure/plugins/content/pages/content.php
- redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
- redaxo/src/core/pages/setup.php
- redaxo/src/core/pages/system.clangs.php
fixes #4003
Es werden nun auch die komplexeren Array-Typen unterstützt, wie z. B. hier: https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/media_manager/pages/settings.php#L20-L25
Bringt zumindest 1% mehr Typsicherheit ;)
```
// Vorher
Psalm was able to infer types for 87.8527% of the codebase
// Nachher
Psalm was able to infer types for 88.8930% of the codebase
```
> psalm: RexTypeReturnProvider erweitert

- redaxo/src/core/lib/setup/setup.php
Für boolsche Variablen kann auch ein leerer String für false zurück kommen.
Kam heute in Slack auf: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1604919943469600
> ini_get kann auch leeren String liefern

- .tools/psalm/baseline.xml
- composer.json
- psalm.xml
Ich würde mal ausprobieren, wie sich das macht.
Es könnte sein, dass es in neuem Code nervig wird, weil unsere Altcode an vielen Stellen mit null noch nicht richtig umgeht, oder psalm jedenfalls den Eindruck hat, und so dann ggf. in neuem Code Folgeerscheinungen auftreten.
Aber wie gesagt, ich würde es mal ausprobieren.
> psalm: activate null errors, use baseline

- composer.json
- redaxo/src/addons/be_style/composer.json
- redaxo/src/addons/be_style/composer.lock
- redaxo/src/addons/debug/composer.json
- redaxo/src/addons/debug/composer.lock
- redaxo/src/addons/phpmailer/composer.json
- redaxo/src/addons/phpmailer/composer.lock
- redaxo/src/core/composer.json
- redaxo/src/core/composer.lock
- redaxo/src/core/vendor/composer/ClassLoader.php
- redaxo/src/core/vendor/composer/InstalledVersions.php
- redaxo/src/core/vendor/composer/autoload_classmap.php
- redaxo/src/core/vendor/composer/autoload_real.php
- redaxo/src/core/vendor/composer/autoload_static.php
- redaxo/src/core/vendor/composer/installed.json
- redaxo/src/core/vendor/composer/installed.php
Ich möchte zukünftig Composer 2 nutzen für die Vendor Updates.
Ich schlage vor, diese neuen platform checks in v2 vorerst zu deaktivieren.
PHP-Version prüfen wir schon selbst bei jedem Aufruf.
Extensions allerdings nur während des Setups, aber trotzdem würde ich die Checks in Composer vorerst nicht aktivieren.
> Use composer v2

- psalm.xml
Siehe https://psalm.dev/docs/running_psalm/issues/Trace/.
Man kann per `@psalm-trace $var` sich einen Typ einer Variable ausgeben lassen.
Ich wunderte mich schon eine Zeit, warum das bei mir nicht funktionierte. Jetzt habe ich kapiert, dass die Trace-Meldungen info-Meldungen sind, die wir normalerweise nicht ausgeben.
Ich würde die als Error werten. So sieht man sie definitiv, praktisch für das Debuggen. Und wir wollen die ja auch nicht dauerhaft im Code haben, und so wird auch verhindert, dass wir sie versehentlich mit mergen.
> psalm: Debug-Trace-Ausgaben als error werten

- redaxo/src/core/lib/rex.php
Da die Methode neu ist, können wir native Type-hints nutzen
> Native type-hints nutzen

- redaxo/src/core/lib/config_db.php
In Neuinstallationen sind die Keys in der config.yml vorhanden, aber in Altinstallationen können die fehlen.
(config.yml wird ja nicht angepasst bei update)
> Undefined Notice vermeiden

- .github/workflows/static-analysis.yml
taint analysis job um sicherheitslücken im code zu finden.
https://psalm.dev/articles/detect-security-vulnerabilities-with-psalm
sobald das nächste psalm release erstellt wurde können wir dann auch SARIF reports erstellen und diese direkt ins github.com reinladen, sodass github die security reports im repo zur triage bereitstellt
> GithubAction: added a psalm taint analysis job

- composer.json
man bekommt jetzt einen error wenn man noch compoer v1 benutzt:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
- The requested package composer-plugin-api ^2 exists as composer-plugin-api[1.1.0] but these are rejected by your constraint.
```
technisch funktionierts, schön ist es nicht.. daher upstream issues: https://github.com/composer/composer/issues/9501
> require composer v2.. our setup doesn't work with v1 anymore

- .tools/phpstan/baseline.neon
- phpstan.neon.dist
see https://phpstan.org/blog/detecting-unused-private-properties-methods-constants
alle gefundenen fehler werden gebase-lined und in separaten PRs abgearbeitet.
die vollständige liste an Fehlern aus der Analyse kann man diesem PR hier aus der baseline entnehmen
> phpstan: activate dead code detection

- .tools/rector/rector.php
use the same autoload file, we already use for psalm/phpstan
> rector: prevent 'Use of undefined constant REX_MIN_PHP_VERSION' warnings

- .tools/rector/rector.php
instead of listing all rules.. just a cosmetic change
> recotor: activate early-return set instead of separate rules

- redaxo/src/core/lib/error_handler.php
https://www.php.net/manual/de/migration80.incompatible.php
> The @ operator will no longer silence fatal errors (E_ERROR, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR, E_RECOVERABLE_ERROR, E_PARSE). Error handlers that expect error_reporting to be 0 when @ is used, should be adjusted to use a mask check instead:
Das führt bei uns zu einem Problem, aber nur wenn `debug.throw_always_exception` in der config.yml aktiviert ist. Dann hat mit PHP 8 der `@`-Operator keinen Effekt mehr, und es kommt auch dort zu Exceptions, wo wir eigentlich bewusst unterdrücken wollen (`@file_get_content()` etc.).
Das neue Verhalten ist nun minimal anders:
Vorher: Fehlerunterdrückung wird immer beachtet. Aber `throw_always_exception` ignoriert die `error_reporting`-Einstellung aus der php.ini.
Neu: …
> Anpassung rex_error_handler für PHP 8

- .tools/bin/refresh
Das refresh-Skript (um die lokale Entwicklungsumgebung nach pull oder branch wechsel zu aktualisieren) reinstalliert nun alle vorhandenen Core-Packages (vorher fehlten manche).
Und es reinstalliert aber nur noch die, die vorher schon installiert waren.
> refresh script: alle core packages reinstallieren, aber nur wenn schon installiert

- .github/workflows/tests.yml
this is a **new feature of composer v2**, see https://php.watch/articles/composer-ignore-platform-req
that way extension requirements are still checked
> tests: ignore only php version constraints

- redaxo/src/core/lib/packages/manager.php
finalizes https://github.com/redaxo/redaxo/pull/3991
closes #3961
Co-authored-by: Vitalij Mik <BlackScorp@users.noreply.github.com>
getestet mit 
```
$addon->setProperty('statusmsg', 'bitte verwende den neuen <a href="lala">menupunkt</a>');
```
im debug addon in der `install.php`:
> Addon-Installation: Eigene Zusatzmeldungen auch bei Erfolg

- .tools/psalm/RexTypeReturnProvider.php
- .tools/psalm/baseline-taint.xml
- redaxo/src/core/lib/login/user.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
Hilft uns bei der Typsicherheit.
Ich bin mir aber noch unsicher. `getDateTimeValue` ist zum beispiel nullable, `getIntValue` nun aber nicht.
Man könnte daher auch überlegen, ob man ähnlich zu anderen klassen für die nicht nullable variante den require-präfix nimmt. Wäre hier dann also `requireIntValue`. Analog, falls wir Bedarf dafür finden, könnte man irgendwann auch noch `requireValue` als allgemeine non-nullable-methode einführen, oder eben `requireDateTimeValue`.
Und eventuell könnte man irgendwann auch eine nullable `getIntValue` gebrauchen für nullable int columns.
> rex_sql: type support in getValue

- redaxo/src/addons/mediapool/lib/media_category_select.php
Der PR löst gleich zwei Probleme:
* Bei Nutzung von `setRootId` war das Select leer, wenn die Root-Kategorie nicht auf oberster Ebene liegt (dieses Repo nutzt nirgends `setRootId`)
* Bei eingeschränkten Mediacat-Rechten fehlten Kategorien, wenn man Rechte für Unterkategorien hatte, aber nicht für deren Root
Beide Bugs muss es bereits seit 5.0 gegeben haben, der Code hat sich seitdem nicht geändert.
fixes #4135 /cc @skerbis
> rex_media_category_select: fix root & perm handling

- redaxo/src/addons/backup/lib/tar.php
- redaxo/src/addons/cronjob/lib/types/phpcode.php
- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/lib/cache_media.php
- redaxo/src/addons/structure/plugins/content/lib/api_template.php
Eigentlich wollte ich die neue `simplified_if_return` rule aktivieren.
Aber einerseits ist die automatische Formatierung dort oftmals nicht so schön, andererseits gab es auch eine Stelle wo ich die vorherige Variante besser lesbar fand.
Deswegen habe ich den Fixer nur einmalig angewandt und habe die Stellen anschließend noch optimiert bzgl. Formatierung und bzgl. verneinte Klammern etc.
> cs: simplified if return

- redaxo/src/core/lib/sql/sql.php
> reset(): Argument 1 ($array) must be passed by reference, value given
> PHP 8: Warnings vermeiden

- composer.json
- phpunit.xml.dist
after some initial testing this depenency does not solve a problem we have.
additionally it slows down our test-runs a lot
> remove nunomaduro/collision dependency

- .github/workflows/visual-tests.yml
It might be the cause why the action sometimes isnt triggered (and we dont use it nevertheless)
> Remove ci-skip handling

- .tools/bin/refresh
vor diesem fix wurde der core-assets ordner in den /assets/core/ ordner kopiert.
nach dem fix werden nur noch die Inhalte des assets ordner kopiert:
da die dateien nicht richtig kopiert wurden war bei mir auch das REDAXO Logo so rießig dargestellt worden
> `composer refresh`: fix core-assets copying

- .idea/php.xml
phpstorm versucht schlau zu sein und einen lang level selbst zu erkennen.
dies wird hiermit unterbunden
> .idea: prevent "suggest default language level change"

- redaxo/src/addons/structure/plugins/content/assets/content.js
Betrifft das Script zum Speichern der Toggle-Status der Sidebar-Panels im localStorage (#4178): Mit der Umstellung auf [viewRoot.find()](704cf581f5af05b13368f3049ba8ec7380b75c75) ist das Script kaputt gegangen. Weil `viewRoot` nur noch den Inhalt des `<body>` enthält, an dem `#rex-page-content-edit` hängt, liefert das nachfolgende `find()` kein Ergebnis mehr. Denn das durchsucht ja nur Kindelemente, und nicht das aktuelle Element.
> fix sidebar panel toggle js (structure/content)

- redaxo/src/core/console.php
otherwise we would never see the `PHP version >=7.3 needed!` message, when the rex-console is invoked with a unsupported php version.
before this PR invoking `redaxo/bin/console config:get setup` on PHP 7.2 would just return empty with a 255 exit code.
```
$ php redaxo/bin/console config:get setup
$ echo $?
255
```
after this PR we are getting the underlying error on STDERR and a 254 error code.
```
$ php redaxo/bin/console config:get setup
PHP version >=7.3 needed!
#0 /cluster/www/www/www/redaxo/redaxo/src/core/console.php(13): require()
#1 /cluster/www/www/www/redaxo/redaxo/bin/console(11): require('/cluster/www/ww...')
#2 {main}
$ echo $?
254
```
> setup a minimal exception handler to print early errors in console

- redaxo/src/core/lib/console/setup/run.php
vorher
nachher
man beachte das `-` Auflistungskennzeichen
> console-setup: print file-errors in list-style

- .gitattributes
otherwise the scripts, when running on windows, might not work (because of git core.autocrlf)
see https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings
> add global .gitattributes to make git checkouts work when git core.autocrlf is configured

- redaxo/src/core/lib/util/logger.php
Seit https://github.com/redaxo/redaxo/pull/3904 schreiben wir das Loglevel immer mit einem Großbuchstaben in die Logdatei.
Das ist aber bei unseren `rex_exceptions` nicht so schön, da die nun mal eigentlich klein geschrieben werden.
> rex_logger: rex_exceptions ohne Großbuchstabe vorne

- redaxo/src/addons/backup/pages/import.server.php
- redaxo/src/core/assets/standard.js
Dieser PR fixt #4335 für R5.11.2, ich sehe das als Bug an.
Für die neue pjax-Variante (5.12) ist der Fix in #4337 enthalten.
> Download-Links ohne PJAX, insbesondere bei Backups

- redaxo/src/core/lib/response.php
fixes #4331
Habe es auf dem strato-server getestet, so kommt der Fehler nicht mehr.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing
> Server-Timings über einen einzigen Header

- redaxo/src/addons/backup/pages/export.php
Wenn man ein Dateibackup erstellt, erscheinen anschließend im Formular fälschlich sowohl die Tabellen-Auswahl als auch die Ordner-Auswahl. 
Nach diesem PR erscheint in dem Zustand korrekt nur noch die Ordner-Auswahl.
> Nach Backup erstellen: Korrekte Felder einblenden

- redaxo/src/core/lib/error_handler.php
- redaxo/src/core/vendor/filp/whoops/src/Whoops/Resources/js/whoops.base.js
- Button-Styles angeglichen
- Enthält auch den Fix aus https://github.com/filp/whoops/pull/685; würde den trotz Vendor-Code einfach schon bei uns so aufnehmen
- Whoops hat einen "Hide"-Button eingeführt. Der wird mit diesem PR entfernt, da er bei uns keinen Sinn macht. Denn nach Klick darauf sieht es so aus:
---
Vorher:
Nachher:
> Whoops: fix buttons

- .tools/phpstan/baseline.neon
- phpstan.neon.dist
- redaxo/src/core/lib/sql/sql.php
https://phpstan.org/config-reference#treatphpdoctypesascertain
Wenn wir einen Typ nur per phpdoc deklarieren, dann wollen wir ihn durchaus php-seitig nochmal explizit checken und verlassen uns nicht immer nur auf den phpdoc.
Daher würde ich diese Option in phpstan so setzen.
> phpstan: disable treatPhpDocTypesAsCertain

- .tools/psalm/baseline-taint.xml
- redaxo/src/core/lib/form/elements/control.php
Der `class`-Key wird im Fragment gar nicht verwendet, sondern über `formatElement()` wird bereits auch das `class`-Attribut gesetzt.
> remove unused code

- redaxo/src/addons/media_manager/lang/en_gb.lang
- redaxo/src/addons/media_manager/lang/es_es.lang
- redaxo/src/addons/media_manager/lang/sv_se.lang
Im Deutschen heißen die Effekte so:
Im Englischen und auch den anderen Sprachen war der Präfix hingegen nicht so einheitlich:
Nach diesem PR sieht es dann so aus:
> MM-Effekte-Namen einheitlicher

- redaxo/src/core/lib/setup/setup.php
Seit https://github.com/redaxo/redaxo/commit/620900ad7ff6a86bc0ff312829ff93c116749a9a verwenden wir zum ersten Mal direkt die `filter_var`-Funktion. 
Wobei sie indirekt scheinbar auch vorher schon erforderlich war, da unter anderem AntiXSS sie verwendet.
Und auch sf/http-foundation verwendet sie.
Die filter-Extension ist sehr Standard, aber doch auch nicht immer vorhanden. Daher besser der explizite Check.
(Ich meine, ich hätte im Slack schon jemanden gesehen, wo die Extension fehlte.)
Siehe auch https://externals.io/message/112976.
> filter-extension als erforderlich gesetzt

- redaxo/src/addons/mediapool/pages/media.detail.php
- redaxo/src/addons/mediapool/pages/media.list.php
ref #4456
Lange Titel und Dateinamen werden umgebrochen. An den Spaltenbreiten wurde nichts geändert.
Update. Auf der Detailseite ebenso für den Filenamen ergänzt:
> mediapool: use word-break for title and file name

- redaxo/src/core/lib/util/string.php
- redaxo/src/core/tests/util/string_test.php
fixes #4450
Ist nicht ganz unkritisch, hier mit Halbwissen in das AntiXSS-Skript einzugreifen.
Ich vermute aber, dass dieser Regex mehr ein "sicher ist sicher" darstellt, und kein direkt notwendiger ist.
Das leite ich daraus ab, dass das AntiXSS-Skript ja generell versucht, JS-Code zu verhindern, nicht nur diesen spezifischen.
Wenn dieser Regex so absolut notwendig wäre, wäre auch merkwürdig, dass man ihn ja sehr leicht umgehen könnte, indem man Leerzeichen um den `.`-Operator ergänzen würde.
> sanitizeHtml: allow "window.location" code snippet

- redaxo/src/core/lib/extension.php
Siehe dazu Diskussion in Slack: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1614011906115000?thread_ts=1613996172.089200&cid=C1BAXLN2F
(insbesondere auch dann weiter unten im Thread)
Wie dort diskutiert, wegen BC, für den String-Fall nur eine Warnung, und ansonsten aber dem bisherigen Verhalten.
Es hat sich rausgestellt, dass es mehrere Stellen gibt, wo der String "LATE" übergeben wurde, und es damit trotzdem funktionierte in 5.11, da dort nach int gecastet wurde.
> rex_extension: Umgang mit $level-Param

- redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Ist hier passiert: https://github.com/redaxo/redaxo/pull/4465/files
Ich hatte in dem PR eigentlich mir extra die rex_article_slice-Klasse noch angeschaut, ob die Umbenennung irgendwo ein Problem sein könnte. Aber die Stelle hatte ich leider nicht entdeckt.
> rex_article_slice: Propertynamen korrigiert

- redaxo/src/core/functions/function_rex_other.php
- redaxo/src/core/lib/autoload.php
@polarpixel hatte beim Update auf die 5.12 Probleme, nach dem Update wurde gemeldet, es würde die Klasse `rex_config_db` fehlen. 
Ich konnte es auf seiner Seite debuggen und habe dabei zwei Probleme festgestellt:
Wenn man `rex_autoload::addDirectory()` mit einem nicht-existierenden Ordner aufruft, dann wird der Cache neugeschrieben, der Inhalt bleibt aber wie zuvor.
Peter nutzt das theme-Addon. Dieses [fügt einen eigenen Pfad zum Autoloader hinzu](https://github.com/FriendsOfREDAXO/theme/blob/6c20cb8ce3b88bba8b4289c32c6f95efa69db652/boot.php#L12).
Dieser Pfad existiert aber nicht immer, je nachdem, was man letztlich so im theme-Ordner drin hat. Bei Peter ist der Pfad nicht vorhanden.
Das hat zur Folge, dass bei Peter bei jedem Seitenaufruf der Autoload-Cache neugeschrieben wird.
Das ist …
> Autoloader: fix cache handling

- redaxo/src/core/lib/setup/setup.php
closes #4492
Ich habe nochmal geschaut, wann wir das Beenden der Session dort eingefügt haben:
https://github.com/redaxo/redaxo/commit/c3e93dbe8903f2790fd66e3644ca1f65e3fd1cd9, als Reaktion auf https://github.com/redaxo/redaxo/issues/150.
Es ging also nicht um technische Gründe, sondern nur um die Unstimmigkeit des "Zum Login"-Buttons ganz am Ende.
Ich würde das wieder rückgängig machen. Ich finde die Unstimmigkeit nicht so schlimm, dass man bei erneutem Setup dann trotz "Zum Login"-Buttons direkt im Backend landet.
Man könnte den Button auch umbenennen, wobei auch weiter oben im Text steht, man solle sich einloggen. Siehe https://github.com/redaxo/redaxo/pull/4371.
Ich würde es wohl erstmal einfach so lassen.
---
Es stellt sich jetzt höchstens die Frage, ob es vielleicht doch auch …
> Setup: Backend-Session nicht beenden

- redaxo/src/core/lib/util/formatter.php
closes #4493
Ich habe es nun so gemacht, dass bei den speziellen 0000er Dates nur eine Warnung kommt (und der Formatter liefert letztlich einen leeren String).
Bei anderen ungültigen Strings bleibt es bei der Exception.
Lässt sich schwer unittesten, da man dafür ein 32bit-System bräuchte. Auf 64bit lässt sich "0000-00-00" als int-timestamp darstellen und ist somit valide.
> rex_formatter: handle 0000-00-00

- redaxo/src/addons/be_style/install.php
Während des Updates, wurden die Vendorfiles von bootstrap-select und fontawesome aus dem alten Release kopiert, statt aus dem Temp-Ordner, aus dem das Update ausgeführt wird.
> be_style: Während Update korrekte Assets kopieren

- .github/workflows/static-analysis.yml
So können wir in der Action immer mal nachschauen/vergleichen, wie die type-coverage aktuell aussieht.
Refs #4052
> psalm action: type-coverage ausgeben

- .github/workflows/code-style.yml
- .github/workflows/rexlint.yml
- .github/workflows/unit-tests.yml
Mir ist aufgefallen, dass unsere 7.3-Builds immer recht langsam sind.
Vermutlich da sie nicht vorinstalliert sind auf ubuntu-latest: https://github.com/shivammathur/setup-php#github-hosted-runners
Mal schauen, wie es mit diesem PR ausschaut.
> run php 7.3 actions on ubuntu-18.04

- redaxo/src/core/lib/select.php
Ich wollte in einem *rex_form* mit dem Select-Feld Daten aus der zweiten Datenbank zur Auswahl stellen (_addSqlOptions_). Das klappte nicht, da keine DB-Id angegeben werden kann und daher DB=1 genutzt wird. Um das zu lösen habe ich bei den beiden Methoden zu SQL-Optionen den neuen zusätzlichen Parameter $db eingebaut.
```php
/**
* Fügt Optionen anhand der Übergeben SQL-Select-Abfrage hinzu.
*/
public function addSqlOptions($query,$db=1)
{
$sql = rex_sql::factory($db);
$this->addOptions($sql->getArray($query, [], PDO::FETCH_NUM));
}
/**
* Fügt Optionen anhand der Übergeben DBSQL-Select-Abfrage hinzu.
*/
public function addDBSqlOptions($query, $db=1)
{
$sql = rex_sql::factory($db);
$this->addOptions($sql->getDBArray($query, [], PDO::FETCH_NUM));
}
```
> addSqlOptions / addDBSqlOptions: DB-Auswahl ergänzt

- .tools/psalm/baseline-taint.xml
- redaxo/src/core/lib/view.php
Ansonsten wurden `rex_view::error` (etc) ausgaben verknüpft mit eingaben von völlig anderen stellen.
> rex_view messages: taint-specialize nutzen

- redaxo/src/addons/mediapool/lib/media.php
Weil wir eine ID eines Medium haben und der Fall wohl öfter gebraucht wird.
closes https://github.com/redaxo/redaxo/issues/1807
> rex_media::forId ergänzt

- redaxo/src/core/lib/util/pager.php
- redaxo/src/core/tests/util/pager_test.php
So kann die aktuelle Page, bzw. der aktuelle Cursor auch programmatisch gesetzt werden, und muss nicht zwingend aus `$_REQUEST` kommen.
> rex_pager: new methods setPage/setCursor

- redaxo/src/addons/mediapool/lib/service_media.php
- redaxo/src/addons/mediapool/pages/media.list.php
Die Methode hat @dergel letztens eingeführt. Dabei hat er nicht `rex_pager` genutzt, weil der bisher zwingend über `$_REQUEST` gesteuert wird.
Mit #4578 würde sich das aber ändern.
Und ich fände die Api hier dann mit `rex_pager` besser. Ein Parameter weniger, und simplerer Return-Type (da Gesamtzahl am pager-objekt zurückgeliefert wird).
> rex_media_service::getList: rex_pager nutzen

- composer.json
running into process timeouts..
```
$ composer rector
> rector process --ansi
415/2112 [=====>----------------------]  19%PHP Warning:  Use of undefined constant REX_MIN_PHP_VERSION - assumed 'REX_MIN_PHP_VERSION' (this will throw an Error in a future version of PHP) in phar://C:/xampp7.3/htdocs/redaxo/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassConstantReflection.php on line 48
Warning: Use of undefined constant REX_MIN_PHP_VERSION - assumed 'REX_MIN_PHP_VERSION' (this will throw an Error in a future version of PHP) in phar://C:/xampp7.3/htdocs/redaxo/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassConstantReflection.php on line 48
463/2112 [======>---------------------]  21%
[Symfony\Component\Process\Exception\ProcessTimedOutException]
The process "rector process …
```
> rector: disable process timeout

- .tools/psalm/baseline.xml
- redaxo/src/addons/backup/lang/de_de.lang
- redaxo/src/addons/backup/lang/en_gb.lang
- redaxo/src/addons/backup/lang/es_es.lang
- redaxo/src/addons/backup/lang/sv_se.lang
- redaxo/src/addons/backup/lib/cronjob.php
- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/backup/update.php
- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/lib/mediapool.php
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/mediapool/tests/mediapool_test.php
- redaxo/src/addons/project/boot.php
- redaxo/src/core/assets/standard.js
- redaxo/src/core/lib/util/string.php
- redaxo/src/core/pages/setup.step3.php
https://www.heise.de/news/Nichtrassistische-Sprache-Abschied-von-Blacklist-und-Whitelist-4784291.html
> Begriffe "blacklist"/"whitelist" vermeiden

- .tools/psalm/baseline.xml
- redaxo/src/core/layout/top.php
- redaxo/src/core/lib/be/navigation.php
- redaxo/src/core/lib/form/form.php
- redaxo/src/core/lib/login/api_user_impersonate.php
- redaxo/src/core/lib/rex.php
- redaxo/src/core/lib/view.php
- redaxo/src/core/pages/profile.php
Fügt eine neue Methode `rex::requireUser()` hinzu, die im Gegensatz zu `getUser` nicht nullable ist.
Sie wirft also eine Exception, wenn der User nicht existiert.
<details>
<summary>Ursprünglicher Beitrag</summary>
Ich bin am überlegen, ob wir hier mal `@psalm-ignore-nullable-return` verwenden sollen.
Aus der Doku (https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-ignore-nullable-return):
> This can be used to tell Psalm not to worry if a function/method returns null. It’s a bit of a hack, but occasionally useful for scenarios where you either have a very high confidence of a non-null value, or some other function guarantees a non-null value for that particular code path.
Das trifft an vielen Stellen bei uns zu, zum Beispiel den ganzen Backend-Pages. Dort ist man sowieso …
> Neue Methode rex::requireUser()

- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/package/run_update_script.php
Das Skript ist nützlich, um die `update.php` testen zu können.
Es kann auch verwendet werden, wenn man ein Package manuell geupdatet hat.
Man muss beim Aufruf allerdings die vorherige Version angeben. Diese wird für die Versionsvergleiche benötigt.
`redaxo/bin/console package:run-update-script my_package 1.3.0`
So wird also die `update.php` von `my_package` ausgeführt, so als käme man von der Version `1.3.0`.
> Neuer Command: package:run-update-script

- .github/workflows/visual-tests.yml
@schuer setzt seinen PR manchmal auf "ready to review", wartet die Screenshots ab, und dann wieder auf Draft.
Ich denke, wir sollten den Check hier ganz rausnehmen. Auch in Draft-PRs ist es praktisch, bereits die Screenshots zu sehen.
> Visual-Tests auch in Draft-PRs

- redaxo/src/core/backend.php
Floc im Backend per default deaktivieren. IMO sollte es im Frontend jeder Webseitenbetreiber selbst entscheiden
Closes https://github.com/redaxo/redaxo/issues/4640
> google FLoC optout per default aktivieren

- .idea/redaxo.iml
Hat sich doch als nachteilig rausgestellt.
> PhpStorm-Settings: baselines nicht mehr excluden

- composer.json
Wir müssen im bugfix-Branch die Version festsetzen wegen https://github.com/rectorphp/rector/issues/6322.
Im main-Branch können wir das wieder rausnehmen, wenn wir rector und psalm und weitere updaten.
> nikic/php-parser auf 4.10.4 festsetzen

- redaxo/src/core/lib/response.php
Was ja z.B. bei API-Calls vorkommen kann, sind falsch aufgebaute URLs. Das wird bei der Parameter-Überprüfung festgestellt und entsprechend reagiert. Da Server und Applikation wie konstruiert arbeiten, aber der Client ungültige Anfragedatens schickt, wäre 400 Bad Request eine passende Antwort. (siehe https://de.wikipedia.org/wiki/HTTP-Statuscode).
Hierfür ist keine Konstante in rex_response vorhanden, die hiermit vorgeschlagen wird.
> HTTP_BAD_REQUEST ergänzt

- .github/workflows/code-style.yml
- redaxo/src/core/lib/csrf_token.php
utilize multi core capabilities. Using 3 processes at a time, because github action VMs have 2 cpus, but cs-fixer is also doing some IO and therefore its likely processes are blocked for IO.
In CI php-cs-fixer cannot benefit from the cs-fixer-cache, therefore running things in parallel results in a great perf boost.
Refs https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5390
> php-cs-fixer: utilize multiple processors

- redaxo/src/addons/mediapool/lib/var_media.php
- redaxo/src/addons/mediapool/lib/var_medialist.php
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/metainfo/lib/input/linkbutton.php
- redaxo/src/addons/metainfo/lib/input/linklistbutton.php
- redaxo/src/addons/metainfo/lib/input/mediabutton.php
- redaxo/src/addons/metainfo/lib/input/medialistbutton.php
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/structure/lib/linkmap/var_link.php
- redaxo/src/addons/structure/lib/linkmap/var_linklist.php
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/pages/linkmap.php
fixes #4610
Aktuell nutzen die Slices und die Metainfos das gleiche ID-Schema und zählen beide eigenständig hoch.
YForm hat bereits angepasst, dass dort die ID einen zusätzlichen Präfix enthält.
Metainfo macht es nun genauso und fügt `METAINFO_` der ID hinzu.
Allerdings musste ich die Widgets selbst auch noch ein bisschen dafür anpassen, damit es überall korrekt funktioniert.
> Metainfo: Widget-IDs mit eigenem Präfix

- redaxo/src/core/lib/util/socket/socket_proxy.php
use tls1.2 instead of sslv3 to support proxies with higher
security defaults and also improve security
> use modern crypto for socket connections

- redaxo/src/addons/structure/lib/linkmap/var_link.php
fixes #4730 
Nicht die generierte URL darf in den Cache, sondern der PHP-Code zum Abruf der URL.
Sonst hat die URL die falsche Sprache, wenn der Cache unter anderer Sprache generiert wird (zum Beispiel beim Einbinden der Sprachversion in eine andere Sprache).
> REX_LINK[id=1 output=url]: URL nicht in Cache

- .tools/psalm/baseline-taint.xml
- redaxo/src/addons/backup/pages/export.php
- redaxo/src/core/functions/function_rex_escape.php
- redaxo/src/core/lib/error_handler.php
- redaxo/src/core/lib/util/i18n.php
Seit https://github.com/vimeo/psalm/commit/47bf5ed56797e5605eeb656bd7ec98bb87650d8f gibt es neu `has_quotes`, was wir bisher nicht berücksichtigt haben. Deswegen hatten wir sehr viele false-positive in der baseline.
> taint analyse: has_quotes berücksichtigen

- .github/tests-visual/visual-record.js
```
(node:2091) UnhandledPromiseRejectionWarning: TypeError: error.replace is not a function
at /home/runner/work/redaxo/redaxo/.github/tests-visual/visual-record.js:310:15
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2091) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2091) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are …
```
> visual-tests: fix error handling

- .github/tests-visual/visual-record.js
vorher
`BROWSER-CONSOLE: Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
nachher
`BROWSER-CONSOLE: "http://localhost:8000/__clockwork/latest" Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
ursprung https://github.com/redaxo/redaxo/runs/4056412059?check_suite_focus=true#step:14:112
> visual-tests: show origin for failed ajax requests

- phpstan.neon.dist
to ease migration to phpstan 1.0
> phpstan: don't use excludes_analyse deprecated config

- redaxo/src/addons/metainfo/lib/handler/category_handler.php
- redaxo/src/addons/metainfo/lib/handler/clang_handler.php
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/metainfo/lib/handler/media_handler.php
fixes #1661: Ich habe in den letzten Jahren mehrfach angesetzt, um das sauber zu fixen, aber bin immer zu keiner schönen Lösung gekommen, bzw. es wäre mir zu viel Umbau im metainfo-Addon. Deshalb nun eine bisschen Quick&Dirty-Lösung. Gibt immer noch Dinge, die ich nicht optimal finde, aber so wird das eigentliche Ticket zumindest gelöst (kein doppeltes Speichern mehr, und keine doppelt ausgeführten Callbacks).
fixes #1660: Einerseits hängt sich das metainfo nun EARLY and die EPs (`MEDIA_UPDATED` etc.). So wird dafür gesorgt, dass wenn andere Extensions sich an die EPs hängen, die Metainfos auch bereits gespeichert wurden. Des Weiteren spielte hier auch das doppelte Speichern von oben noch mit rein. Also selbst wenn man sich selbst an `MEDIA_UPDATED` mit LATE registriert hat, dann waren da …
> metainfo: Ablaufoptimierungen

- .tools/psalm/baseline-taint.xml
- .tools/psalm/baseline.xml
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/lib/sql/util.php
- redaxo/src/core/lib/util/i18n.php
Ich schlage vor, alle Werte aus der DB als unsicher zu markieren (`@psalm-taint-source input`).
Denn wir können ja nicht die Verknüpfung ziehen zu den Stellen, wo in die entsprechenden Felder geschrieben wird.
Als Beispiel: Durch prepared Statements verhindert man SQL Injections. Aber es wird ja nicht verhindert, dass am Ende SQL-Syntax in der DB landet. Daher beim Auslesen wieder als unsicheren Wert betrachten, der wieder escaped werden muss.
Ich habe bereits Folge-PRs in Vorbereitung mit vielen Fixes, aber wollte diesen PR nicht zu groß werden lassen.
> Taint-Analyse: Werte aus DB als unsicher betrachten

- .tools/phpstan/baseline.neon
- phpstan.neon.dist
Wenn wir einen Array-Typ für einen Parameter genauer spezifizieren, dann wollen wir durchaus in der Methode trotzdem per isset() etc prüfen, ob die Keys existieren.
Daher mein Vorschlag, diesen Error-Typ generell zu unterdrücken.
> PHPStan: "Offset always exists" generell unterdrücken

- redaxo/src/addons/debug/boot.php
Wenn man REDAXO in einem custom cli-Skript lädt, also nicht über unsere rex-console, dann wirft Debug eine Notice:
> Notice: Undefined index: REQUEST_URI in redaxo/src/addons/debug/boot.php on line 154
Daher mein Vorschlag, allgemein bei cli in den if-zweig zu gehen. Und die Extension greift dann halt, wenn rex-console, ansonsten nicht.
Aufgefallen war es mir im Release-Skript (.tools/bin/release).
> Debug-Addon: Notice vermeiden in custom cli-Skripten

- redaxo/src/addons/structure/plugins/content/lib/content_service.php
Bei irgendeinem Refactoring muss das passiert sein, dass der Parameter `$clang` nun gleich hieß wie die Schleifenvariable.
Dadurch hatte der Parameter keinen Effekt mehr, es wurden immer die Inhalte für alle Sprachen generiert.
> Doppelte Variable $clang

- redaxo/src/core/lib/util/socket/socket.php
- redaxo/src/core/tests/util/socket_test.php
um Optionen wie
`$socket->setOptions(['ssl' => ['verify_peer' => false, 'verify_peer_name' => false ] ]);`
zu erlauben
> Socket Aufruf von fsockopen auf stream_context_create geändert

- redaxo/src/addons/structure/plugins/content/lib/cache_template.php
- redaxo/src/addons/structure/plugins/content/lib/content_service.php
@schuer war es auf redaxo.org aufgefallen, dass Slice-Änderungen sich teils nicht direkt ausgewirkt haben.
Neu wird nun bei unseren Cache-Dateien im PHP-Format nach jeder Neugenerierung der Opcache für die jeweilige Datei invalidiert.
> PHP-Cache-Dateien: Bei Neugenerierung Opcache invalidieren

- redaxo/src/addons/be_style/assets/javascripts/main.js
- redaxo/src/addons/phpmailer/pages/config.php
- redaxo/src/core/assets/standard.js
- Entfernen der Initialisierung im PHPMailer
> tooltips überall nutzbar machen

- redaxo/src/core/layout/top.php
- redaxo/src/core/lib/util/i18n.php
fixes #4898
Seitdem wir mit der intl-Extension für Datumsformatierung arbeiten, setzt `rex_i18n::setLocale` auch die Default-Locale in der `Locale`-Klasse der intl-Extension.
Nach diesem PR wird die Zeile nicht ausgeführt bei aktivem Setup, wenn die Klasse nicht existiert, damit man im Setup bis zum eigentlichen Extensions-Check kommt.
Konnte es leider gerade nicht wirklich testen, da ich nicht so leicht bei mir die intl-Extension deaktivieren kann.
/cc @eaCe
> intl-Extension nicht frühzeitig im Setup nutzen

- redaxo/src/addons/install/lib/api/api_core_update.php
Dieses Issue löst das Problem, was einige in Slack gemeldet haben.
Nach dem Core-Update, aber noch vor dem Reload, loggen wir über `rex_logger` eine Erfolgsmeldung.
Wenn die `rex_logger`-Klasse bis dahin aber noch nicht geladen wurde, wird sie dort bereits aus dem neuen Core geladen, obwohl der Request noch im alten Core läuft. So kommt es zu einer inkompatiblen Klassenkombination.
Daher lade ich nun vor dem Update bereits die Klasse.
Das Problem trat zum Beispiel nicht auf, wenn das debug-Addon aktiv ist, da dann die rex_logger-Klasse immer geladen wird, da das Addon dafür eine factory-class registriert.
Ich konnte das Problem nachstellen und mit diesem PR nicht mehr feststellen. Somit getestet.
> Core-Update: Logger-Klasse vor Update laden

- redaxo/src/addons/install/lang/de_de.lang
- redaxo/src/addons/install/lang/en_gb.lang
- redaxo/src/addons/install/lib/api/api_core_update.php
fixes #4652
Hiermit versuche ich obiges Issue zu lösen.
Einerseits versuche ich vorab die Schreibrechte etwas mehr zu prüfen. 
Andererseits beim Update der Core-Addons nenne ich den alten Ordner erst um (in der Hoffnung, dass das zumindest klappt), und versuche dann den Tempordner zu löschen. Falls letzteres mal nicht klappt, weil irgendwelche Unterordner/dateien nicht gelöscht werden konnten, wäre das nicht so dramatisch. Man hätte dann halt den temp-Ordner da noch liegen.
Abbrechen können wir da nicht mehr, da Core (und ggf. manche Addons) bereits ausgetauscht wurden.
(Das ist noch nicht die Lösung für das heute in Slack besprochene Problem. Aber mir war es dort bei @skerbis als Nebenproblem aufgefallen, dass das debug-Addon bei ihm nicht richtig aktualisiert werden konnte.)
> Core-Update: Besserer Umgang mit fehlenden Schreibrechten

- redaxo/src/addons/install/CHANGELOG.md
- redaxo/src/addons/install/package.yml
Wenn #4921 und #4922 gemerged sind, werde ich ein Einzel-Update für den Installer rausbringen.
Und beim Core-Update auf 5.13 werde ich dann den Installer 2.9.2 erfordern.
> Release install 2.9.2

- redaxo/src/core/update.php
Die Logik hatten wir so [schon mal in der `update.php`](https://github.com/redaxo/redaxo/blob/5.6.5/redaxo/src/core/update.php#L21-L26) (mit anderen Versionsnummern), sie war aber irgendwann entfallen, da die damalige installer-version irgendwann schon durch die min-rex-version implizit erforderlich war.
> Require install addon 2.9.2

- redaxo/src/core/lib/login/backend_login.php
Wenn man die Eingeloggt-bleiben-Funktion nutzt, wird ein Cookiekey erzeugt und im user-datensatz in der DB abgelegt.
* Wenn man sich dann an einem anderen Rechner anmeldet, und auch dort "Eingeloggt bleiben" aktiviert, wird ein neuer Cookiekey in der DB gespeichert. Der alte ist damit invalide, an dem anderen Rechner bleibt man also nicht eingeloggt.
- Das finde ich nicht sinnvoll, man sollte die Funktion auch an mehreren Rechnern nutzen können.
- Daher wird nun nur noch ein neuer Cookiekey erzeugt, wenn noch keiner existiert, ansonten wird der bisherige weiterverwendet.
* Bei einem Loginfehlversuch wurde der Cookiekey geleert.
- Auch das finde ich nicht sinnvoll. Nur weil man sich an einem Rechner vertut mit dem Login, sollte nicht an den anderen Rechnern die Eingeloggt-bleiben-Session …
> Eingeloggt bleiben: Cookie nicht unnötig invalidieren

- .tools/psalm/baseline.xml
- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/lib/login/login.php
- redaxo/src/core/pages/profile.php
- redaxo/src/core/update.php
closes #4936
Wenn man das Passwort eines Users ändert, dann werden alle Sessions des Users invalidiert.
Dies passiert, indem der Passwort-Hash mit in die Session gelegt wird. So kann eine Änderung erkannt werden.
Wenn man sein eigenes Passwort ändert, egal ob über Profil oder über Benutzerverwaltung, dann wird die eigene gerade verwendete Session gerettet, indem der neue Passwort-Hash direkt in die Session gesetzt wird.
Auch die Eingeloggt-bleiben-Cookies werden invalidiert, indem das Feld in der DB geleert wird.
> Passwortänderung: Sessions beenden

- redaxo/src/addons/media_manager/pages/types.php
- redaxo/src/addons/metainfo/pages/field.php
Es gab unter den Core-AddOns noch zwei Links ohne Klasse `.rex-link-expanded`, die die Klickfläche vergrößert. Diese habe ich ergänzt.
> UI: Weitere Hinzufügen-Links vergrößert

- redaxo/src/addons/mediapool/lib/media.php
- redaxo/src/addons/structure/lib/structure_element.php
- redaxo/src/core/lib/clang/clang.php
Als Vorbereitung für PHP 8.2: https://wiki.php.net/rfc/deprecate_dynamic_properties
> PHP 8.2: Attribut AllowDynamicProperties verwenden

- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/mediapool/pages/sync.php
Der Fehler kam mit https://github.com/redaxo/redaxo/commit/32220c9e97f56966c320304ba796385cd9294a5c.
> MP: Sync der ersten Datei aus der Liste funktioniert teils nicht

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/lib/util/finder.php
- redaxo/src/core/lib/util/log_file.php
Das ist seit PHP 8.1 notwendig.
Die zugehörigen Deprecated-Meldungen sehen wir nicht, weil wir die [aktuell unterdrücken im Autoloader](https://github.com/redaxo/redaxo/blob/722888500317dcc01e0fee99ab2453e8308e4117/redaxo/src/core/lib/autoload.php#L109).
Das werde ich eventuell auch ändern, hat aber auch Auswirkungen auf Addons. Muss ich nochmal schauen.
Hier zunächst daher nur die Attribute.
> ReturnTypeWillChange-Attribut nutzen

- redaxo/src/core/lib/console/setup/run.php
> Cli-Setup: Warnung, dass Checks nur die Cli-Umgebung prüfen

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_select_test.php
Somit können Params auch an Stellen verwendet werden, wo SQL einen Integer erwartet, wie bei `LIMIT :limit`.
fixes #1419
> rex_sql: Params mit korrektem Typ binden

- redaxo/src/addons/structure/plugins/content/boot.php
closes #3916
Der PR macht zwei Dinge:
* Die Fehlermeldung im Frontend sehen nur eingeloggte Benutzer. Andere Seitenbesucher sollten keine Fehlermeldungen dieser Art und auch keinen Link zum Backend sehen. Daher für die eine normale Exception, die ins Log geht, und der Benutzer sieht dann die normale Fehlerseite
* Für eingeloggte Benutzer habe ich die Meldung optimiert. Fand ich nicht so leicht. Der Regelfall ist nach dem Setup, wenn noch gar kein Artikel existiert. Theoretisch kann der Fall aber auch in anderen Konstellationen auftreten. Ist unwahrscheinlich  (aber nicht ausgeschlossen), das System versucht die vorher schon zu verhindern.
> Fehler optimiert, wenn kein Artikel vorhanden oder Artikel nicht gefunden

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/login/backend_login.php
Es gab zwei Probleme:
* Es wurde `sameSite=Strict` verwendet. Das führt zumindest im Safari dazu, dass bei Browser-Neustart der Cookie gelöscht wird. Wundere mich warum, aber man findet dazu auch mehrere Berichte, wie [hier](https://stackoverflow.com/questions/68309242/samesite-strict-cookie-not-sent-in-safari-when-opening-a-new-tab). Laut einem Kommentar dort betrifft es auch Chrome. Neu nehme ich nun die gleiche samesite-Einstellung wie für den Session-Cookie (default Lax).
* Nach einem Login über den Cookie, wurde fälschlich eine vermeintliche Passwortänderung "bemerkt" und deswegen wurde man direkt wieder ausgeloggt
> "Eingeloggt bleiben" repariert

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/packages/package.php
closes #2876
Problem war vor allem, dass die Page-Pfade zunächst als Sub-Pfade zum Addon probiert wurden, und wenn dort nicht vorhanden, als globale, bzw. relative Pfade. Somit bekam man letztlich eine Fehlermeldung nur mit dem relativen Pfad (siehe Issue), obwohl meist der zuerst geprüfte Subpath eher der "richtigere" gewesen wäre.
Daher nun mit eigener Fehlermeldung. Schaut nun so aus:
> Fehlende Package-Page: Fehlermeldung optimiert

- phpstan.neon.dist
nicht mehr nötig seit phpstan 1.0
bleeding edge brauch man nur, wenn man unstabile features aktivieren will.. aktuell gibts aber keine relevanten
> phpstan: remove bleeding edge mode

- .tools/psalm/baseline.xml
- redaxo/src/addons/metainfo/lib/handler/media_handler.php
Should fix
```
------ ------------------------------------------------------------------------------------------
Line   addons\metainfo\lib\handler\media_handler.php
------ ------------------------------------------------------------------------------------------
191    Unresolvable Query: Cannot simulate parameter value for type: mixed.
💡 Make sure all variables involved have a non-mixed type and array-types are specified.
------ ------------------------------------------------------------------------------------------
```
refs https://github.com/redaxo/redaxo/pull/4984#issuecomment-1017767525
> Use prepared Statement in media_handler

- redaxo/src/addons/phpmailer/lib/mailer.php
sollte aus PHPMailer-Config kommen. 
E-Mails können nicht versendet werden, wenn hier ein Absender steht, der nicht berechtigt ist E-Mails unter dem konfigurierten Postfach oder der Domain zu versenden. 
https://github.com/redaxo/redaxo/blob/c9e667d630870942dfa5568bf7be56c8a89661db/redaxo/src/addons/phpmailer/lib/mailer.php#L298-L299
> PHPMailer :: Absender der Errormail

- .tools/psalm/baseline.xml
- redaxo/src/addons/metainfo/functions/function_metainfo.php
should fix
```
------ ------------------------------------------------------------------------------------------------------
Line   addons\metainfo\functions\function_metainfo.php
------ ------------------------------------------------------------------------------------------------------
83     Unresolvable Query: Cannot simulate parameter value for type: mixed.
💡 Make sure all variables involved have a non-mixed type and array-types are specified.
93     Unresolvable Query: Cannot simulate parameter value for type: mixed~0|0.0|''|'0'|array{}|false|null.
💡 Make sure all variables involved have a non-mixed type and array-types are specified.
101    Unresolvable Query: Cannot simulate parameter value for type: mixed.
💡 Make sure all variables involved have a non-mixed type and array-types …
```
> added phpdocs

- redaxo/src/core/lib/util/version.php
fixes #5038
`exec` ist auf shared hostings öfters über die php.ini deaktiviert.
> rex_version: Abfangen, wenn exec() nicht zur Verfügung steht

- redaxo/src/addons/mediapool/pages/media.detail.php
SVG wurden nicht angezeigt und mit Breite 0 versehen.
> Mediapool details size fix: disable width, when $rfwidth 0

- redaxo/src/addons/structure/plugins/content/lib/var_value.php
Added a check in rex_var_value to see if the value isn't null, if it is null, PHP 8.1 throws deprecation warnings;
> rex_var_value deprecation warnings in PHP 8.1

- redaxo/src/core/lib/context.php
Um es im Frontend besser verwenden zu können
```php
$context = rex_context::fromGet();
$context->setParam('foo', 'bar');
$context->removeParam('foobar');
echo rex_getUrl('', '', $context->getParams());
```
> rex_context: Neue zusätzliche Methoden

- redaxo/src/core/lib/be/page.php
Ermöglicht es, den Titel einer Seite z.B. per EP zu ändern, um z.B. Addons projektbezogen aussagekräftige Titel zu geben.
```
rex_extension::register('PAGES_PREPARED', static function () {
rex_be_controller::getPageObject('page')->setTitle('Custom Page Title'));
});
```
> Neue Methode zum ändern eines BE-Seiten-Titels

- redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Gibt sonst immer null zurück, weil falscher Listentyp.
> rex_article_slice: fix getMediaListArray

- redaxo/src/core/lib/var/var.php
fixes #5100
Alternative wäre, alle Stellen zu prüfen/anzupassen, wo `quote()` aufgerufen wird.
Denke aber es ist ok/gut, wenn die Methode selbst `null` auch unterstützt, da es den Aufruf-Code einfacher hält.
> rex_var::quote: support null value

- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/packages/package.php
In `rex_package::clearCache` wird nun auch der Properties-Cache des Addons geleert.
Außerdem wird die Methode beim Löschen von Addons aufgerufen.
closes #5060
> Package-Cache besser löschen

- redaxo/src/core/lib/form/form_base.php
#5061
(betraf nicht nur rex_config_form, sondern auch rex_form.)
@alxndr-w Das Fieldset-Problem sollte hiermit behoben sein.
@tbaddade Kannst du bestätigen, dass damit dein Problem auch weg ist?
> rex_form: Fieldset mit eckigen Klammern unterstützen

- redaxo/src/addons/debug/boot.php
- redaxo/src/addons/debug/lib/debug_clockwork.php
We cannot rely on `rex::isDebugMode()` because it is always true on the console. So we have to check the config file itself.
fixes #5073
> debug: check core config file to decide if clockwork should be turned on

- redaxo/src/core/lib/request.php
```
Exception trace:
at /var/www/vhosts/klxm.de/httpdocs/redaxo/src/core/lib/rex.php:348
rex::getRequest() at /var/www/vhosts/klxm.de/httpdocs/redaxo/src/core/lib/request.php:255
rex_request::isPJAXRequest() at /var/www/vhosts/klxm.de/httpdocs/redaxo/src/addons/minibar/boot.php:61
require() at /var/www/vhosts/klxm.de/httpdocs/redaxo/src/core/lib/packages/package.php:285
rex_package->includeFile() at /var/www/vhosts/klxm.de/httpdocs/redaxo/src/core/lib/packages/package.php:421
rex_package->boot() at /var/www/vhosts/klxm.de/httpdocs/redaxo/src/core/lib/console/application.php:93
rex_console_application->loadPackages() at /var/www/vhosts/klxm.de/httpdocs/redaxo/src/core/lib/console/application.php:48
rex_console_application->doRunCommand() at …
```
> request: prevent exception when invoked from CLI

- .tools/phpstan/baseline.neon
- phpstan.neon.dist
- redaxo/src/core/default.config.yml
- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/lib/login/login_policy.php
- redaxo/src/core/schemas/config.json
- redaxo/src/core/tests/login/backend_login_test.php
followup to https://github.com/redaxo/redaxo/pull/5197
refs https://github.com/redaxo/redaxo/issues/5194
Verhalten nach dem PR:
- man hat `login_tries_until_delay` versuche, ohne verzögerung
- nach `login_tries_until_delay` versuchen, kommt bei jedem weiteren versuch ein `relogin_delay` sodass man nicht mehr so schnell weitere passworte ausprobieren kann
- nach `login_tries_until_blocked` versuchen, kann man sich mit einem account nicht mehr einloggen
> simplify `rex_login_policy`

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- phpstan.neon.dist
- redaxo/src/addons/structure/plugins/history/lib/history_login.php
- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/lib/login/login.php
- redaxo/src/core/lib/login/password_policy.php
- redaxo/src/core/lib/login/user.php
- redaxo/src/core/lib/sql/sql.php
New feature for PHP 8.2: [Redact parameters in back traces](https://stitcher.io/blog/new-in-php-82#redact-parameters-in-back-traces-rfc)
> Hide sensitive information with SensitiveParameter attribute

- .tools/psalm/baseline.xml
- redaxo/src/addons/debug/boot.php
closes https://github.com/redaxo/redaxo/issues/5201
ich hab wenig erfahrung mit dem debug addon. nach ein bissl try&error bin ich auf diesem gelandet, inspiriert von 
https://github.com/redaxo/redaxo/blob/6f133c93d21125b58afe2f632790b38bc63ed6a3/redaxo/src/addons/debug/lib/debug_clockwork.php#L44-L55
ob das wirklich passt, kann ich nicht sagen.
es behebt das problem für mich wenn debug addon im unterordner läuft:
> fix debug addon when redaxo running in subfolder

- redaxo/src/core/backend.php
- redaxo/src/core/lib/be/controller.php
Aktuell wird die Abfrage bei jedem Backend-Aufruf gemacht. 
Neu wird nur noch innerhalb der Log-Page geprüft, ob das Slow Query Log vorhanden ist.
> Slow Query Log: DB-Abfragen vermeiden

- .tools/phpstan/baseline.neon
- redaxo/src/core/lib/sql/sql.php
refs https://github.com/redaxo/redaxo/pull/5278#discussion_r934194028
see https://phpstan.org/blog/remembering-and-forgetting-returned-values
> mark `rex_sql::getRows()` as impure

- redaxo/src/addons/structure/plugins/version/boot.php
Dadurch kann man das Verhalten von #5294 über den vorhandenen EP ändern:
```php
rex_extension::register(rex_extension_point_art_content_updated::NAME, function (rex_extension_point_art_content_updated $ep) {
if ('work_to_live' === $ep->getAction()) {
rex_article_revision::setSessionArticleRevision($ep->getArticle()->getId(), rex_article_revision::WORK);
}
});
```
closes  #5294
> version-Plugin: bei work_to_live neue Revision vor EP setzen

- redaxo/src/addons/phpmailer/lib/mailer.php
fixes: https://github.com/redaxo/redaxo/issues/5319
Mails werden auch bei nicht erfolgreichem Versand archiviert. Gerade bei längerem Ausfall eines Mail-Servers kann dies helfen. Die Archiv-Funktion sollte aber auch nur dafür kommuniziert werden. Das werde ich entsprechend dokumentieren in einem weiteren PR. Erkennbar sind die Mails am Prefix not_sent im Archiv-Ordner.
> PHPMailer: archiving not sent mails with prefix not_sent

- redaxo/src/core/lib/rex.php
required for https://github.com/FriendsOfREDAXO/rexstan/issues/143
context https://staabm.github.io/2022/07/23/phpstan-dba-inference-placeholder.html
> added `@phpstandba-inference-placeholder` to `rex::getTablePrefix()`

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
Mir ist aufgefallen, dass in DBAL auch der Backslash noch escaped wird: https://github.com/doctrine/dbal/blob/d3530a4d6e857942d87b730b2f9255bf72fc0245/src/Platforms/AbstractPlatform.php#L4426-L4433
Das leuchtet auch ein. Beispiel: Man möchte explizit nach `foo\_bar` suchen (also wirklich ein Backslash und ein Unterstrich). Aktuell würde aus `escapeLikeWildcards` dann `foo\\_bar` rauskommen, also ein escapeter Backslash und ein Unterstrich-Wildcard-Zeichen. Daher müssen auch Backslashes escaped werden, damit dann `foo\\\_bar` rauskommt (ein escapter Backslash und ein escapter Unterstrich).
Ich denke aber, dass es nicht wirklich ein Security-Problem ist. Also es waren dadurch keine SQL-Injections oder so möglich, denn `escapeLikeWildcards` ist und bleibt ja eine unsichere Methode, die …
> escapeLikeWildcards: Backslash auch escapen

- .tools/psalm/baseline-taint.xml
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/pages/field.php
die methode existiert seit redaxo 5.9, siehe https://github.com/redaxo/redaxo/pull/3242
metainfo erfordert aktuell `^5.13.0`, daher good to go
> use `rex_sql::escapeLikeWildcards()`

- redaxo/src/core/pages/profile.sessions.php
Wir sollten nicht das deutsche Format erzwingen, sondern das Format sollte entsprechend der Sprache gewählt werden. Daher intlDateTime.
> Session-Liste: intlDateTime nutzen

- redaxo/src/core/fragments/core/form/search.php
Man kann das Suchfeld auch in anderen Addons verwenden ohne direkt per JavaScript den Output zu verändern. Bei Aufruf der Backend-Seite (refresh) sollte man den Suchbegriff auch wieder mit dem abgesendeten Suchbegriff vorbelegen können.
> Suchfeld mit Value vorbelegen

- redaxo/src/core/lib/util/dir.php
- redaxo/src/core/lib/util/file.php
See https://psalm.dev/docs/annotating_code/adding_assertions/
Grundidee ist: wenn file IO operationen true liefern (und somit gesagt haben, dass der pfad im filesystem existiert), muss der übergebene pfad auch `non-empty-string` gewesen sein. daher wird im aufrufenden scope der type des parameters durch den aufruf der IO operation präzisiert.
Requires phpstan 1.9.x
> added rex_file/dir assertions

- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/lib/media_manager.php
- redaxo/src/addons/media_manager/package.yml
Seit #5415 bekam man bei dem Weg über `rex_media_manager::create` teils die Originalgrößen der Bilder.
> Fix rex_media_manager::create

- .tools/phpstan/baseline.neon
- redaxo/src/addons/media_manager/tests/media_manager_test.php
- redaxo/src/addons/structure/plugins/content/tests/article_content_base_test.php
- redaxo/src/addons/structure/plugins/content/tests/article_content_test.php
- redaxo/src/addons/structure/tests/article_test.php
- redaxo/src/addons/structure/tests/category_test.php
- redaxo/src/core/tests/console/command_test.php
- redaxo/src/core/tests/list_test.php
- redaxo/src/core/tests/login/password_policy_test.php
- redaxo/src/core/tests/sql/sql_select_test.php
- redaxo/src/core/tests/util/socket_test.php
- redaxo/src/core/tests/util/stream_test.php
Da seit PHP 8.1 nicht mehr notwendig.
> reflection: setAccessible nicht mehr aufrufen

- redaxo/src/core/lib/setup/setup.php
only for mariadb we have new numbers.. every else unchanged
https://www.php.net/supported-versions.php
https://mariadb.org/about/#maintenance-policy
https://www.mysql.com/support/supportedplatforms/database.html
> update end-of-life warning dates

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- redaxo/src/addons/mediapool/lib/service_media.php
- redaxo/src/core/lib/extension.php
- redaxo/src/core/lib/util/editor.php
damit in folgendem code kein error entsteht
```php
$name = null;
$name = rex_extension::registerPoint(new rex_extension_point(
'NEW_NAME',
$name,
[
'id' => $id,
'output' => $output,
]
));
if (null !== $name) { // Strict comparison using !== between null and null will always evaluate to false.
return $name;
}
```
siehe https://github.com/FriendsOfREDAXO/rexstan/issues/282
> fix `rex_extension::registerPoint` return type

- redaxo/src/core/.phpstorm.meta.php
- redaxo/src/core/lib/sql/foreign_key.php
- redaxo/src/core/lib/sql/schema_dumper.php
"NO ACTION" fehlte als in MySQL mögliche foreign key constraint action in der  rex_sql_foreign_key Klasse
> add "NO ACTION" as Constant in rex_sql_foreign_key

- redaxo/src/addons/install/lib/package/package_update.php
- redaxo/src/addons/install/package.yml
fixes #5145
Es funktioniert nun, wenn man in der `update.php` z.b. das notiert:
```php
rex_dir::delete(rex_path::plugin($addon, $plugin);
```
> Addon-Update: Plugin-Entfernung ermöglichen

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/util/string.php
`urlencode(): Passing null to parameter #1 ($string) of type string is deprecated | src\core\lib\util\string.php | 179`
aktuell diese Zeile:
https://github.com/redaxo/redaxo/blob/main/redaxo/src/core/lib/util/string.php#L189
aufgetreten bei einem ydeploy::diff Lauf mit PHP 8.1
> prevent warning in rex_string::buildQuery()

- rector.php
- redaxo/src/core/boot.php
- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/lib/login/login.php
- redaxo/src/core/lib/login/user_session.php
Nach einem Frontend-Login sollte die Session-ID regeneriert werden.
Ab 5.15 haben wir jedoch die user_session-Tabelle mit den Backend-Sessions. 
Daher würde man bei einem Frontend-Login dann im Backend ausgeloggt werden. Das ist unschön.
Daher muss das Backend die Session-ID in der Tabelle aktualisieren, wenn durch ein Frontend-Login die Session-ID neu generiert wird.
Umgekehrt gilt das Gleiche. Ein Frontend-Login-System muss darauf reagieren können, wenn wegen des Backend-Logins die Session-ID neu generiert wurde.
Daher der neue EP `SESSION_REGENERATED`.
Mir gefällt das ganze Konstrukt hier nicht so wirklich. Aber mir ist keine simplere Lösung eingefallen.
closes #5551
> Neuer EP `SESSION_REGENERATED`

- redaxo/src/core/pages/system.log.redaxo.php
Der Core gibt nirgends solche Meldungen aus, aber wenn man selbst welcher per 
`rex_logger:.factory()->debug('...');`
ausgibt, dann erschienen die rot (Error) im Log.
Neu erscheinen sie ohne eigene Hintergrundfarbe, also normale Tabellen-Hintergrundfarbe.
Sie haben aber eine eigene Klasse `rex-state-debug`, worüber sie gestylt werden könnten.
> Syslog: Debug-Meldungen nicht in rot

- redaxo/src/core/functions/function_rex_escape.php
- redaxo/src/core/tests/functions_test.php
`$escaped = rex_escape($object);` 
Das übergebene Objekt sollte nicht angepasst werden, sondern es sollte ein neues escapetes zurückgeliefert werden.
Betrachte ich als Bug.
> rex_escape: bei stdClass neues Objekt erzeugen

- .tools/psalm/baseline.xml
- redaxo/src/addons/backup/pages/export.php
- redaxo/src/addons/backup/pages/index.php
- redaxo/src/addons/cronjob/lib/manager.php
- redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/phpmailer/lib/mailer.php
- redaxo/src/addons/structure/lib/service_article.php
- redaxo/src/addons/structure/plugins/content/tests/article_slice_test.php
- redaxo/src/core/fragments/core/page/section.php
- redaxo/src/core/functions/function_rex_escape.php
- redaxo/src/core/lib/login/login.php
- redaxo/src/core/lib/response.php
- redaxo/src/core/lib/util/logger.php
- redaxo/src/core/lib/util/timer.php
Bei 4-stelligen Zahlen habe ich es erstmal weggelassen. Da bin ich mir nicht sicher, ob das überhaupt eine Verbesserung ist, also `1_024` statt `1024`. Insbesondere auch bei Jahreszahlen.. `2_005`.
> Numeric Literal Separator nutzen

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- redaxo/src/addons/mediapool/lib/service_media.php
- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
- redaxo/src/core/lib/extension.php
Dies ist ein Revert von https://github.com/redaxo/redaxo/pull/5455
> rex_extension::registerPoint: Conditional Return-Type wieder entfernt

- redaxo/src/core/pages/system.log.redaxo.php
Zwischen Variablen-Deklaration und -Verwendung wurde eine gleichnamige Variable `$url` für die Editor-URL verwendet.
> System-Log: URL-Ausgabe korrigiert

- redaxo/src/core/lib/console/config/get.php
- redaxo/src/core/lib/console/config/set.php
- redaxo/src/core/lib/console/db/connection_options.php
Ähnlich wie `db:set-connection` sollten auch die drei Commands `config:get`, `config:set` und `db:connection-options` immer ausführbar sein, auch wenn die aktuelle DB-Verbindung ungültig ist, oder die DB leer ist.
Gibt auch keine Notwendigkeit, bei den Commands die Addons zu laden.
> Commands config:get/set und db:connection-options als Standalone-Commands

- redaxo/src/core/assets/webauthn.js
`rex:ready` ist im Chrome schon gelaufen, wenn der Code in der webauthn.js erreicht wird.
Daher nun ein Workaround.
> Passkeys funktionierten in Chrome nicht

- redaxo/src/core/lib/fragment.php
refs https://github.com/redaxo/redaxo/issues/5336
---
ich denke es macht sinn in diesem fall eine `InvalidArgumentException` zu werfen.
auch sollten wir damit den false-positive im phpstorm beheben
> Prevent error in phpstorm, when calling `rex_fragment->parse()`

- .tools/psalm/baseline.xml
- redaxo/src/addons/structure/plugins/history/lib/history_login.php
- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/lib/login/backend_password_policy.php
- redaxo/src/core/lib/login/login.php
- redaxo/src/core/lib/login/password_policy.php
- redaxo/src/core/lib/login/user.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/lib/util/socket/socket.php
und einheitlich ohne Backslash vorne
> SensitiveParemter-Attribute an weiteren Stellen nutzen

- redaxo/src/core/lib/Fragment/Component/Alert.php
- redaxo/src/core/lib/Fragment/Component/Alert/Error.php
- redaxo/src/core/lib/Fragment/Component/Alert/Info.php
- redaxo/src/core/lib/Fragment/Component/Alert/Success.php
- redaxo/src/core/lib/Fragment/Component/Alert/Warning.php
- redaxo/src/core/lib/Fragment/Component/Button.php
- redaxo/src/core/lib/Fragment/Component/Button/Add.php
- redaxo/src/core/lib/Fragment/Component/Button/Save.php
- redaxo/src/core/lib/Fragment/Component/Card.php
- redaxo/src/core/lib/Fragment/Component/Checkbox.php
- redaxo/src/core/lib/Fragment/Component/Choice.php
- redaxo/src/core/lib/Fragment/Component/Icon.php
- redaxo/src/core/lib/Fragment/Component/Input.php
- redaxo/src/core/lib/Fragment/Component/Textarea.php
- redaxo/src/core/lib/Fragment/Html.php
Damit wir flexibler sind bzgl. späterer Änderungen.
Wer die Components auf Klassenebene erweitern möchte, sollte neue Klassen erstellen, und die Basis-Komponente intern dann aufrufen.
> Fragment-Component-Klassen sollten final sein

- redaxo/src/core/lib/var/var.php
- redaxo/src/core/tests/var/var_test.php
REX_VARs werden aktuell nicht ersetzt in PHP-String, die Variablen-Interpolation nutzen. Also sowas:
```php
echo "text REX_VALUE[1] $phpVariable";
```
> REX_VARs in PHP-Strings mit Var-Interpolation

- redaxo/src/core/lib/setup/setup.php
fixes; https://github.com/redaxo/redaxo/issues/5647
Hier wird kein Vergleich der Versionen mehr durchgeführt, sondern die aktuelle Version anhand eines deprecation arrays überprüft. 
Ich denke es ist so auch einfacher zu pflegen
> SETUP :: new deprecation check for MariaDB, MySQL and PHP versions

- redaxo/src/addons/install/lib/archive.php
- redaxo/src/addons/install/lib/package/package_download.php
closes #5657
Ich konnte es nicht testen unter Windows, denke aber, dass es so passen sollte.
Wir nutzen den Phar-Stream-Wrapper nur, wenn die Zip-Extension fehlt. Ich denke, deswegen ist es bisher nicht aufgefallen.
> phar:// stream wrapper: Korrekten Dir-Separator nutzen

- redaxo/src/core/lib/error_handler.php
ich hatte lokal einen fall in dem `preg_replace()` `NULL` returned hat wg einem `Backtrack limit exhausted` error.
dies führte dann dazu dass gar keine whoops error page gerendert wurde wg. folge-fehler
```
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in [redaxo/src/core/lib/error_handler.php](phpstorm://open?file=/Users/staabm/workspace/redaxo/redaxo/src/core/lib/error_handler.php&line=277) on line 277
Warning: Cannot modify header information - headers already sent by (output started at /Users/staabm/workspace/redaxo/redaxo/src/core/lib/error_handler.php:276) in [redaxo/src/core/lib/response.php](phpstorm://open?file=/Users/staabm/workspace/redaxo/redaxo/src/core/lib/response.php&line=378) on line 378
Warning: Cannot modify header …
```
> fix error pages on huge errors

- redaxo/src/addons/structure/plugins/content/lib/api_template.php
Keys were compared without using the result.
Assign the key to the template instead.
> Assign key instead of unused comparison

- redaxo/src/addons/metainfo/lib/handler/media_handler.php
Behebt 2 Probleme:
1. Wenn ein Metainfo Feld der Art cat_ und art_ vorhanden war und in beiden Feldern die selbe Datei eingetragen war, wurde nur auf die Verwendung in einem der Felder hingewiesen. Jetzt wird auf die Verwendung in beiden Feldern hingewiesen.
2. Wenn das Feld der Art art_ war und der Artikel ein Startartikel der Kategorie, dann war die Verlinkung falsch. Es wurde ein Link auf ein cat_ Feld erzeugt. Jetzt wird korrekt verlinkt.
fixes #5734
> Löschen von Medien: Verwendungscheck bzgl Artikel/Kategorien korrigiert

- redaxo/src/core/lib/sql/sql.php
https://app.slack.com/client/T1BCPLXEE/C1BAXLN2F/thread/C1BAXLN2F-1688450024.074529, 
@gharlan schrieb:
>das sieht mir nach einem bug aus, der hier entstanden ist: https://github.com/redaxo/redaxo/pull/5545 müsste aber lokal eigentlich auch auftreten. ist lokal  die gleiche rex-version?
> der bug müsste seit 5.14.3 bestehen
> also der PR fixt ein anderes problem, und lässt dabei aber den neuen bug bei den zusätzlichen db-verbindungen entstehen
> https://github.com/redaxo/redaxo/blob/main/redaxo/src/core/lib/sql/sql.php#L137
da müsste es self::factory($db) heißen
> rex_sql: fix für fehlenden `$db`-Parameter

- redaxo/src/addons/structure/lib/service_category.php
close #5748
@gharlan du bist als Autor der rex_clang-Klasse angegeben. Ich habe in die Klasse reingeschaut und m.E. nach ist `getStartId()` das, was an der Stelle hingehört (die erste verfügbare id), ich wüsste auch nicht, was eine Start-ID in dem Kontext von Clang sonst sein soll.
> `$clang = 1` zu `$clang = rex_clang::getStartId();`

- redaxo/src/core/lib/response.php
avoid reading the entire stream and dismissing the data afterward, check between the chunks if the client is still there.
inspired by https://github.com/sabre-io/http/pull/207
> abort on disconnect in `rex_response->sendFile()`

- redaxo/src/core/lib/packages/package.php
supportpage kann via ~ null sein
> Fix: Deprecated: preg_match(): Passing null to parameter

- redaxo/src/addons/media_manager/lib/effects/effect_resize.php
fixes #5694
Beim Modus `exact` macht es eigentlich nicht wirklich Sinn, einen Wert leer zu lassen.
Aber habe mich nun dafür entschieden, wenn doch, dann wird für den Wert einfach der bisherige Wert verwendet.
Denke das passt noch am ehesten zu "exact".
> Effekt resize: Fehler vermeiden, wenn ein Wert leer ist

- redaxo/src/addons/structure/plugins/content/pages/content.php
closes #5692
Es kommt jetzt in dem Fall kein Whoops mehr, sondern nur eine gelbe Warnung "Modul wurde nicht gefunden" nach Reload.
Finde ich auch nicht ganz optimal, aber das zu ändern ist mir jetzt zu kompliziert. Und finde es so noch akzeptabel vom Verhalten.
> Slice löschen: Error vermeiden bei Reload

- redaxo/src/core/lib/util/version.php
on linux/macos we can now determine the git hash in a single command, see https://medium.com/@heba.waly/run-git-from-any-directory-git-c-vs-git-dir-2b6a3936582b
should speedup the slowest part of some requests:
> Faster `rex_version::gitHash()`

- redaxo/src/addons/media_manager/lib/media_manager.php
Auf Windows Geräten wird die Modified Time von Dateien nicht verändert wenn die Datei kopiert wird.
Der Check `$cachetime > $filetime` liefert also auch dann false, wenn beide Zeitstempel identisch sind und die korrekte Datei eigentlich bereits im Cache liegt.
> Media Cache auf Windows Geräten korrekt anhand der file modified time erkennen

- redaxo/src/addons/debug/lib/extensions/logger_debug.php
- redaxo/src/core/lib/util/logger.php
Sobald ein anderes Addon eine neuere Version vom PSR Log verwendet, funktioniert die rex_logger Klasse nicht mehr ( wegen Type Hint) und wirft ein Whoops-Fehler, da das neue LoggerInterface einen Return Type erwartet und rex_logger diesen noch nicht angegeben hat.
https://github.com/php-fig/log/blob/master/src/LoggerInterface.php#L124
> Bugfix rex_logger return type

- redaxo/src/core/lib/sql/sql.php
Schon seit PHP 5.3.6 kann man den Zeichensatz für die Connection direkt über die DSN setzen.
https://github.com/php/php-src/blob/PHP-5.3/NEWS#L1394
`SET NAMES utf8mb4` ist dann überflüssig.
> PDO: charset über DSN setzen

- redaxo/src/core/lib/var_dumper.php
Seit https://github.com/redaxo/redaxo/commit/796993347a3025d03ef7823ee0218c7bf778aa35 funktioniert unsere dump()-Funktion nicht mehr, wenn man unter System keinen Editor ausgewählt hat (das Problem ist somit noch in keinem Release).
Vorher war Symfony da toleranter. Neu erwartet es `string|false`, unsere Editor-Klasse liefert aber `string|null`.
> fix dump function

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- redaxo/src/core/lib/list.php
ein schritt in richtung https://github.com/redaxo/redaxo/pull/5770
---- 
dadurch wird vermieden dass `$this->columnDisabled` in der subclass gebraucht wird
https://github.com/kreatifIT/mail_sprog/commit/b6e98dbda08d07dde03cf33d72b198636d65553f#diff-e3a913a2a9ad719d61884d9259edbef97211f7d1a4cb8215842dc842f9853489R20-R22
> rex_list: refactor logic into new getEnabledColumnNames() method

- redaxo/src/core/lib/list.php
weiterer schritt in richtung https://github.com/redaxo/redaxo/pull/5770
----
dadurch wird vermieden dass `$this->rowAttributes` in der subclass gebraucht wird
https://github.com/kreatifIT/mail_sprog/commit/b6e98dbda08d07dde03cf33d72b198636d65553f#diff-e3a913a2a9ad719d61884d9259edbef97211f7d1a4cb8215842dc842f9853489R32-R34
----
`$this->tableAttributes` wird in der subclass auch via reflection geholt, dafür gibts aber bereits einen `getTableAttributes`-getter 
https://github.com/kreatifIT/mail_sprog/commit/b6e98dbda08d07dde03cf33d72b198636d65553f#diff-e3a913a2a9ad719d61884d9259edbef97211f7d1a4cb8215842dc842f9853489R16-R18
> rex_list: refactor logic into new formatRowAttributes() method

- redaxo/src/core/lib/list.php
weiterer schritt in richtung https://github.com/redaxo/redaxo/pull/5770
----
dadurch wird vermieden dass in der subclass das `$pager` objekt gebraucht wird:
https://github.com/kreatifIT/mail_sprog/commit/b6e98dbda08d07dde03cf33d72b198636d65553f#diff-e3a913a2a9ad719d61884d9259edbef97211f7d1a4cb8215842dc842f9853489R24-R26
> rex_list: refactor logic into new getRowsOnCurrentPage() method

- redaxo/src/core/fragments/core/Component/Alert.php
- redaxo/src/core/fragments/core/Component/Badge.php
- redaxo/src/core/fragments/core/Component/Button.php
- redaxo/src/core/fragments/core/Component/ButtonGroup.php
- redaxo/src/core/fragments/core/Component/Card.php
- redaxo/src/core/fragments/core/Component/Checkbox.php
- redaxo/src/core/fragments/core/Component/ChoiceCheckbox.php
- redaxo/src/core/fragments/core/Component/ChoiceRadio.php
- redaxo/src/core/fragments/core/Component/ChoiceSelect.php
- redaxo/src/core/fragments/core/Component/CopyButton.php
- redaxo/src/core/fragments/core/Component/Details.php
- redaxo/src/core/fragments/core/Component/Dialog.php
- redaxo/src/core/fragments/core/Component/Divider.php
- redaxo/src/core/fragments/core/Component/Drawer.php
- redaxo/src/core/fragments/core/Component/Icon.php
- redaxo/src/core/fragments/core/Component/Input.php
- redaxo/src/core/fragments/core/Component/Range.php
- redaxo/src/core/fragments/core/Component/Switcher.php
- redaxo/src/core/fragments/core/Component/Tab.php
- redaxo/src/core/fragments/core/Component/TabGroup.php
- redaxo/src/core/fragments/core/Component/Textarea.php
- redaxo/src/core/fragments/core/Component/Tooltip.php
- redaxo/src/core/fragments/core/page/SystemLogRedaxo.php
- redaxo/src/core/fragments/core/page/SystemReport.php
- redaxo/src/core/fragments/core/page/SystemSettings.php
- redaxo/src/core/lib/Fragment/Fragment.php
- redaxo/src/core/lib/Fragment/HtmlAttributes.php
Wir hatten beim Treffen diskutiert, ob wir vielleicht doch `__toString()` nutzen im Fragment-Kontext.
Ich habe das hier mal umgesetzt. Finde es besser, denke ich.
> Fragmente: __toString nutzen

- .tools/psalm/baseline.xml
- redaxo/src/addons/cronjob/lib/command/run.php
nexttime ist eine Optimierung für die Frontend/Backend-Jobs, in der Console ist das überflüssig und führte zu Problemen.
closes #5853, closes #5854
> Cronjob-Command: nexttime nicht berücksichtigen

- redaxo/src/core/backend.php
- redaxo/src/core/default.config.yml
- redaxo/src/core/layout/top.php
- redaxo/src/core/lib/rex.php
- redaxo/src/core/schemas/config.json
Aktuell kann jeder das Backend in den Safemode versetzen, auch schon auf der Loginseite.
Das ist problematisch, weil dann auch Addons bzgl. Security z.b. deaktiviert sind.
Neu können nur eingeloggte Admins über `?safemode=1` (oder den Button auf der Systempage) den Safemode aktivieren. Bei der Variante ist er weiterhin sessionbasiert, also nur für den einen Admin aktiviert.
Damit man sich aber notfalls auch im Safemode einloggen kann, kann man neu alternativ den Safemode auch über die config.yml aktivieren (`safemode: true`). So ist er dann global fürs Backend aktiviert unabhängig vom User.
> Safemode nur für Admins oder über config.yml

- redaxo/src/core/backend.php
- redaxo/src/core/default.config.yml
- redaxo/src/core/lib/rex.php
- redaxo/src/core/schemas/config.json
In https://github.com/redaxo/redaxo/pull/5881 wurde für 5.16 ein neuer `safemode`-Schalter für die config.yml eingeführt.
Dieser PR nennt ihn (noch vor Release) doch nochmal um in `safe_mode`. 
Passt besser zum neuen `live_mode` (#5909) und auch besser zu `rex::isSafeMode()`.
(Nur eine kleine Unstimmigkeit gibt es: der schon vorher existierende URL-Parameter bleibt bei `safemode`, und auch der Session-Key.)
> config.yml: safe_mode statt safemode

- .tools/psalm/baseline.xml
- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/cronjob/lib/cronjob.php
- redaxo/src/addons/cronjob/lib/manager.php
- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/cronjob/pages/cronjobs.php
- redaxo/src/addons/debug/package.yml
- redaxo/src/addons/install/lib/api/api_core_update.php
- redaxo/src/addons/install/lib/api/api_package_add.php
- redaxo/src/addons/install/lib/api/api_package_delete.php
- redaxo/src/addons/install/lib/api/api_package_update.php
- redaxo/src/addons/install/lib/api/api_package_upload.php
- redaxo/src/addons/install/package.yml
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/structure/plugins/content/lib/var_value.php
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/core/backend.php
- redaxo/src/core/default.config.yml
- redaxo/src/core/lib/be/controller.php
- redaxo/src/core/lib/error_handler.php
- redaxo/src/core/lib/packages/api_package.php
- redaxo/src/core/lib/rex.php
- redaxo/src/core/pages/system.settings.php
- redaxo/src/core/schemas/config.json
- redaxo/src/core/schemas/package.json
- redaxo/src/core/tests/rex_test.php
Der PR führt einen neuen Live-Mode ein, den man über die `config.yml` aktivieren kann.
Im Live-Mode wird das System gehärtet, sodass ein gekaperter Backend-Admin-Account weniger Schaden anrichten kann.
Insbesondere soll in dem Modus über das Backend kein PHP-Code eingegeben werden können (bzw. der soll zumindest dann nicht ausgeführt werden).
Im Einzelnen hat der Live-Modus diese Folgen:
- Safe-Mode und Debug-Mode sind immer deaktiviert
- System-Page: Buttons für Debug-Modus, Safe-Mode und Setup verschwinden
- Auch als Admin bekommt man kein Whoops, sondern die Ooops-Seite
- Backup-Import-Page verschwindet
- Addonverwaltung verschwindet
- Installer verschwindet
- Metainfoverwaltung verschwindet
- MediaManager-Verwaltung verschwindet
- Debug-Page verschwindet
- Module- und …
> Live-Mode einführen

- .tools/psalm/baseline.xml
- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/lib/list.php
Aktuell übergibt man die Default-Sortierung direkt mit der Query.
Wenn dann per Klick auf Spalte eine andere Sortierung gesetzt wird, wird die Query per Regex angepasst.
Die Regex-Stelle ist uns nicht mehr geheuer und wurde in einem externen Scan auch bemängelt. Daher möchten wir sie gerne loswerden.
Neu sollte die Default-Sortierung als zusätzlicher Param übergeben werden:
```php
$list = rex_list::factory($queryWithoutOrderBy, 30, defaultSort: ['name' => 'asc']);
```
Addons, die eine Default-Sortierung übergeben und die Spaltensortierung aktivieren, müssen nun leider angepasst werden. Ohne Anpassung funktioniert die Per-Spaltenklick-Sortierung nicht mehr (es kommt aber auch kein Fehler).
Addons, die selbst ein `ORDER BY` übergeben und nicht die Per-Spaltenklick-Sortierung nutzen, müssen …
> rex_list: `ORDER BY` nicht mehr per Regex ersetzen

- .tools/psalm/baseline.xml
- phpstan.neon.dist
- psalm.xml
- redaxo/src/addons/install/update.php
- redaxo/src/addons/media_manager/update.php
- redaxo/src/addons/mediapool/update.php
- redaxo/src/addons/structure/update.php
- redaxo/src/core/install.php
- redaxo/src/core/update.php
Wie man zu R6 updaten können wird, steht noch nicht fest.
Aber in jedem Fall sollte man zunächst zur neusten R5-Version updaten. Somit werden die alten Update-Skripte nicht mehr benötigt.
> Remove old update scripts

- redaxo/src/addons/debug/update.php
Hier haben wir versehentlich vergessen, eine `update.php` anzulegen. Die `install.php` wird ja beim Update nicht automatisch ausgeführt.
Somit wurde das frontend.zip beim Update nicht aktualisiert.
> Debug-Addon: Bei Update die install.php ausführen

- redaxo/src/addons/mediapool/pages/media.list.php
Im Mediapool gibt es eine versteckte Config für einen alternativen Suchmodus. Dazu musste man selbst den Configwert in rex_config eintragen.
Dieser PR entfernt den alternativen Modus für 6.x
> Mediapool: Alternativer Suchmodus entfernt

- rector.php
Idee ist, während der Entwicklung von R6 direkt ein Rector-Ruleset mit zu entwickeln und es auch direkt zu nutzen für das Refactoring hier im Repo. So sieht man dann direkt, ob es funktioniert.
Es kann dann später auch für andere Addons und Projekte verwendet werden.
Würde die Rules erstmal direkt in unserer normalen `rector.php` aufnehmen. Später kann man es dann auslagern, sodass es leichter von anderen verwendet werden kann.
> Rector-Ruleset beginnen für Upgrade zu R6

- redaxo/src/addons/media_manager/pages/types.php
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/core/lib/form/elements/element.php
refs https://github.com/redaxo/redaxo/issues/604
Ich denke, dass man die drei Attribute oftmals zusammen setzen will. Daher die Idee, dafür eine Shortcut-Methode einzuführen.
> rex_form: Shortcut um Spellcheck/Autocorrect abzuschalten

- redaxo/src/addons/mediapool/lib/service_media.php
Erhielt unter 6.x diesen Fehler:
```
rex_sql_exception | Error while executing statement "SELECT count(*) FROM rex_media AS m  WHERE (m.category_id = :search_1) ORDER BY m.updatedate DESC" using params {"search_1":0}! SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause | src/Database/Sql.php | 444 | https://redaxo.localhost/redaxo/index.php?page=mediapool/media&opener_input_field=
```
> media_service: Count-Query ohne Order-By

- .tools/psalm/baseline.xml
- redaxo/src/addons/structure/plugins/history/boot.php
- redaxo/src/core/backend.php
- redaxo/src/core/lib/api_function.php
- redaxo/src/core/lib/exception.php
- redaxo/src/core/lib/util/logger.php
@dergel ist aufgefallen, was auch in #1950 beschrieben ist, dass man von außen das normale Fehlerlog zumüllen kann, indem man nicht existierende Api-Functions aufruft.
Dies wollen wir mit diesem PR verhindern (und auch noch weitere ähnliche Stellen).
Daher wird bei `rex_http_exception` bei Client-Errors (4xx Statuscode) nur noch ins Fehlerlog geschrieben, wenn Debug-Mode aktiv oder man als Backend-Admin eingeloggt ist.
Und es wird `rex_http_exception` an weiteren Stellen ergänzt mit 4xx-Statuscode.
closes #1950
> rex_http_exception: Bei 4xx-Fehler nicht loggen im Frontend + an weiteren Stellen nutzen

- redaxo/src/core/lib/api_function.php
Bisher mussten Api-Func-Klassen mit `rex_api_`  beginnen, und der hintere Teil war dann der Name für den Url-Param.
Das ist problematisch, wenn man die eigene Api-Func-Klasse in einem Namespace platzieren möchte.
Daher ist es neu nun auch möglich, Api-Func-Klassen explizit zu registrieren:
```php
rex_api_function::register('my-api', MyApi::class);
```
> Api-Funcs können explizit registriert werden (Namespace)

- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
fixes: https://github.com/redaxo/redaxo/issues/6035
> Codemirror wurde in Moduleingabe nicht ausgelöst

- redaxo/src/addons/be_style/plugins/redaxo/install.php
Bei Core-Update verschwanden die alten Bilder zwar aus dem Plugin-Ordner, aber im Root-assets-Ordner blieben sie erhalten.
Beim Assets-Kopieren werden keine Dateien gelöscht. Nur ergänzt oder überschrieben.
Daher nun explizit im Plugin gelöst, sodass sich im Assets-Ordner nicht immer mehr Bilder ansammeln von Update zu Update.
> be_style/redaxo: Bei update/reinstall alte Login-Bilder löschen

- .tools/bin/release
- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- redaxo/src/addons/debug/boot.php
- redaxo/src/addons/debug/install.php
- redaxo/src/addons/debug/lib/debug_clockwork.php
- redaxo/src/addons/debug/update.php
- redaxo/src/addons/install/lib/api/api_core_update.php
- redaxo/src/addons/install/lib/package/package_update.php
- redaxo/src/addons/install/lib/packages.php
- redaxo/src/addons/project/boot.php
- redaxo/src/core/lib/base/singleton_trait.php
- redaxo/src/core/lib/be/controller.php
- redaxo/src/core/lib/packages/addon.php
- redaxo/src/core/lib/packages/api_package.php
- redaxo/src/core/lib/packages/ep_package_cache_deleted.php
- redaxo/src/core/lib/packages/interface.php
- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/packages/null.php
- redaxo/src/core/pages/credits.php
- redaxo/src/core/pages/packages.changelog.php
- redaxo/src/core/pages/packages.details.php
- redaxo/src/core/pages/packages.help.php
- redaxo/src/core/pages/packages.license.php
- redaxo/src/core/pages/packages.list.php
- src/Core.php
plus Entfernung der Methode `getAddon` und `getType`, die überflüssig sind aufgrund der Plugin-Abschaffung.
> Core-Klasse und Addon-Klassen optimiert bzgl. Typen etc.

- redaxo/src/addons/mediapool/pages/structure.php
- redaxo/src/addons/structure/lib/service_article.php
- redaxo/src/addons/structure/lib/service_category.php
- redaxo/src/addons/structure/plugins/content/lib/content_service.php
- redaxo/src/addons/structure/plugins/content/pages/content.php
- redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
- redaxo/src/core/pages/profile.php
Wir haben mehrere Stellen im Code, wo wir Exception abfangen und die Message an den User ausgeben. 
Dabei geht es nicht um Stellen mit `rex_functional_exception`/`rex_api_exception`, die extra dafür gedacht sind.
Sondern insbesondere `rex_sql_exception` fangen wir öfters ab und geben die Message aus. An Redakteure, also Nicht-Admins. Das finde ich problematisch, sollte man nicht tun, denke ich.
> Exception-Messages nicht an User ausgeben

- redaxo/src/addons/debug/boot.php
fixes #6073
Noch besser fände ich, wenn der Request gar nicht gemacht werden würde. Aber blicke beim Frontend zu wenig durch, weiß daher nicht, ob man den Manifest-Meta-Tag irgendwie sinnvoll entfernt bekommt.
> Clockwork: manifest.json-Request ignorieren

- redaxo/src/core/lib/util/formatter.php
> rex_formatter: Missing "t" in "dateime"

- redaxo/src/addons/structure/plugins/content/boot.php
ich benutze die  rex_article_not_found_exception in meinem Template, um offline Artikel als 404 Fehlerartikel auszugeben.
Der bisherige Code holt sich den Inhalt des 404-Artikels und jagt ihn durch das Template.
Bei mir wurde dabei der SEO Title nicht auf "not found" gesetzt, meine Navigationen zeigten noch den ursprünglichen Artikel an.
Außerdem bekam ich zunächst einen 500er Fehler, weil die exception immer wieder ausgelöst wird, wenn ich versuche sie nur bei rex_article::getCurrentId() != rex_article::getNotFoundArticleId() auszuführen.
Denn viele Methoden, die dabei zum Einsatz kommen wie z.B. `rex_article::getCurrentId()`, basieren alle auf der Property "article_id" (https://github.com/redaxo/redaxo/blob/main/redaxo/src/addons/structure/lib/article.php#L17). 
Mit dieser einen …
> rex_article_not_found_exception erweitert um sie auch im Artikel-Template nutzen zu können

- redaxo/src/addons/mediapool/package.yml
um zu vermeiden, dass komprimitierte SVG eingeschleust werden.
> SVG Dateien werden nun default geblockt

- redaxo/src/addons/media_manager/lib/media_manager.php
replaces #6135
@AndiLeni kannst du es mit diesem EP mal testen. Ich stelle mir den Code dann so in der Art vor:
```php
rex_extension::register('MEDIA_MANAGER_INIT', function (rex_extension_point $ep) {
$mediaManager = $ep->getSubject();
$type = $ep->getParam('type');
$effects = $mediaManager->effectsFromType($type);
foreach ($effects as $effect) {
if ($effect['effect'] === 'negotiator') {
// change cache path for negotiator
$possible_types = rex_server('HTTP_ACCEPT', 'string', '');
$types = explode(',', $possible_types);
$possibleFormat = media_negotiator\Helper::getOutputFormat($types);
$mediaManager->setCachePath($mediaManager->getCachePath() . $possibleFormat . '/');
return;
}
}
});
```
Gut fände ich an dem EP, dass er allgemeiner gefasst ist und einfach dann die vorhandenen …
> Media Manager: neuer EP MEDIA_MANAGER_INIT

- redaxo/src/core/lib/sql/sql.php
Bei einer rex_sql_could_not_connect_exception im REX-Log war bisher nicht sichtbar um welche Datenbank-Verbindung es sich handelt. Wenn man in der config.yml des Cores mehrere DBs eingetragen hat, war im Log nicht nachzuvollziehen, welche Connection den Fehler verursacht hat.
Dieser PR ergänzt die DB-ID im REX-Log und in der Whoops-Meldung.
**REX-Log:**
**Whoops:**
Closes https://github.com/redaxo/redaxo/issues/6221
> Angabe der Datenbank-ID im REX-Log für SQL-Exceptions ergänzt

- redaxo/src/addons/media_manager/boot.php
- redaxo/src/addons/structure/plugins/content/boot.php
- redaxo/src/addons/structure/plugins/history/boot.php
Hier noch ein paar Stellen an denen die EPs im Backend aufgerufen werden. Soweit ich das sehe können die aber so bleiben.
```
rex_extension::register('PAGE_CHECKED', 'rex_metainfo_extensions_handler');
rex_extension::register('STRUCTURE_CONTENT_SIDEBAR', function ($ep) {
```
```
rex_extension::register('RESPONSE_SHUTDOWN', static function () {
```
```
rex_extension::register('PAGE_CHECKED', static function () {
```
```
rex_extension::register('STRUCTURE_CONTENT_HEADER', static function (rex_extension_point $ep) {
```
> API-Extensions unabhängig von Backend registrieren

- redaxo/src/addons/metainfo/uninstall.php
Einerseits um die Functions zur Verfügung zu stellen, andererseits um die Meta-Tables zu registrieren.
fixes #6253
> MetaInfo uninstall: Functions auch einbinden, da benötigt

- redaxo/src/core/lib/api_function.php
- redaxo/src/core/update.php
Nicht mehr über die URL durchschleifen.
> API-Functions: Bei Reboot Result in Session zwischenspeichern

- redaxo/src/core/lib/form/elements/control.php
~statt~ zusätzlich zu `onclick`.
Ich denke, das war ein Versehen in https://github.com/redaxo/redaxo/commit/b4aaf11856f0e7de03feb31ea4590b4bd6cfd680#diff-f93fb0335861fa411ec71e47a184b19217f4462cdfb8fe13f656cf3be9807d1c, dass bei der Umstellung auf `data-confirm` nicht auch die Abfrage entsprechend angepasst wurde.
> rex_form_control_element: `data-confirm`-Attribut abfragen

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/login/backend_login.php
Bei PHP-Umstellung auf 8.4 werden die Passwörter zum ersten Mal neu gehasht, da sich der Default-Kostenfaktor für bcrypt geändert hat.
Dabei gibt es aber einen Fehler in REDAXO, und die Passwörter werden auch neu gehasht, wenn man über den "Eingeloggt bleiben"-Cookie automatisch wieder eingeloggt wird, oder wenn man sich über einen Passkey einloggt.
In den Situationen liegt das Passwort aber im Klartext ja gar nicht vor, somit kann es auch nicht rehasht werden. Es wird dann ein falscher Hash in die DB geschrieben und der User kann sich nicht mehr neu mit Passwort einloggen.
Das Rehashen darf nur passieren, wenn sich der User gerade frisch mit Passwort einloggt, weil man nur dann das Passwort als Klartext zur Verfügung hat für das Rehashen.
> Passwort nur rehashen, wenn sich User gerade mit Passwort neu einloggt

- redaxo/src/core/lib/console/command_loader.php
Die Commands können im Setup-Modus noch nicht verwendet werden, weil die DB ja noch gar nicht existiert.
> Commands `user:create` und `user:delete` nur nach Setup

- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/pages/field.php
Die Werte wurden nicht korrekt escaped. War hier nicht so schlimm, da der Präfix immer validiert wird und nur feste Werte einnimmt. Trotzdem ist es so besser.
> MetaInfo: Escaping für Meta-Präfix korrigiert

- redaxo/src/core/assets/session-timeout.js
In meinem Commit [`97295b0` (#6282)](https://github.com/redaxo/redaxo/pull/6282/commits/97295b043f8845719f48a1b9ca5f4ea7586d57b9) im Ursprungs-PR hatte ich versehentlich die zugehörige Änderung in der JS-Datei vergessen.
> Session overlay: Fix für "eingeloggt bleiben"
