redaxo/redaxo

- redaxo/src/core/lib/util/stream.php
- redaxo/src/core/tests/util/stream_test.php
> Workaround für Suhosin

- redaxo/src/core/lib/error_handler.php
Should fix http://www.redaxo.org/de/forum/post117577.html#p117577
> Fixed exception handler for php7

- redaxo/src/core/lib/form/form.php
> Disable html5 browser validation on abort button submit

- redaxo/src/core/lib/util/validator.php
Should fix https://github.com/redaxo/redaxo/issues/568
> Skip all validations except notempty aka required when value is empty

- redaxo/src/core/lib/form/form.php
To delete a row it dont needs to be valid
> formnovalidate also on delete button

- redaxo/src/core/lib/autoload.php
Ich habe jetzt schon mehrfach die Rückmeldung bekommen, dass der Hauptordner verschoben, oder das Projekt per FTP aufgespielt wurde, und danach eine Exception kam.
Grund: der Autoloader cacht zurzeit absolute Pfade.
Cache löschen hilft somit.
Nach diesem PR ist es nicht mehr notwendig.
@staabm Was meinst du dazu, siehst du irgendwelche Probleme?
> Autoloader: Relative (statt absolute) Pfade cachen

- redaxo/src/addons/mediapool/pages/sync.php
- redaxo/src/core/lib/util/string.php
> Normalisierungsfunktion für NFD -> NFC

- redaxo/src/addons/metainfo/boot.php
- redaxo/src/addons/metainfo/extensions/extension_cleanup.php
- redaxo/src/addons/metainfo/functions/function_metainfo.php
- redaxo/src/addons/metainfo/install.php
- redaxo/src/addons/metainfo/lib/handler/category_handler.php
- redaxo/src/addons/metainfo/lib/handler/clang_handler.php
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/metainfo/pages/index.php
- redaxo/src/core/lib/clang/clang.php
- redaxo/src/core/pages/system.clangs.php
Ich habe das schon öfters mal vorgeschlagen, Markus hat es glaube ich letztens auch mal erwähnt, und Jan eben in Skype. Also scheinbar halten wir drei das prinzipiell für sinnvoll (bei Thomas weiß ich es nicht), daher hier mal offiziell als Vorschlag.
> Metainfos für Sprachen

- redaxo/src/addons/structure/plugins/content/lib/article_action.php
> Slices-Values automatisch zurücksetzen, wenn kein Wert gesendet wurde

- redaxo/src/addons/mediapool/assets/mediapool.js
- redaxo/src/addons/mediapool/pages/index.php
- redaxo/src/addons/mediapool/pages/media.php
- redaxo/src/addons/mediapool/pages/upload.php
- redaxo/src/addons/structure/assets/linkmap.js
- redaxo/src/addons/structure/pages/linkmap.php
- redaxo/src/core/assets/standard.js
closes #445 
Würde das so das Problem lösen?
> JS-Events rex:selectMedia und rex:selectLink

- redaxo/src/core/lib/api_function.php
Refs https://github.com/yakamara/redaxo_ycom/issues/85
> Verbesserte Fehlermeldungen in rex_api_function

- redaxo/src/addons/mediapool/assets/mediapool.js
> Medienpool: Preview bei Mouseover hakelt

- .gitignore
- .php_cs
- bin/release
- redaxo/src/addons/project/boot.php
- redaxo/src/addons/project/package.yml
- redaxo/src/core/default.config.yml
> Projektspezifisches Addon "project"

- redaxo/src/core/lib/packages/package.php
Warning für den seltenen Fall einer leeren package.yml unterdrücken :)
> Warning unterdrücken

- redaxo/src/core/lib/be/controller.php
> Markdown-Subpages ermöglichen

- redaxo/src/core/composer.json
See https://ocramius.github.io/blog/roave-security-advisories-protect-against-composer-packages-with-security-issues/
> Prevent installation of insecure packages

- redaxo/src/addons/backup/pages/export.php
Fixes sql injection vulnerability in export. See https://blog.ripstech.com/2016/redaxo-remote-code-execution-via-csrf/
> Sanitize tables to export

- redaxo/src/addons/mediapool/lib/media.php
Um die Klasse einfach erweiterbar zu machen. Siehe #884
> Vererbbare Properties und Late Static Binding

- redaxo/src/addons/backup/lib/backup.php
- redaxo/src/core/lib/sql/sql.php
Reported via https://blog.ripstech.com/2016/redaxo-remote-code-execution-via-csrf/
> Sanitize arg in exportDb()

- redaxo/src/core/lib/fragment.php
Noch nicht mergen, will zuerst nochmal mit blackfire messen.
> Speedup variables handling in rex_fragments

- redaxo/src/addons/media_manager/lang/de_de.lang
- redaxo/src/addons/media_manager/lang/en_gb.lang
- redaxo/src/addons/media_manager/lib/effects/effect_rotate.php
Übergangslösung zu https://github.com/redaxo/redaxo/issues/322
> Media Manager Effekt "Bild drehen"

- redaxo/src/core/fragments/core/top.php
> added a cachebuster parameter to backend js/css files

- .travis.yml
- redaxo/index.php
Some Composer autoload files require 5.6
> Dont lint vendor files

- redaxo/src/core/lib/setup/setup.php
wird gebraucht für die rex_vars
> tokenizer als requirement fürs setup definiert

- redaxo/src/addons/structure/CHANGELOG.md
- redaxo/src/addons/structure/plugins/content/_install.sql
- redaxo/src/addons/structure/update.php
> Mediumtext-Spalten für Templates und Module

- redaxo/src/core/composer.json
- redaxo/src/core/composer.lock
- redaxo/src/core/lib/error_handler.php
- redaxo/src/core/vendor/composer/installed.json
- redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/JsonResponseHandler.php
- redaxo/src/core/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php
- redaxo/src/core/vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php
@staabm Was meinst du, sollen wir vorübergehend meinen Fork nutzen, damit in 5.3 bereits richtig gekürzt wird?
Sollte mein Whoops-PR nicht gemerged werden, oder es noch Änderungen geben, können wir ja trotzdem im nächsten Redaxo-Release wieder auf die Whoops-Release-Version wechseln, und den Code dann ggf. anpassen.
> whoops: Pfade korrekt kürzen

- redaxo/src/addons/media_manager/lib/media_manager.php
> session_write_close() als fallback für session_abort()

- redaxo/src/addons/mediapool/lib/service_media_category.php
- redaxo/src/addons/mediapool/pages/structure.php
Closes https://github.com/redaxo/redaxo/issues/987
> added rex_media_category_service

- redaxo/src/addons/mediapool/pages/index.php
- redaxo/src/addons/structure/pages/linkmap.php
> Mediepool/Linkmap: Fix für Mehrfacheinfügung bei Auswahl

- redaxo/src/addons/media_manager/lib/managed_media.php
also sollte das fallback nicht bei 80 stehen.
> default ist 85

- redaxo/src/core/lib/sql/table.php
Dieser PR soll die `rex_sql_table`-Api so erweitern, dass man darüber auch Tabellen löschen oder neu anlegen kann. Außerdem soll man auch Keys (Primary, ~normale, Unique, Foreign~) darüber verwalten können.
Die Methoden werden von ydeploy genutzt werden, aber auch für andere Addons kann es praktisch sein, insbesondere in der `update.php`.
> rex_sql_table: Tabellen anlegen/löschen, Primary Key verwalten

- redaxo/src/core/lib/sql/table.php
> rex_sql_table: Tabellenumbenennung

- redaxo/src/addons/install/pages/packages.add.php
sets the autofocus on search input
> Installer :: autofocus on search input

- redaxo/src/addons/mediapool/pages/media.php
> Cache Buster für Bilder im Medienpool

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/pages/media.php
per .selectpicker restyled + Livesearch
**Vorher:**
> Medienpool :: Selects / CSS / Bootstrap

- redaxo/src/addons/media_manager/install.php
- redaxo/src/addons/media_manager/lang/de_de.lang
- redaxo/src/addons/media_manager/lang/en_gb.lang
- redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/pages/settings.php
closes #1070, closes #1083, closes #1119, closes #1125, closes #773, closes #759
> Media Manager: Einstellungen für Interlace und PNG-Kompression, und neuer Effekt "image_properties"

- redaxo/src/addons/media_manager/lang/de_de.lang
- redaxo/src/addons/media_manager/lang/en_gb.lang
- redaxo/src/addons/media_manager/lib/effects/effect_filter_brightness.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_contrast.php
* Value von -255 bis 255
* max / min / empty wird abgefangen und normalisiert
> added brightness and contrast filter effect

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
@tbaddade @staabm 
Tests fehlen noch. Aber bitte vor allem mal schauen, ob wir denn überhaupt alle das gleiche meinten. ;)
closes #1196
> rex_sql_table: Shortcuts für gängige Spalten

- redaxo/src/addons/structure/pages/linkmap.php
Ursprung
https://demo.ripstech.com/main/(issues/18/18/1/6582/(content:summary//info:desc)//sidebar:issues/18/18/1/6582)
> sanitize user-input in REX_LINKLIST

- redaxo/src/addons/structure/plugins/content/lib/api_template.php
> #1279 Fehlerhafte Abfrage in api_template.php

- redaxo/src/core/lib/sql/sql.php
> use a single SET query for all mysql settings

- redaxo/src/addons/media_manager/lang/de_de.lang
- redaxo/src/addons/media_manager/lib/effect_abstract.php
- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
- redaxo/src/addons/media_manager/lib/effects/effect_crop.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_blur.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_brightness.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_colorize.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_contrast.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_greyscale.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_sepia.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_sharpen.php
- redaxo/src/addons/media_manager/lib/effects/effect_flip.php
- redaxo/src/addons/media_manager/lib/effects/effect_header.php
- redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
- redaxo/src/addons/media_manager/lib/effects/effect_insert_image.php
- redaxo/src/addons/media_manager/lib/effects/effect_mediapath.php
- redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
- redaxo/src/addons/media_manager/lib/effects/effect_resize.php
- redaxo/src/addons/media_manager/lib/effects/effect_rotate.php
- redaxo/src/addons/media_manager/lib/effects/effect_rounded_corners.php
- redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
- redaxo/src/addons/media_manager/pages/effects.php
closes #1176 
Ist noch nicht fertig, englische Übersetzungen fehlen noch, und in #1176 wird noch diskutiert, ob wir noch eine Gruppenstruktur haben wollen.
> Effekte mit schöneren Namen

- redaxo/src/addons/install/lib/api_core_update.php
- redaxo/src/addons/install/lib/api_package_download.php
> Installer: "Illegal result returned from api-function" vermeiden

- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
- redaxo/src/addons/media_manager/lib/effects/effect_mediapath.php
- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/lib/media_manager.php
- redaxo/src/addons/media_manager/pages/effects.php
> MM Verbesserungen

- redaxo/src/core/lib/sql/sql.php
> rex_sql: Query mit in Exception Message

- redaxo/src/core/lib/config.php
- redaxo/src/core/lib/setup/import.php
> Setup: Bei Import die Addon-Config aus Dump übernehmen

- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/setup/import.php
- redaxo/src/core/lib/util/i18n.php
.. statt die Standard-Packages zu installieren.
> Setup: Bei "Datenbank existiert bereits" und "Update" die bisherigen Packages reinstallieren

- redaxo/src/addons/phpmailer/pages/checkmail.php
- redaxo/src/addons/phpmailer/pages/config.php
Hier hatte sich irgendwie eine Kopie der config reingemogelt.
> phpmailer: checkmail.php - Korrekte Datei

- redaxo/src/addons/phpmailer/install.php
- redaxo/src/addons/phpmailer/lang/de_de.lang
- redaxo/src/addons/phpmailer/lang/en_gb.lang
- redaxo/src/addons/phpmailer/lib/mailer.php
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/addons/phpmailer/pages/config.php
- redaxo/src/addons/phpmailer/update.php
> phpmailer backup config fixed #1237

- redaxo/src/core/lib/sql/foreign_key.php
- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
> rex_sql_table: support foreign keys

- redaxo/src/addons/backup/CHANGELOG.md
- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/be_style/CHANGELOG.md
- redaxo/src/addons/be_style/package.yml
- redaxo/src/addons/cronjob/CHANGELOG.md
- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/install/CHANGELOG.md
- redaxo/src/addons/install/package.yml
- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/mediapool/CHANGELOG.md
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/metainfo/CHANGELOG.md
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/phpmailer/CHANGELOG.md
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/addons/structure/CHANGELOG.md
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/addons/structure/plugins/history/package.yml
- redaxo/src/addons/structure/plugins/version/package.yml
- redaxo/src/addons/users/CHANGELOG.md
- redaxo/src/addons/users/package.yml
- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/boot.php
Bin noch nicht durch mit dem Changelog, daher noch nicht mergen!!
> Version 5.4.0-beta1

- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/media_manager/pages/effects.php
- redaxo/src/core/lib/form/elements/prio.php
> Effekt-Namen auch im Prio-Feld übersetzen

- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/pages/profile.php
> Neue EPs: USER_ADDED/UPDATED/DELETED, PROFILE_UPDATED und PASSWORD_UPDATED

- redaxo/src/addons/be_style/plugins/customizer/lang/de_de.lang
- redaxo/src/addons/be_style/plugins/customizer/lang/en_gb.lang
- redaxo/src/addons/be_style/plugins/customizer/package.yml
- redaxo/src/addons/be_style/plugins/customizer/pages/system.customizer.php
> Customizer: Validierung für Farbe entfernt

- redaxo/src/addons/be_style/plugins/customizer/boot.php
- redaxo/src/addons/be_style/plugins/customizer/help.php
- redaxo/src/core/fragments/core/footer.php
see https://twitter.com/iammerrick/status/914988292637990912
> prevent XSS with rel="noreferrer noopener" for target="_blank" urls

- redaxo/src/addons/structure/lib/api_functions/api_article_status.php
Beim Cherry-Picking ist mir der falsche Inhalt in die Datei gerutscht. Dies ist die korrekte Klasse. Fixes #1400
> Datei-Inhalt wiederherstellen

- redaxo/src/core/default.config.yml
- redaxo/src/core/fragments/core/footer.php
closes https://github.com/redaxo/redaxo/issues/1409
> passwortdefaults ändern

- redaxo/src/core/pages/setup.php
> added missing html-escaping in setup

- README.md
> #1399 update README.md

- redaxo/src/core/assets/standard.js
- redaxo/src/core/backend.php
- redaxo/src/core/default.config.yml
- redaxo/src/core/fragments/core/footer.php
- redaxo/src/core/fragments/core/top.php
closes https://github.com/redaxo/redaxo/issues/1039
> keep session alive

- redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
> Workspace-Effekt: Leere Zielwerte unterstützen

- redaxo/src/addons/media_manager/lib/managed_media.php
> Bilder automatisch gemäß Exif-Flag drehen

- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
- redaxo/src/addons/structure/plugins/content/pages/templates.php
> Template & Module EPs hinzugefügt

- redaxo/src/core/lib/console/cache/clear.php
- redaxo/src/core/lib/console/command.php
- redaxo/src/core/lib/console/command_loader.php
> Added Console Command cache:clear

- redaxo/src/addons/media_manager/lib/managed_media.php
fix für https://github.com/redaxo/redaxo/issues/1475
> warnings exif_read_data verhindern/ unterdrücken

- redaxo/src/core/lib/fragment.php
> Methodenverkettung ermöglicht und PHPDoc comments ergänzt

- redaxo/src/core/lib/console/cache/clear.php
- redaxo/src/core/lib/console/command.php
- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/package/deactivate.php
Da wir inzwischen schon andere Core-Commands haben, habe ich diesen allgemeinen Part nun rausgetrennt aus #1427.
/cc @bloep
> Console: Registrierung Core-Commands vereinfacht

- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/package/activate.php
> Added Console Command package:activate

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
> Medienpool: Type-Check case-insensitive

- redaxo/src/core/lib/form/form.php
> rex_form: setzen von applyUrl war nicht möglich

- redaxo/src/addons/cronjob/lib/manager.php
Refs https://github.com/redaxo/redaxo/issues/1431
da die Problematik im issue nicht klar beschrieben ist, ist das hier mehr ein schuss ins blaue.
> cli: handle errors gracefully when a cronjob throws

- redaxo/src/addons/media_manager/pages/effects.php
- redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/lib/setup/import.php
- redaxo/src/core/lib/util/i18n.php
- redaxo/src/core/pages/system.settings.php
> rex_i18n: Params auch escapen

- redaxo/src/addons/media_manager/pages/effects.php
fixes #1494 
closes #1510 
@phoebusryan Ich benutze lieber unsere organizePriorities-Funktion. Trotzdem danke für deinen PR!
> MM: Nach Effektlöschung Prios neu setzen

- redaxo/src/core/lib/util/socket/socket.php
> rex_socket: Neue Methode followRedirects()

- redaxo/src/core/lib/util/logger.php
- redaxo/src/core/lib/util/socket/socket.php
> Warnung loggen, wenn ein socket/proxy-socket ohne ssl verwendet wird

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/pages/setup.php
Closes https://github.com/redaxo/redaxo/issues/1479
> Warnung im Setup ausgeben, wenn Apache mod_security geladen ist

- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/setup/import.php
> Setup: Reinstall der Packages korrigiert

- redaxo/src/core/lib/util/log_file.php
- redaxo/src/core/tests/util/log_entry_test.php
Unterstützung für \n Zeilenumbrüche
> Log-Dateien: Zeilenumbrüche erhalten

- redaxo/src/addons/install/lib/api_core_update.php
- redaxo/src/addons/install/lib/api_package_update.php
> Nach Core-/Addon-Update Opcache zurücksetzen

- redaxo/src/core/default.config.yml
Als hinweis wg https://github.com/redaxo/redaxo/issues/1437
> Hinweis bzgl untersch. Cookie domains und backend session Erkennung

- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/mediapool/pages/structure.php
- redaxo/src/addons/structure/functions/function_rex_category.php
- redaxo/src/addons/structure/functions/function_rex_searchbar.php
- redaxo/src/addons/structure/pages/linkmap.php
- redaxo/src/core/fragments/core/navigations/breadcrumb.php
escaping angepasst bei breadcrumb fragmentaufrufen
> XSS mediapool

- redaxo/src/addons/structure/lib/perm.php
https://wiki.php.net/rfc/counting_non_countables - count auf null gibt eine notice
> php 7.2 compat

- redaxo/src/addons/structure/lib/structure_element.php
- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
- redaxo/src/addons/structure/plugins/content/lib/article_slice.php
- redaxo/src/addons/structure/plugins/content/pages/content.php
Closes https://github.com/redaxo/redaxo/issues/843
> introduce getClangId() and deprecate getClang()

- redaxo/src/core/lib/sql/sql.php
Closes https://github.com/redaxo/redaxo/issues/573
> rex_sql Transaktions api hinzugefügt

- redaxo/src/addons/structure/plugins/content/lang/de_de.lang
> Spalte > Bereiche

- redaxo/src/addons/cronjob/pages/cronjobs.php
> Cronjob: CSRF-Token für Status-Link fehlte

- redaxo/src/addons/cronjob/lib/command/run.php
> Command cronjob:run: Optional Job direkt ausführen

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/pages/media.php
- redaxo/src/addons/mediapool/pages/upload.php
> MEDIA_ADDED nicht mehr doppelt, MEDIA_UPDATED verschoben

- redaxo/src/addons/phpmailer/README.md
Korrekturen aus Doku übernommen
> PHPMailer::Doku-Korrektur

- redaxo/src/addons/phpmailer/install.php
- redaxo/src/addons/phpmailer/package.yml
> phpmailer :: default setting for logging to 0

- redaxo/src/addons/structure/lib/service_article.php
> Neue Extension Points ART_MOVED und ART_COPIED

- redaxo/src/core/lib/response.php
> rex_response::sendFile - Added optional parameter for filename

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/packages/package.php
> Deinstallation von Addons/Plugins: Cache des Packages löschen

- redaxo/src/core/lib/response.php
503 - HTTP_TEMPORARILY_UNAVAILABLE
> adds 503 header response 

- redaxo/src/core/fragments/core/footer.php
- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lang/es_es.lang
- redaxo/src/core/lang/it_it.lang
- redaxo/src/core/lang/pt_br.lang
- redaxo/src/core/lang/sv_se.lang
> Doku in Footer verlinken

- redaxo/src/core/default.config.yml
- redaxo/src/core/lib/util/i18n.php
- redaxo/src/core/tests/util/i18n_test.php
closes #1707 
Müssen nun aber noch entscheiden, ob Deutsch default als Fallback-Fallback eingetragen sein soll, oder nicht.
Siehe dazu die Diskussion im Issue. @schuer ist dafür, ich tendiere eher dagegen, lasse mich aber auch gerne überstimmen.
/cc @schuer
> rex_i18n: Englisch als Fallback

- redaxo/src/core/lib/response.php
> sendResource: Content-Disposition setzen können

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
> rex_sql: Mehrere Datensätze gleichzeitig einfügen

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
> rex_mediapool_syncFile: Userlogin kann angegeben werden

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
> Neue Methode rex_sql::insertOrUpdate()

- redaxo/src/core/lib/config.php
> rex_config: weniger Queries nutzen

- redaxo/src/addons/install/lang/de_de.lang
- redaxo/src/addons/install/lang/en_gb.lang
- redaxo/src/addons/install/pages/packages.add.php
> [Installer] Zeige Addon Release

- redaxo/src/core/lib/sql/sql.php
fixes #1623
Dieser PR sorgt erst mal nur dafür, dass Views nicht mehr als Tables betrachtet werden.
Die korrekte Unterstützung für Views kann denke ich separat ein anderes Mal integriert werden.
> rex_sql: Views nicht als Tables betrachten

- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/user/set_password.php
> Console: Neues Passwort kann gesetzt werden

- redaxo/src/addons/users/pages/users.php
> Benutzerliste sortierbar nach Spalten

- redaxo/src/addons/metainfo/lib/handler/article_handler.php
> Metainfo: updatedate/user bei Artikeln aktualisieren

- redaxo/src/addons/backup/LICENSE
- redaxo/src/addons/be_style/LICENSE
- redaxo/src/addons/be_style/plugins/customizer/LICENSE
- redaxo/src/addons/be_style/plugins/redaxo/LICENSE
- redaxo/src/addons/cronjob/LICENSE
- redaxo/src/addons/cronjob/plugins/article_status/LICENSE
- redaxo/src/addons/cronjob/plugins/optimize_tables/LICENSE
- redaxo/src/addons/debug/LICENSE
- redaxo/src/addons/install/LICENSE
- redaxo/src/addons/media_manager/LICENSE
- redaxo/src/addons/mediapool/LICENSE
- redaxo/src/addons/metainfo/LICENSE
- redaxo/src/addons/phpmailer/LICENSE
- redaxo/src/addons/structure/LICENSE
- redaxo/src/addons/structure/plugins/content/LICENSE
- redaxo/src/addons/structure/plugins/history/LICENSE
- redaxo/src/addons/structure/plugins/version/LICENSE
- redaxo/src/addons/tests/LICENSE
- redaxo/src/addons/users/LICENSE
Nur das project-Addon habe ich weggelassen, da man dort ja seinen eigenen Code ablegt.
> Lizenz in allen Packages hinterlegen

- redaxo/src/core/lib/autoload.php
> Weniger Dateioperationen im Autoloader

- redaxo/src/core/lib/util/file.php
> Weniger Dateioperationen in rex_file->get()

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/pages/system.settings.php
> Debug-Modus erläutern

- redaxo/src/core/lib/autoload.php
Da aufgefallen im profile
https://blackfire.io/profiles/16a50ed9-8ce0-4113-93db-6446732523e3/graph
> Mikrooptimierungen im Autoloader

- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
> Kompatibilität mit anderen Kommando-Shells verbessern

- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/lib/login/login.php
> Benutzerwechsel in inaktive Benutzer ermöglichen

- redaxo/src/core/lib/list.php
Ungetestet!
Closes https://github.com/redaxo/redaxo/issues/1724
> Paginierung per RexList ermöglichen

- redaxo/src/addons/structure/lib/api_functions/api_category_status.php
> Kategorie-Status: Korrekte Permission prüfen

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_select_test.php
Closes https://github.com/redaxo/redaxo/issues/1684
> To resolve the lost fetchType bug after next()

- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/mediapool/CHANGELOG.md
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/structure/CHANGELOG.md
- redaxo/src/addons/structure/package.yml
- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/boot.php
Als Vorbereitung für das wahrscheinlich morgige Release.
> Version 5.6.1

- redaxo/src/addons/be_style/boot.php
Alternative zu PR https://github.com/redaxo/redaxo/pull/1853
> Font nur bei html fullpage requests preloaden

- redaxo/src/core/lib/error_handler.php
> Notices/Warnings: Datei verlinken

- redaxo/src/core/lib/util/editor.php
Wir hatten den xdebug-Editor noch gar nicht behandelt.
> Editor: xdebug wurde nicht behandelt

- redaxo/src/addons/backup/lang/de_de.lang
- redaxo/src/addons/backup/lang/en_gb.lang
- redaxo/src/addons/backup/pages/import.server.php
- redaxo/src/addons/backup/pages/import.upload.php
Sollte https://github.com/redaxo/redaxo/issues/1871 beheben
Ungetestet!
> Backup: Fehlerbehandlung beim löschen von dateien korrigert

- redaxo/src/core/lib/exception.php
> rex_http_exception: Message aus Orig-Exception nehmen

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/pages/system.log.php
Refs https://github.com/redaxo/redaxo/issues/1868
> Systemlog kann via System-Editor geöffnet werden

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
> rex_sql: Neue Methoden getTables/getViews/getTablesAndViews; deprecated showTables

- redaxo/src/core/lib/autoload.php
hab den neusten stand reingeholt... im phpdoc steht was von "copied with little changes", fehlt hier noch was?
> Classloader mit Composer Classloader synchronisiert

- redaxo/src/addons/backup/lib/backup.php
- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/backup/pages/export.php
- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/cronjob/plugins/optimize_tables/lib/cronjob.php
- redaxo/src/core/lib/setup/import.php
https://github.com/redaxo/redaxo/pull/1889#issuecomment-404651661
> rex_sql: getTables statt showTables nutzen

- redaxo/src/core/lib/error_handler.php
Ich habe den Button erst mal neben dem vorhandenen Copy-Button platziert.
Bin mir noch nicht so sicher mit der Darstellung/Bezeichnung.
Die Ausgabe des Markdown-Inhalts sieht dann so aus:
---
**InvalidArgumentException:** Expecting $key to be string, but integer given!
**File:** redaxo/src/core/lib/packages/package.php
**Line:** 157
<details>
<summary>Stacktrace</summary>
| Function                 | File                                     | Line     |
| ------------------------ | ---------------------------------------- | -------- |
| rex_package->hasProperty | redaxo/src/core/lib/packages/package.php | 145      |
| rex_package->getProperty | redaxo/src/addons/project/boot.php       | 58       |
| include                  | redaxo/src/core/lib/packages/package.php | 228      |
| …
> Whoops: Copy-Button für Markdown (Exception mit Stacktrace + Systembericht)

- redaxo/src/core/lib/util/i18n.php
Ungetestet.
Todo
War sichtbar in messungen aus https://github.com/redaxo/redaxo/issues/1919
> I18n::translateArray() micro-Optimierungen

- redaxo/src/core/pages/system.settings.php
Entspricht nun der Auswahl im Nutzerprofil.
Issue: 
https://github.com/redaxo/redaxo/issues/1973
> Settings: Sprachauswahl ausgeschrieben

- redaxo/src/addons/phpmailer/pages/config.php
Die SMTP-Einstellungen werden erst gezeigt, wenn als mailer ausgewählt
> PHPMailer show SMTP settings only if checked

- redaxo/src/addons/structure/pages/index.php
Selectpicker bei Template-Auswahl
vorher
> Template select selectpicker

- redaxo/src/core/lib/util/i18n.php
- redaxo/src/core/tests/util/i18n_test.php
> Php5 string-cb regression test

- redaxo/src/addons/cronjob/pages/cronjobs.php
https://github.com/redaxo/redaxo/issues/1980
jetzt:
> Crontyp abhängige Parameter in der Reihenfolge ändern

- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/media_manager/pages/types.php
> MM: Beim Löschen von Typ auch deren Effekte löschen

- redaxo/src/addons/media_manager/pages/types.php
> MM: maxlength-Attribut

- redaxo/src/addons/cronjob/plugins/article_status/install.php
- redaxo/src/addons/cronjob/plugins/optimize_tables/install.php
> Vorinstallierte Cronjobs: Werte in DB aktualisiert

- redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
> MM: Bug bei Auswahl interlace in image_properties

- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/lib/login/backend_login.php
> `UNIX_TIMESTAMP()` in mysql vermeiden

- redaxo/src/addons/be_style/plugins/customizer/boot.php
- redaxo/src/core/pages/system.log.external.php
Refs https://github.com/redaxo/redaxo/issues/1842
Beispiel wie man nach dieser Änderung dann ein Logfile einbinden kann
https://github.com/redaxo/redaxo/pull/2010
> Addons erlauben zusätzliche Logfiles zu registrieren 

- .editorconfig
> .editorconfig hinzugefügt

- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/lib/list.php
Ungetestet 
Closes 
https://github.com/redaxo/redaxo/issues/2043
> SqlInjection-Lücke in rex_list behoben

- redaxo/src/addons/media_manager/lib/media_manager.php
> neue ExtensionPoints MEDIA_MANAGER_BEFORE_SEND & MEDIA_MANAGER_AFTER_SEND

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/pages/index.php
- redaxo/src/core/boot.php
refs redaxo/redaxo4#421
refs redaxo/redaxo4#422
> mediapool xss fix

- redaxo/src/addons/media_manager/pages/types.php
Ungetestet 
Closes https://github.com/yakamara/redaxo-security-issues/issues/4
Der einfachheit halber hab ich den changelog für diesen PR in dem anderen mit reingepackt:
https://github.com/redaxo/redaxo/pull/2057/files#diff-083a1fafa129b3aab8fd2db64f63c4ec
> XSS Lücke im Mediamanager behoben

- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/CHANGELOG.md
Ungetestet 
Closes https://github.com/yakamara/redaxo-security-issues/issues/5
> Sql-Injection Sicherheitslücken in der Benutzerverwaltung behoben

- .travis.yml
- redaxo/src/addons/tests/lib/test_runner.php
Cs check bewusst erstmla auf 7.2 gelassen, da dies aktuell noch die letzte stabile php version ist
> Added php7.3 to travis

- redaxo/src/core/lib/response.php
> const HTTP_MOVED_TEMPORARILY

- redaxo/src/core/layout/top.php
- redaxo/src/core/lib/context.php
- redaxo/src/core/lib/form/elements/checkbox.php
- redaxo/src/core/lib/form/elements/container.php
- redaxo/src/core/lib/form/elements/element.php
- redaxo/src/core/lib/form/elements/radio.php
- redaxo/src/core/lib/form/form_base.php
- redaxo/src/core/lib/list.php
- redaxo/src/core/lib/select.php
- redaxo/src/core/lib/setup/import.php
- redaxo/src/core/lib/util/formatter.php
- redaxo/src/core/lib/util/i18n.php
- redaxo/src/core/pages/credits.php
- redaxo/src/core/pages/login.php
- redaxo/src/core/pages/packages.php
- redaxo/src/core/pages/profile.php
- redaxo/src/core/pages/system.clangs.php
- redaxo/src/core/pages/system.log.external.php
- redaxo/src/core/pages/system.log.redaxo.php
- redaxo/src/core/pages/system.settings.php
- redaxo/src/core/tests/context_test.php
- redaxo/src/core/tests/util/formatter_test.php
Ersetzen der Escape-Funktionen im core.
refs #2063
> core - Escaping durch rex_escape ersetzt

- redaxo/src/core/lib/select.php
Ungetestet 
Vermutlich ein Fix für https://github.com/redaxo/redaxo/issues/2093
> Regression fix für selected-attribut nach escaping Änderungen

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lib/minibar/minibar_element_system.php
https://github.com/redaxo/redaxo/issues/2041#issuecomment-431571241
Closes https://github.com/redaxo/redaxo/issues/2041
> Adds GitHub issue link to minibar

- .github/ISSUE_TEMPLATE/---security-issue.md
- Hinweis zur Veröffentlichung von Sicherheitsproblemen direkt in der Übersicht
- Geändertes Symbol
> Issue Template - geänderter Text

- .github/ISSUE_TEMPLATE/---feature-request.md
Damit die Formatierung richtig angezeigt wird
> Fix typo in issue template

- redaxo/src/addons/mediapool/pages/media.detail.php
- redaxo/src/addons/mediapool/pages/media.list.php
> Medienpool vereinfachungen

- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/db/set_connection.php
- redaxo/src/core/lib/console/db/set_connection_options.php
> add cli command db:set-connection-options

- redaxo/src/core/lib/sql/sql.php
rex_sql - Debug-Ausgabe erweitern um aufgelöstes SQL-Statement
Update redaxo/src/core/lib/sql/sql.php
closes #2150
> rex_sql - Debug-Ausgabe erweitern um aufgelöstes SQL-Statement

- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/config/get.php
> add command config:get

- redaxo/src/core/lib/error_handler.php
sollte https://github.com/redaxo/redaxo/issues/2181 beheben.
Ungetestet
> Exceptions in der CLI nicht als html website behandeln

- redaxo/src/core/boot.php
Damit im setup auch whoops Fehlerseiten dargestellt werden
Refs https://github.com/redaxo/redaxo/issues/2181#issuecomment-435671752
> ErrorHandler immer registrieren

- redaxo/src/core/fragments/core/footer.php
- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lib/minibar/minibar_element_system.php
> Forum Links gelöscht, close #2172

- redaxo/src/core/assets/standard.js
- redaxo/src/core/layout/bottom.php
> Pjax-Unterstützung für die Minibar

- redaxo/src/addons/be_style/plugins/customizer/boot.php
> customizer: prevent notice

- redaxo/src/core/pages/profile.php
führt einen Redirect nach dem Speichern aus, damit beim full reload die Sprache gewechselt ist.
closes #2210
> Profil: Reload nach Speichern

- redaxo/src/addons/be_style/plugins/customizer/boot.php
> Customizer: Persistent XSS via Servername verhindern

- redaxo/src/addons/backup/lib/backup.php
analog https://github.com/redaxo/redaxo/pull/2272 nur direkt im backup
> Backup: fast-exit um backups zu beschleunigen

- redaxo/src/addons/phpmailer/CHANGELOG.md
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/boot.php
> Release R5.6.5

- redaxo/src/addons/media_manager/lib/media_manager.php
Refs https://github.com/redaxo/redaxo/issues/2288#issuecomment-446178743
> media-manager: kürzere cache Lebenszeit bei aktiven sessions

- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
> Sandbox für Stream-Include

- redaxo/src/addons/mediapool/lib/media.php
- redaxo/src/addons/mediapool/lib/media_category.php
um unnötige file_exists() aufrufe zu vermeiden
Refs #2297
> Medienpool: Optimistisches cache lesen

- redaxo/src/core/update.php
> Zwischenupdate erfordern bei <5.4

- redaxo/src/addons/structure/lib/structure_element.php
> Artikel konnten als rex_category-Objekt erzeugt werden

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/sv_se.lang
https://github.com/redaxo/redaxo/pull/2059#pullrequestreview-167517444
> CSRF-Token-Meldung verallgemeinert

- redaxo/src/addons/backup/lib/backup.php
- redaxo/src/addons/backup/package.yml
> Backup: export cleanup

- redaxo/src/addons/be_style/plugins/customizer/boot.php
- redaxo/src/addons/be_style/plugins/customizer/install.php
einfaches review mit https://github.com/redaxo/redaxo/pull/2339/files?w=1
> Customizr vereinfacht

- redaxo/src/addons/install/lib/api_package_upload.php
- redaxo/src/addons/install/lib/archive.php
Implement excludes from package.yml
closes #1272
> Installer: implement package excludes

- redaxo/src/core/lib/util/log_file.php
> rex_log: Unnötiges file_exists entfernt

- redaxo/src/addons/structure/lib/article.php
- redaxo/src/addons/structure/lib/structure_element.php
- redaxo/src/addons/structure/plugins/content/lib/minibar_element_structure_clang.php
- redaxo/src/addons/structure/plugins/content/lib/minibar_element_structure_content.php
- redaxo/src/core/fragments/core/minibar/minibar_backend.php
- redaxo/src/core/fragments/core/minibar/minibar_element.php
- redaxo/src/core/fragments/core/minibar/minibar_frontend.php
- redaxo/src/core/lib/minibar/api_minibar.php
- redaxo/src/core/lib/minibar/minibar.php
- redaxo/src/core/lib/minibar/minibar_element.php
- redaxo/src/core/lib/minibar/minibar_element_system.php
- redaxo/src/core/lib/minibar/minibar_element_time.php
- redaxo/src/core/lib/minibar/minibar_lazy_element.php
Closes https://github.com/redaxo/redaxo/issues/2326
> Lazy minibar element

- redaxo/src/core/packages.php
> 'packages_boot' stopwatch hinzugefügt

- redaxo/src/addons/be_style/boot.php
- redaxo/src/core/lib/minibar/minibar.php
closes https://github.com/redaxo/redaxo/issues/2348
> minibar: programmatisches aktivieren/deaktivieren erlauben

- redaxo/src/core/functions/function_rex_escape.php
Änderungen von Twig übertragen.
Im Wesentlichen sind es wohl diese beiden Commits:
https://github.com/twigphp/Twig/commit/ce4aff66ccf5ad8539b0a47d5936fa1c9a483c61
https://github.com/twigphp/Twig/commit/e90c78610221f9d8e9d00a4baa2f71bb2b6ba189
> fix rex_escape

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
> rex_sql_table: Default value CURRENT_TIMESTAMP korrekt behandeln

- redaxo/src/addons/media_manager/lib/effects/effect_filter_blur.php
- redaxo/src/addons/media_manager/lib/effects/effect_flip.php
- redaxo/src/addons/metainfo/lib/input/datetime.php
- redaxo/src/core/lib/util/socket/socket_proxy.php
- redaxo/src/core/pages/profile.php
warnungen gefixed die beim scan mit phpstan aufgefallen sind
**mergen ohne squash!**
> Phpstan fixes

- redaxo/src/addons/structure/plugins/history/boot.php
Ungetestet
Gefunden via phpstan
> fix 'Undefined variable: $version'

- redaxo/src/addons/structure/plugins/content/lib/event_select.php
- redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
Closes https://github.com/redaxo/redaxo/issues/2427
> rex_event_select in eigene datei auslagern

- redaxo/src/core/lib/sql/sql.php
closes https://github.com/redaxo/redaxo/issues/2424
> rex_sql: console als global update/create field unterstützen

- redaxo/src/addons/debug/boot.php
PHP Notice:  Undefined index: REQUEST_URI in /home/travis/build/redaxo/redaxo/redaxo/src/addons/debug/vendor/chromephp/ChromePhp.php on line 136
Gefunden via phpstan
> Fixed 'Undefined index: REQUEST_URI'

- redaxo/src/core/lib/rex.php
closes https://github.com/redaxo/redaxo/issues/2446
> rex::isFrontend() hinzugefügt

- redaxo/src/addons/structure/plugins/content/lib/content_service.php
> Fixed 'Variable $updSort might not be defined.'

- redaxo/src/addons/debug/lib/sql_debug.php
Variable $file might not be defined.  
Variable $line might not be defined.
Via phpstan
> Fixed Warnings

- redaxo/src/addons/structure/plugins/content/pages/content.php
> Fixed 'Variable $module_id might not be defined.'

- redaxo/src/core/fragments/core/footer.php
- redaxo/src/core/lib/minibar/element/time.php
closes https://github.com/redaxo/redaxo/issues/2385
> Datums aus footer/minibar entfernt

- redaxo/src/addons/install/lib/api_core_update.php
- redaxo/src/addons/install/lib/api_package_update.php
> Installer: Requirements-Checks korrigiert

- redaxo/src/addons/install/pages/packages.add.php
- redaxo/src/addons/install/pages/packages.update.php
- redaxo/src/addons/install/pages/packages.upload.php
Die Dateien hatten schon eine `$addon`-Variable.
Daher die neue Variable nochmal umbenannt.
> Installer: Variablenumbenennung

- redaxo/src/core/lib/form/form.php
- redaxo/src/core/lib/list.php
> rex_form/list nutzbar für 2. DB

- redaxo/src/addons/be_style/vendor_files.php
> add glyphicons woff2

- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/user/create.php
user:create für die console hinzugefügt
> console: user:create kommando hinzugefügt

- redaxo/src/addons/install/lang/de_de.lang
- redaxo/src/addons/install/lang/en_gb.lang
»Bitte in wenigen Minuten noch einmal probieren!«
Falls ihr einen anderen Text haben wollt, ändert ihn einfach direkt hier im PR.
Ich habe nur DE und EN gemacht. Wie geht man in solchen Situationen mit den anderen Sprachen um? Eigenmächtig mit Hilfe von z. B. Google Translate ergänzen ist vermutlich nicht angebracht. Wenn man es komplett auslässt, so wie ich jetzt, wird es aber vermutlich nie von Übersetzern entdeckt und nachgezogen, oder?
fixes #2509
> Installer: Hinweis bei Prüfsummenfehler ergänzt

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
> rex_sql: insert() ohne Values unterstützen

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
> @-Zeichen im Dateinamen erlauben, close #2507

- redaxo/src/core/lib/clang/clang.php
> count Methode um ignoreOffline ergänzt

- redaxo/src/addons/structure/plugins/content/lang/de_de.lang
- redaxo/src/addons/structure/plugins/content/lang/en_gb.lang
- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
> anzeigen ob das Modul verwendet wird

- redaxo/src/addons/install/lang/de_de.lang
- redaxo/src/addons/install/lang/en_gb.lang
- redaxo/src/addons/install/pages/settings.php
> Installer: Erklärungstext für Backups ergänzt

- redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
> MM: transparente GIFs mit workspace-Effekt gefixt

- redaxo/src/core/lib/select.php
> rex_select: Escaping fehlte

- phpstan.neon.dist
Refs https://github.com/redaxo/redaxo/pull/2579#issuecomment-471331373
> Neue phpstan warnings in Fragmenten ignorieren

- redaxo/src/addons/phpmailer/package.yml
https://github.com/redaxo/redaxo/issues/2583, fixed
> PHPMailer Help fix

- redaxo/src/addons/install/pages/packages.upload.php
> Markdown beim AddOn-Upload parsen

- redaxo/src/addons/mediapool/assets/mediapool.js
> Medienpool: Schließen nach Klick auf Übernehmen

- redaxo/src/addons/phpmailer/README.md
kleine Ergänzungen , Korrekturen
> PHPMailer: Readme kleine Ergänzungen , Korrekturen

- redaxo/src/core/pages/setup.php
siehe https://secure.php.net/supported-versions.php
> Setup: Nach EOL von php 7.1/7.2/7.3 warnen

- .travis.yml
So kann ich leichter von bugfix nach master hochmergen, wenn ich noch einen dritten Branch habe, den travis prüft.
So kann ich darin den Merge vorbereiten, durch travis checken lassen, und dann master auf den geprüften Stand bringen.
> travis: add temp branch

- redaxo/src/core/update.php
> R5.6 erfordern für Update

- redaxo/src/core/lib/login/perm.php
> Rechte case-insensitive sortieren

- redaxo/src/core/backend.php
Ungetestet 
Closes https://github.com/redaxo/redaxo/issues/2674
> asset-streaming: /assets/ rooted pfade untersützen

- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/cronjob/pages/log.php
- redaxo/src/addons/cronjob/pages/system.log.cronjob.php
closes https://github.com/redaxo/redaxo/issues/2639
> Cronjob log unter system/log anzeigen

- redaxo/src/addons/cronjob/lib/types/phpcode.php
> PHPCode-Cronjobs: Fehler abfangen

- redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php
> bearbeiten / löschen in Slice-Ansicht ausschreiben

- redaxo/src/addons/structure/lib/navigation.php
> rex_navigation: callback return instance of object

- redaxo/src/addons/structure/plugins/content/pages/content.php
> SLICE_ADD slice_id parameter wird nun korrekt als parameter übrergeben

- .travis.yml
see https://github.com/phpstan/phpstan-shim
> use phpstan/phpstan-shim to reduce conflict surface

- phpstan.neon.dist
- redaxo/src/core/lib/packages/addons/addon.php
- redaxo/src/core/lib/packages/interface.php
- redaxo/src/core/lib/packages/null.php
- redaxo/src/core/lib/packages/plugins/plugin.php
- redaxo/src/core/lib/util/i18n.php
Verwenden von variadics https://wiki.php.net/rfc/variadics
Ungetestet 
Streng gesehen ein **BC break**, vermutlich aber nicht relevant da das interface sehr speziell ist und eigentlich nur für interne core Nutzung gedacht
> Fix phpstan warning: Method rex_package_interface::i18n\(\) invoked with 2 parameters, 1 required

- redaxo/src/addons/media_manager/lang/de_de.lang
- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
closes: https://github.com/redaxo/redaxo/issues/2775
closes: https://github.com/redaxo/redaxo/issues/2052
> Convert2Image :: ImageMagick-Check und Hinweis als Prefix 

- redaxo/src/core/default.config.yml
closes https://github.com/redaxo/redaxo/issues/2744
> Verhindern dass man aus dem Backend ausgeloggt wird

- .travis.yml
- redaxo/src/core/lib/util/stream.php
> rex_stream: stream_set_option implementieren

- .travis.yml
> travis: trusty verwenden

- redaxo/src/addons/structure/plugins/content/lib/api_template.php
> getTemplatesForCategory: Korrektur für $ignore_inactive=false

- redaxo/src/addons/structure/lib/service_article.php
- redaxo/src/addons/structure/lib/service_category.php
> Cache korrekt löschen nach Prio-Setzung

- redaxo/src/addons/install/lib/api_core_update.php
> Fixed phpdoc

- redaxo/src/addons/mediapool/lib/media.php
> Remove assignment of undefined variable

- redaxo/src/core/lib/login/user.php
Keine schöne lösung aber mal so als Vorschlag weil mir nix besseres einfällt
> more specific phpdocs

- .kodiak.toml
Closes https://github.com/redaxo/redaxo/issues/2827
Doku zur konfig siehe https://github.com/chdsbd/kodiak
> Setup Kodiak Bot

- redaxo/src/addons/metainfo/lib/handler/handler.php
> added phpdoc

- redaxo/src/core/layout/top.php
> Setup: "Nicht angemeldet" in Header entfernt

- .gitignore.example
- redaxo/bin/release
> Vorlage für .gitignore

- redaxo/src/addons/mediapool/pages/sync.php
> Debug code entfernt

- redaxo/src/addons/metainfo/functions/function_metainfo.php
> Include-pfade vereinfacht

- redaxo/src/core/lib/form/elements/select.php
> phpdocs ergänzt

- redaxo/src/addons/metainfo/lib/input.php
Phpdocs in diesen basisklassen fixen viele psalm warnings
> rex_input: phpdocs ergänzt

- redaxo/src/addons/structure/lib/service_article.php
https://github.com/redaxo/redaxo/pull/2818
> unset() undefined var

- redaxo/src/core/lib/be/controller.php
ERROR: ParadoxicalCondition - redaxo\src\core\lib\be\controller.php:343:25 - Encountered a paradox when evaluating the conditionals ($setter==!callable) and ($setter==!callable)
if (is_callable($setter)) {
> fix psalm warning in be_controller

- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/metainfo/lib/input.php
- redaxo/src/addons/metainfo/lib/input/datetime.php
Closes https://github.com/redaxo/redaxo/issues/2834
> inline rex_input::factory() into call-sites (and deprecate it)

- redaxo/src/core/lib/list.php
> Fix phpdoc

- redaxo/src/core/lib/packages/addons/manager.php
> added phpdocs

- redaxo/src/addons/structure/pages/index.php
warnings siehe commit
Refs https://github.com/redaxo/redaxo/pull/2629
> fix phpstan warning bzgl. $template_select

- redaxo/src/addons/structure/lib/service_article.php
warnings siehe commit
refs https://github.com/redaxo/redaxo/pull/2629
> fixed phpstan warning bzgl. parent_id

- redaxo/src/addons/structure/lib/service_category.php
warnings siehe commit
refs https://github.com/redaxo/redaxo/pull/2629
> fix phpstan warnings bzgl. templates

- .travis.yml
da nun alle fixes im release sind die wir brauchen
> use stable psalm release

- redaxo/src/addons/mediapool/pages/media.detail.php
Refs https://github.com/redaxo/redaxo/pull/2629
Fixes phpstan warnings
------ --------------------------------------------- 
362  Line   addons/mediapool/pages/media.detail.php      
363 ------ --------------------------------------------- 
367  116    Variable $fheight might not be defined.      
368  116    Variable $fwidth might not be defined.       
369  123    Variable $rfwidth might not be defined.
> If Bedingungen vereinfacht

- redaxo/src/core/pages/setup.php
> Sprachen sortiert

- redaxo/src/addons/backup/lib/tar.php
Refs https://github.com/redaxo/redaxo/pull/2882
> Added phpdocs for rex_tar

- .travis.yml
- redaxo/src/addons/cronjob/lib/manager.php
Docs https://psalm.dev/docs/annotating_code/templated_annotations/
Refs https://github.com/redaxo/redaxo/issues/2931
> Added phpdoc to rex_cronjob_manager

- redaxo/src/addons/cronjob/lib/cronjob.php
Docs https://psalm.dev/docs/annotating_code/templated_annotations/
Refs https://github.com/redaxo/redaxo/issues/2931
> added phpdoc to rex_cronjob_form

- redaxo/src/addons/metainfo/lib/handler/media_handler.php
`setQuery` gefolgt von `getArray` sollte man nicht machen, da dann die Query immer doppelt ausgeführt wird.
> Queries wurden doppelt ausgeführt

- redaxo/src/addons/install/lib/packages.php
- redaxo/src/addons/install/lib/webservice.php
Ich hätte gerne ein paar mehr infos an die methoden gepackt, allerdings war mir der ablauf/die internals nicht überall klar
> install: added phpdocs

- redaxo/src/core/lib/sql/table.php
> Param afterColumn für ensureGlobalColumns hinzugefügt

- redaxo/src/core/lib/login/login.php
> Exception gelöscht um Whoops zu vermeiden

- redaxo/src/addons/phpmailer/README.de.md
- redaxo/src/addons/phpmailer/README.md
Added notice: 
https://github.com/redaxo/redaxo/issues/2960
> PHPMailer :: notice for empty body with SMTP

- redaxo/src/core/lib/rex.php
- redaxo/src/core/lib/system_report.php
- redaxo/src/core/pages/system.settings.php
> rex::getVersionHash(): Repo validieren

- .github/workflows/push.yml
- .travis.yml
> use GithubActions for psalm-analysis

- .github/workflows/push.yml
um diesen ewig langen und unnötigen forschrittsbalken loszuwerden
> use --no-progress for phpstan

- .github/workflows/csfix.yml
Egal ob wir auf label-basierte events umstellen oder nicht: mit den Änderungen sollte die action flotter werden -> kürzere queue
> Optimize csfixing action for speed

- .github/workflows/csfix.yml
https://stedolan.github.io/jq/manual/#Invokingjq
> csfix GithubAction: check for status code instead of output

- .github/workflows/csfix.yml
since we no longer use comments, but issue based actions, we no longer need to curl the api for metainfo
> csfix GithubAction: simplify

- README.de.md
- README.md
Forum isn’t in use any more, also user registration is disabled.
> docs: remove forum section

- redaxo/src/addons/structure/pages/index.php
Proposal to remove table row containing the level up icon completely, as discussed in issue.
(At least from core team @dergel @tbaddade and @gharlan voted for this solution.)
fixes #774
> Structure: remove '..' level up icon (#774)

- redaxo/src/addons/structure/lib/select_template.php
fix notice
**ErrorException:** Undefined variable: selected
**File:** redaxo/src/addons/structure/lib/select_template.php
**Line:** 76
<details>
<summary>Stacktrace</summary>
| Function                                         | File                                                | Line     |
| ------------------------------------------------ | --------------------------------------------------- | -------- |
| rex_error_handler::handleError                   | redaxo/src/addons/structure/lib/select_template.php | 76       |
| rex_template_select->setSelectedFromStartArticle | redaxo/src/addons/structure/pages/index.php         | 411      |
| include                                          | redaxo/src/core/lib/packages/package.php            | 228      |
| rex_package->includeFile …
> structure: fix notice

- redaxo/src/core/fragments/core/page/section.php
> section Fragment angepasst, kann Attribute aufnehmen

- redaxo/src/core/lib/sql/table.php
- redaxo/src/core/tests/sql/sql_table_test.php
rex_sql_table kann nun auch mit einer weiteren Datenbank verwendet werden.
> rex_sql_table --> Verwendung weiterer Datenbanken möglich (dbid)

- .travis.yml
To have a more recent datapoint
> Test mariadb 10.4

- .github/workflows/push.yml
Closes https://github.com/redaxo/redaxo/issues/3064
> Update to psalm 3.8.1

- redaxo/src/core/lib/response.php
> ETag in Safari nicht mehr deaktivieren

- redaxo/src/core/lib/login/user.php
> rex_user::isAdmin beschleunigt

- redaxo/src/core/lib/list.php
> Trying to access array offset on value of type null
> PHP 7.4: Notice vermeiden

- .github/workflows/push.yml
refs https://github.com/shivammathur/setup-php/issues/136#issuecomment-570628256
> GithubAction: activate `@verbose` mode to debug ext-intl issues

- SECURITY.md
Stimmt die E-Mail-Addy?
fixes #2756
> Github: Security Policy

- .github/workflows/push.yml
Inspired by the vimdeo/psalm shepherd.yml
> psalm: use 2 threads in GithubAction

- .github/workflows/csfix.yml
See https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
> GithubAction: add PAT to csfix action

- redaxo/src/addons/structure/lib/navigation.php
> rex_navigation Ankerinhalt bearbeitbar machen

- redaxo/src/core/pages/setup.php
Siehe https://www.php.net/supported-versions.php
> Setup warnung wenn php 7.4 verwendet wird nach EOL

- .github/workflows/csfix.yml
- .github/workflows/push.yml
See https://github.com/actions/checkout/releases/tag/v2.0.0
> GithubActions: update actions/checkout to v2

- redaxo/src/addons/structure/plugins/version/boot.php
> Use constant instead of magic value

- redaxo/src/addons/mediapool/lib/media.php
- redaxo/src/addons/mediapool/tests/media_test.php
> rex_media: consistent has/getValue

- redaxo/src/addons/structure/lib/service_article.php
- redaxo/src/addons/structure/lib/service_category.php
> Prio-Sync nur, wenn Prio sich geändert hat

- redaxo/src/addons/structure/pages/index.php
nach #2977 bekommt man eine Notice auf der Structure Seite.
**ErrorException:** Undefined variable: function
**File:** redaxo/src/addons/structure/pages/index.php
**Line:** 104
<details>
<summary>Stacktrace</summary>
| Function                              | File                                        | Line     |
| ------------------------------------- | ------------------------------------------- | -------- |
| rex_error_handler::handleError        | redaxo/src/addons/structure/pages/index.php | 104      |
| include                               | redaxo/src/core/lib/packages/package.php    | 228      |
| rex_package->includeFile              | redaxo/src/core/lib/be/controller.php       | 462      |
| rex_be_controller::includePath        | redaxo/src/core/lib/be/controller.php       | …
> Structure context: bugfix

- redaxo/src/addons/structure/plugins/version/boot.php
* Toolbar nur noch über dem Bereich, auf den es sich bezieht. closes #2709
* Im Slice-Edit-Bereich und bei den Funktionen, da es sich dort auch auf "Inhalt kopieren" bezieht
* Aus Platzgründen aktuelle Version nicht mehr in groß links, sondern im Versions-Dropdown in fett
* Weiteres Issue erledigt sich hiermit mit: fixes #2195
Vorher:
Nachher:
> Version-Toolbar besser platzieren

- redaxo/src/addons/structure/pages/index.php
fixes: https://github.com/redaxo/redaxo/issues/2715
> adds article-id to article tr

- redaxo/src/core/pages/setup.php
Ich finde diese Reihenfolge natürlicher.
> Setup: DB-Name nach Host/User/Passwort

- redaxo/src/core/tests/util/timer_test.php
See https://github.com/redaxo/redaxo/pull/3172/checks?check_run_id=397492145
> Fix rex_timer::measure test

- redaxo/src/addons/phpmailer/README.de.md
- redaxo/src/addons/phpmailer/README.md
Ergänzt die Readme um Archivierung und Logging
> PHPMailer: README E-Mail-Log DE

- redaxo/src/core/pages/setup.php
> Setup: DB-Werte trimmen

- .github/workflows/push.yml
initial errors do no longer repro..
> use stable shivammathur/setup-php@v1 again

- .github/workflows/push.yml
- redaxo/src/core/tests/login/backend_login_test.php
- redaxo/src/core/tests/util/timer_test.php
Closes https://github.com/redaxo/redaxo/issues/3169
> Added phpunit problem matcher

- redaxo/src/addons/cronjob/lib/manager.php
- redaxo/src/addons/cronjob/pages/log.php
- redaxo/src/addons/cronjob/update.php
- redaxo/src/addons/phpmailer/README.de.md
- redaxo/src/addons/phpmailer/README.md
- redaxo/src/addons/phpmailer/boot.php
- redaxo/src/addons/phpmailer/lib/mailer.php
- redaxo/src/core/lib/util/logger.php
- redaxo/src/core/lib/util/path.php
- redaxo/src/core/lib/util/path_default_provider.php
- redaxo/src/core/update.php
> Zentraler Log-Ordner redaxo/data/log

- redaxo/src/addons/structure/plugins/content/assets/content.js
- redaxo/src/addons/structure/plugins/content/boot.php
- redaxo/src/core/assets/standard.js
Closes https://github.com/redaxo/redaxo/issues/815
> toggle Status der Sidebar Panels in localstorage speichern

- redaxo/src/addons/be_style/update.php
> be_style: update.php für customizer reinstall

- redaxo/src/addons/media_manager/lang/de_de.lang
- redaxo/src/addons/media_manager/lang/en_gb.lang
- redaxo/src/addons/media_manager/lang/es_es.lang
- redaxo/src/addons/media_manager/lang/sv_se.lang
- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
> ImageMagick-Hinweis korrigiert

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
> Mimetype-Bestimung beim MP-Sync korrigiert

- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/lib/select_template.php
- redaxo/src/addons/structure/plugins/content/package.yml
https://github.com/redaxo/redaxo/pull/961#issuecomment-582846318
> Metainfo: Im Template-Filter auch Templates mit Kategoriebeschränkung listen

- .github/workflows/push.yml
- redaxo/src/addons/mediapool/pages/media.list.php
- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/response.php
- redaxo/src/core/lib/sql/sql.php
Ich habe mal angefangen, ein paar der von psalm gemeldeten Probleme zu lösen.
Eins scheint mir hingegen ein Bug zu sein: https://github.com/vimeo/psalm/issues/2838
> Fix psalm errors

- phpstan.neon.dist
- psalm-utils.php
- redaxo/src/addons/backup/lib/backup.php
- redaxo/src/addons/backup/lib/tar.php
- redaxo/src/addons/backup/vendor/tar.php
- redaxo/src/addons/cronjob/lib/form.php
- redaxo/src/addons/cronjob/lib/manager_sql.php
- redaxo/src/addons/install/lib/api_core_update.php
- redaxo/src/addons/structure/lib/structure_element.php
- redaxo/src/core/lib/packages/interface.php
- redaxo/src/core/lib/packages/manager.php
fixes #3300
Edit: closes #3281
> fix psalm and phpstan

- .idea/inspectionProfiles/Project_Default.xml
- .idea/redaxo.iml
Da wurden Ordner zu global ausgeschlossen.
> PhpStorm-Settings aktualisiert

- redaxo/src/core/lib/setup/setup.php
- redaxo/src/core/pages/setup.php
@bloep kannst du die integration mit dem consolen basierten setup machen?
relates to https://github.com/redaxo/redaxo/pull/3310
> refactored EOL checks into rex_setup class for re-use in redaxo console

- redaxo/src/addons/media_manager/boot.php
- redaxo/src/addons/mediapool/lib/media.php
- redaxo/src/addons/mediapool/lib/media_category.php
- redaxo/src/addons/users/boot.php
- redaxo/src/core/lib/packages/addons/addon.php
- redaxo/src/core/lib/packages/null.php
- redaxo/src/core/lib/packages/plugins/plugin.php
- redaxo/src/core/tests/base/instance_list_pool_trait_test.php
- redaxo/src/core/tests/util/i18n_test.php
closes #2729 
(fyi, mit regex gesucht und per hand ersetzt)
> convert string callable to array notation

- composer.json
- phpstan.neon.dist
- redaxo/src/core/tests/var/var_config_test.php
- redaxo/src/core/tests/var/var_property_test.php
refs https://github.com/redaxo/redaxo/issues/3131
> actviate phpstan for core-tests

- redaxo/src/addons/structure/plugins/content/lib/api_template.php
- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
- redaxo/src/addons/structure/plugins/content/lib/var_template.php
closes https://github.com/redaxo/redaxo/issues/3288
> REX_TEMPLATE_KEY implementiert

- redaxo/src/addons/cronjob/lang/de_de.lang
- redaxo/src/addons/cronjob/lib/manager.php
- redaxo/src/addons/cronjob/pages/log.php
> add cronjob environment information to log

- redaxo/src/addons/structure/plugins/content/pages/templates.php
refs https://github.com/redaxo/redaxo/issues/910
> simplify template already exists validation

- redaxo/src/core/lib/system_report.php
closes https://github.com/redaxo/redaxo/issues/2716
das hier noch reportete html wird in einem separaten PR gefixed
> report php/mysql security checks in sysreport

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
closes https://github.com/redaxo/redaxo/issues/3013
> added category_id param to MEDIA_ADDED, MEDIA_UPDATED

- redaxo/src/addons/cronjob/pages/log.php
refs https://github.com/redaxo/redaxo/issues/2768
> fixed rendering of cronjob.log rex_editor button

- redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
closes https://github.com/redaxo/redaxo/issues/1345
wirklich geschlossen wird #1345 durch die Änderungen eigentlich nicht.. allerdings fällt mir auch kein besserer wert als `- off -` ein, der ohne übersetzungen an dieser stelle gut funktionieren könnte.
ich finde es nicht als wichtiges todo, daher würde ich das issue mit den Änderungen hier schließen
> extract constants

- redaxo/src/core/lib/util/file.php
closes https://github.com/redaxo/redaxo/issues/2544
> implement rex_file::move()

- redaxo/src/core/lib/console/command_loader.php
- redaxo/src/core/lib/console/package/delete.php
bei den ganzen `package` commands die es gibt, habe ich irgendwie das `package:delete` vergessen 🙄 
`redaxo/bin/console package:delete <package-id>`.
> console: added package:delete

- redaxo/src/addons/phpmailer/pages/config.php
Wrong translation key corrected
> phpmailer_log_info > phpmailer_archive_info

- phpstan.neon.dist
- redaxo/src/addons/install/lib/package/package_update.php
- redaxo/src/addons/install/lib/packages.php
- redaxo/src/addons/mediapool/lib/media_category.php
- redaxo/src/addons/mediapool/lib/media_category_select.php
- redaxo/src/addons/metainfo/lib/input.php
- redaxo/src/addons/structure/lib/navigation.php
- redaxo/src/addons/structure/lib/select_category.php
- redaxo/src/addons/structure/lib/structure_element.php
- redaxo/src/addons/users/lib/role.php
phpstan level erhöht und entstandene warnings gefixed
> Fix phpdocs

- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
- redaxo/src/addons/structure/plugins/content/pages/templates.php
> Module/Templates löschen: Fehlermeldung bei Verwendung in Artikeln vereinheitlicht

- redaxo/src/core/pages/setup.php
- redaxo/src/core/pages/setup.step1.php
- redaxo/src/core/pages/setup.step2.php
- redaxo/src/core/pages/setup.step3.php
- redaxo/src/core/pages/setup.step4.php
- redaxo/src/core/pages/setup.step5.php
- redaxo/src/core/pages/setup.step6.php
Und die Params immer als URL-Parameter setzen, nicht als hidden inputs.
Damit man nicht plötzlich nur auf `index.php` ist, ohne Parameter.
> Setup: mit rex_context arbeiten

- redaxo/src/addons/install/lib/archive.php
#2286
@aeberhard Kannst du es mit dieser Version testen, ob du damit den Core aktualisieren kannst (von 5.8.1 zu 5.9), und ob Addon-Downloads/Updates über den Installer aber auch noch funktionieren?
> Installer: Optimierung für Windows

- redaxo/src/core/lib/error_handler.php
> Warnings: HTML nicht escapen

- redaxo/src/addons/structure/lib/structure_element.php
Die zugehörigen Getter geben an, ints zurückzugeben, tatsächlich geben sie aber int-strings.
> rex_category/rex_article: Int-Values wirklich als int

- redaxo/src/addons/install/pages/index.php
Arg, da habe ich scheinbar die letzte Version gar nicht mehr getestet..
> Installer: $markdown-Variable verfügbar gemacht

- psalm.xml
- redaxo/src/core/.phpstorm.meta.php
- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/rex.php
- redaxo/src/core/lib/setup/setup.php
- redaxo/src/core/lib/system_report.php
- redaxo/src/core/lib/util/formatter.php
- redaxo/src/core/lib/util/string.php
- redaxo/src/core/lib/util/version.php
- redaxo/src/core/pages/system.settings.php
- redaxo/src/core/tests/util/string_test.php
- redaxo/src/core/tests/util/version_test.php
> Versions-Funktionen in rex_version verschoben

- redaxo/src/addons/be_style/vendor_files.php
> bootstrap-select: *.map-datei korrigiert

- redaxo/src/addons/structure/plugins/content/pages/content.functions.php
fixes #3410
Dieser PR macht Änderungen aus diesem Commit teils rückgängig, bzw. korrigiert sie:
https://github.com/redaxo/redaxo/commit/0c47eac8f1914475be95e513d7e78b9e57188001#diff-1c0dce87b8b471daceb160672e824c55
> Artikel-Funktionen korrigiert

- redaxo/src/addons/mediapool/pages/index.php
> Medienpool: assert-Warning vermeiden

- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
> Module-Key: Korrekte Umgang mit leerem Key

- redaxo/src/addons/phpmailer/README.de.md
- redaxo/src/addons/phpmailer/README.md
Ich kapiere noch nicht, was AntiXSS da genau für ein Problem mit hat.
Aber in der neuen Variante geht es.
Ich versuche das nochmal genauer zu analysieren. Aber erstmal so gefixt.
> PHPMailer-Readme kompatibel zu antiXss gemacht

- composer.json
- psalm.xml
Dank des Fixes: 
https://github.com/vimeo/psalm/issues/2890
> psalm: activate PossiblyUndefinedMethod

- .github/ISSUE_TEMPLATE/---bug-report.md
Please have a look at the English translation as I'm not a native speaker.
closes #3411
> suggest to insert stacktrace / whoops

- composer.json
- redaxo/src/core/lib/form/form_base.php
- redaxo/src/core/lib/login/user.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/lib/var/var.php
Als Vorbereitung für #3446, die Dinge, die ohne Code-Änderung möglich sind.
> Fix docs, add psalm annotations

- .github/workflows/push.yml
Nun auch für den bugfix-branch
> actions: start mysql manually

- redaxo/src/addons/users/package.yml
- redaxo/src/addons/users/pages/users.php
Im EP USER_UPDATED war die ID immer 0
> EP USER_UPDATED: Parameter korrigiert

- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
- redaxo/src/addons/media_manager/package.yml
> convert2img: colorspace korrekt umwandeln

- redaxo/src/addons/users/lang/de_de.lang
- redaxo/src/addons/users/lang/en_gb.lang
- redaxo/src/addons/users/lang/es_es.lang
- redaxo/src/addons/users/lang/pt_br.lang
- redaxo/src/addons/users/lang/sv_se.lang
- redaxo/src/addons/users/pages/users.php
Ist noch ein Überrest aus R4, die Property pswfunc gibt es in R5 gar nicht. Der Text erschien somit auch nie.
> pswfunc-Rest entfernen

- redaxo/src/addons/debug/lib/debug.php
> Debug: use cache folder

- redaxo/src/addons/debug/README.md
> debug: initiale readme

- redaxo/src/addons/debug/README.md
closes https://github.com/redaxo/redaxo/issues/3522
> debug: added example to readme

- psalm.xml
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/structure/lib/article.php
- redaxo/src/addons/structure/lib/category.php
- redaxo/src/addons/users/lib/role.php
- redaxo/src/core/lib/form/form.php
- redaxo/src/core/lib/form/form_base.php
- redaxo/src/core/lib/list.php
- redaxo/src/core/lib/login/role.php
- redaxo/src/core/lib/login/user.php
- redaxo/src/core/lib/util/log_file.php
Die neue Psalm-Version meldet einige neue Fehler..
> psalm: Anpassungen für neue Version

- redaxo/src/core/lib/system_report.php
**Vorher:**
<details>
<summary>System report (REDAXO 5.11.0-dev#975010ade, PHP 7.4.4)</summary>
| REDAXO        |                      |
| ------------: | :------------------- |
|       Version | 5.11.0-dev#975010ade |
| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.4      |
|       OPcache | yes        |
|        Xdebug | no         |
| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.4.11 |
| Character set | utf8            |
| Server        |                |
| ------------: | :------------- |
|            OS | Darwin         |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.43  |
| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/13.1 |
| …
> Systembericht: DB-Version in Zusammenfassung

- .github/workflows/push.yml
Relates to https://github.com/vimeo/psalm/pull/3184
> GithubAction: added psalm result cache

- redaxo/src/addons/debug/lib/debug.php
> debug: fix notice

- redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Damit es möglich wird, nur aktive Slices abzurufen.
> Slice Status in rex_article_slice berücksichtigen

- redaxo/src/core/lib/sql/sql.php
Review ohne whitespaces: https://github.com/redaxo/redaxo/pull/3561/files?diff=unified&w=1
> rex_sql: properly restore DBID on Exceptions in setDBQuery

- .github/workflows/push.yml
Which also utilizes the recently added caching
Refs https://github.com/vimeo/psalm/issues/3212#issue-604518095
> psalm: analyse only changed files

- redaxo/src/addons/metainfo/lib/handler/handler.php
> Metainfo: Umgang mit Attributen korrigiert

- redaxo/src/addons/structure/plugins/content/lang/de_de.lang
- redaxo/src/addons/structure/plugins/content/pages/content.php
> Fehlermeldung, wenn Artikel nicht existiert

- redaxo/src/core/lib/fragment.php
> rex_fragment: neue Methode getSubfragment

- redaxo/src/addons/debug/boot.php
> Debug: load clockwork frontend only if admin user is logged in.

- redaxo/src/core/pages/system.log.redaxo.php
Der Dateipfad ist nun verlinkt.
> Log: Datei mit Editor-Url verlinken

- composer.json
closes https://github.com/redaxo/redaxo/issues/3651
> update psalm to the latest release

- redaxo/src/addons/users/pages/users.php
Der Fehler kam hier rein: https://github.com/redaxo/redaxo/commit/f6ad3e4d165fbce741f16543282252fa7a88adf3
> Benutzerverwaltung: Korrektur Unterscheidung ob Selbsteditierung

- composer.json
https://github.com/phpstan/phpstan-phpunit 
https://github.com/phpstan/extension-installer
> Added phpstan/phpstan-phpunit plugin

- redaxo/src/addons/debug/boot.php
- redaxo/src/addons/debug/lib/debug_clockwork.php
> Debug: ensure clockwork storage path after cache clear

- redaxo/src/core/lib/console/setup/run.php
> Setup: rex_backup-Klasse verfügbar machen

- redaxo/src/addons/debug/lib/api_debug.php
> Debug: "Headers already sent" vermeiden

- redaxo/src/addons/structure/pages/index.php
> leere Zeile in Artikelliste anzeigen

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lang/es_es.lang
- redaxo/src/core/lang/nl_nl.lang
- redaxo/src/core/lang/sv_se.lang
- redaxo/src/core/lib/setup/setup.php
- redaxo/src/core/update.php
> Datenbank: Mindestens MySQL 5.6 / MariaDB 10.1

- .github/workflows/rexlint.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
- .github/workflows/visual-tests.yml
like it already works on travis
inspired by https://github.com/veggiemonk/skip-commit/issues/5
> added support for `[ci skip]` commit keyword in Github Actions

- redaxo/src/addons/install/package.yml
- redaxo/src/addons/metainfo/package.yml
refs https://github.com/redaxo/redaxo/pull/3857/files#r484053399
see https://github.com/redaxo/redaxo/pull/3399
> rex core mindest version anheben

- redaxo/src/core/lib/util/logger.php
- redaxo/src/core/pages/system.log.redaxo.php
fixed #3798 
hacktoverfest event 2020
> Log: Darstellung Info-Meldungen korrigiert

- .github/workflows/cs-fix.yml
- .github/workflows/visual-tests.yml
- redaxo/src/core/pages/packages.php
Ich möchte hier jetzt selbst nochmal bisschen testen.
> Actions: Umgang mit Forks

- redaxo/src/addons/debug/lib/debug_clockwork.php
closes #3805
closes https://github.com/redaxo/redaxo/pull/3896
> debug: compress files in storage

- redaxo/src/core/tests/console/config/get_test.php
analog https://github.com/redaxo/redaxo/pull/3919
> tests: normalize newlines to make tests work consistently on windows

- redaxo/src/addons/cronjob/lang/de_de.lang
- redaxo/src/addons/cronjob/lang/en_gb.lang
- redaxo/src/addons/cronjob/lang/es_es.lang
- redaxo/src/addons/cronjob/lang/sv_se.lang
- redaxo/src/addons/cronjob/pages/cronjobs.php
Neu: 
closes https://github.com/redaxo/redaxo/issues/3810
> CronJob: Absoluten Pfad zum Cron ausgeben

- .github/workflows/mariadb-tests.yml
- .travis.yml
refs https://github.com/redaxo/redaxo/issues/3926
> GithubAction: added mariadb 10.1 test

- redaxo/src/core/functions/function_rex_globals.php
- redaxo/src/core/lib/request.php
- redaxo/src/core/lib/util/type.php
FIXED #3994 ich hoffe ich habe die Aufgabe korrekt verstanden
wollte wegen Hacktoberfest einfach mal sicher gehen :D
> phpdocs übertragen

- redaxo/src/core/lib/util/formatter.php
Refs https://github.com/redaxo/redaxo/issues/3976
> added note regarding 32bit unix timestamp limitation

- redaxo/src/addons/phpmailer/lang/de_de.lang
- redaxo/src/addons/phpmailer/lang/en_gb.lang
> Lang, Perm: PHPMailer added German/english

- phpstan.neon.dist
This means it can hold arbitrary properties
> define rex_fragment as a universal object crate

- .github/workflows/static-analysis.yml
- composer.json
make sure we get an always up 2 date result
related upstream isse: https://github.com/vimeo/psalm/issues/4623
> don't use psalm cache while taint analysis

- redaxo/src/addons/backup/pages/import.server.php
- redaxo/src/addons/backup/pages/import.upload.php
- redaxo/src/core/lib/util/path.php
- redaxo/src/core/pages/setup.php
gefunden während https://github.com/redaxo/redaxo/pull/4062
> setup: sanitize import filename to prevent path-traversal attacks

- redaxo/src/core/lib/fragment.php
> fix phpstorm duplicate method error

- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
ohne konrekten case aufgefallen
> make sure we don't miss to close output-buffers when module-output throws

- redaxo/src/addons/structure/plugins/content/lib/article_content_base.php
slice-rendering logic 1:1 via phpstorm in separate methode refactored.
ziel dabei war analog https://github.com/redaxo/redaxo/pull/4071 ein übersichtliches ob_* handling zu bekommen mit ordentlichem exception-handling.
> extract slice-rendering into separate method

- redaxo/src/core/lib/setup/import.php
- redaxo/src/core/pages/setup.php
der besser fix für https://github.com/redaxo/redaxo/pull/4064
> moved sanitizing of importName into rex_setup_importer::loadExistingImport()

- redaxo/src/core/lib/sql/util.php
aufgefallen im rahmen von https://github.com/redaxo/redaxo/pull/4086
> rex_sql: validate filename in importDump() method

- .github/workflows/static-analysis.yml
- .tools/psalm/baseline-taint.xml
- composer.json
- psalm.xml
create a `composer taint-baseline`  composer script to regenerate the taint-baseline
https://psalm.dev/docs/running_psalm/command_line_usage/
https://psalm.dev/docs/security_analysis/#using-baseline-with-taint-analysis
> added a psalm taint-baseline

- .github/workflows/sarif-report.yml
- .github/workflows/static-analysis.yml
doesn't make sense to upload the report in work-in-progress pull requests.
follow up to https://github.com/redaxo/redaxo/pull/4074
> upload sarif report only for release-branches and on schedule

- .tools/psalm/baseline.xml
Keine Ahnung, ob die Dinge entfallen können wegen psalm update, oder wegen phpdocs, die inzwischen hinzu kamen.
> psalm: baseline aktualisiert

- .github/workflows/sarif-report.yml
- .github/workflows/static-analysis.yml
Ich glaube, die Actions müssen das Setup gar nicht durchführen. Mal probieren.
> Statische Analyse: Kein Setup notwendig

- .tools/psalm/baseline-taint.xml
- redaxo/src/core/functions/function_rex_escape.php
`rex_escape` wurde noch gar nicht als escaper erkannt scheinbar.
> rex_escape als escaper markiert

- .tools/phpstan/baseline.neon
- redaxo/src/addons/structure/plugins/content/lib/select_template.php
Property rex_template_select\\:\\:\\$templates \\(array\\<string\\>\\) in isset\\(\\) is not nullable\\.
> fix phpstan warning

- .tools/phpstan/baseline.neon
- redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
> removed unused $options property in rex_effect_workspace

- .tools/phpstan/baseline.neon
- redaxo/src/core/lib/clang/clang.php
> fix phpstan warnings

- .tools/phpstan/baseline.neon
- redaxo/src/core/lib/list.php
> rex_list: removed unused property $query

- .tools/phpstan/baseline.neon
- redaxo/src/core/lib/form/elements/prio.php
> rex_form_prio_element: removed unused property primaryKey

- .github/workflows/static-analysis.yml
- .tools/psalm/baseline.xml
> Actions: Prüfen, ob psalm baseline aktuell

- .tools/rector/rector.php
- composer.json
ich will das tool nicht im dev prozess verankern wie alle anderen tools, aber zumindest die config im repo anlegen damit ich es lokal gut nutzen kann und damit die ein oder andere adhoc code transformation durchführen
> added initial rector config

- .tools/rector/rector.php
mein lokales setup funktioniert jetzt, daher konnte ich es mittlerweile testen
> rector: make sure we get php 7.3 compatible code

- redaxo/src/core/lib/extension.php
@staabm So meinte ich es, ganz ohne Template.
> rex_extension: add docs

- redaxo/src/addons/backup/lib/backup.php
> backup import: Cache wurde nicht gelöscht, und Erfolgsmeldung war rot

- redaxo/src/core/lib/response.php
der enstandene code ist nicht equivalent zum ursprungs code.
siehe https://github.com/redaxo/redaxo/pull/4123/files#r532711837
> revert changes from #4123 in response.php

- redaxo/src/addons/media_manager/pages/types.php
- redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
die konstante gibts seit R5.0
https://github.com/redaxo/redaxo/commit/6b0c5766b622bc5a5526cd900d83ef1438925541#diff-e368662f7d4923ad1934d05530e0df6e7a88388ec27442f77a3487f2a9825f76R14
> use `rex_sql::FORMAT_DATETIME`

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
https://github.com/redaxo/redaxo/pull/4153#pullrequestreview-545707633
> rex_sql::getValue: support scalar types only

- redaxo/src/core/lib/setup/setup.php
See https://www.php.net/supported-versions.php
> added php 8.0 end of life handling

- redaxo/src/core/lib/setup/setup.php
Roadmap of mariadb/mysql see changed lines
> Added mariadb 10.5 / mysql 8.0 end of life  handling

- .github/tests-visual/visual-record.js
- .github/workflows/chatops.yml
- .github/workflows/visual-tests.yml
closes https://github.com/redaxo/redaxo/issues/4185
the actual implementation can only be tested after merge, because repository dispatch events don`t work in the PR the are beeing added.
> github actions: added /visual-test chatcommand

- .github/workflows/visual-tests.yml
follow up to https://github.com/redaxo/redaxo/pull/4190
> github actions: try to commit changes on repo-dispatch /visual-test

- composer.json
closes https://github.com/redaxo/redaxo/issues/4203
> fix composer bash-scripts on windows

- .tools/psalm/baseline-taint.xml
- redaxo/src/addons/cronjob/pages/cronjobs.php
Tatsächlich können hier glaube ich keine Usereingaben an den Stellen landen, aber das kann psalm nicht erkennen.
Aber ich denke, das Escaping ist hier auch trotzdem nicht verkehrt, sicher ist sicher.
> cronjob: escaping

- redaxo/src/addons/metainfo/lib/table_expander.php
Nicht so ganz kritisch hier, da nur im Adminbereich.
> metainfo: prepared statements nutzen

- redaxo/src/core/packages.php
> measure boot time of each package individually

- redaxo/src/addons/phpmailer/package.yml
added errormail - default setting
> PHP-Mailer: Adding default setting errormail

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/lang/es_es.lang
- redaxo/src/core/lang/it_it.lang
- redaxo/src/core/lang/nl_nl.lang
- redaxo/src/core/lang/pt_br.lang
- redaxo/src/core/lang/sv_se.lang
die dateinamen passen noch immer noch 100%, da wir teilweise pages aufgespalten haben, aber zumindest die ordner angabe stimmt jetzt
> fixed comments in lang files

- redaxo/src/addons/phpmailer/pages/checkmail.php
Error and success messages via rex_view::error / rex_view::success
> PHPMailer: Checkmail success / error via rex_view

- redaxo/src/core/pages/packages.help.php
> Help: externe support page markieren

- redaxo/src/addons/media_manager/lib/media_manager.php
- redaxo/src/addons/media_manager/pages/types.php
closes https://github.com/redaxo/redaxo/issues/2435
> media-manager: a system-types' name can no longer be changed

- redaxo/src/core/pages/system.log.redaxo.php
damit logfiles nicht via XSS gelöscht/heruntergeladen werden können
> system-log: add csrf protection

- redaxo/src/core/lib/var/var.php
- redaxo/src/core/tests/var/var_test.php
> rex_vars: Ziffern im Namen erlauben

- .github/workflows/chatops.yml
- .github/workflows/cs-fix.yml
- .github/workflows/styles-compile.yml
- .github/workflows/visual-tests.yml
- redaxo/src/core/lib/rex.php
Ich habe mal einen separaten Bot-User angelegt für unsere Actions: https://github.com/rex-bot
> Use rex-bot for actions

- redaxo/src/core/pages/system.settings.php
closes: https://github.com/redaxo/redaxo/issues/4402
Führt einen redirect aus, wenn debug mode aktiviert ist.
> Visuelles Feedback beim Wechsel des Debug-Modus

- redaxo/src/addons/media_manager/lib/effects/effect_image_properties.php
closes #1565
Habe mich also erstmal für die Variante 2 entschieden von https://github.com/redaxo/redaxo/issues/1565#issuecomment-354758746.
Löst auch https://github.com/redaxo/redaxo/pull/4433#discussion_r577118607 (/cc @aeberhard).
> MM-Effekt image_properties: gd-resource erzwingen

- redaxo/src/core/lib/console/setup/run.php
> setup:run: Bei Fehler abbrechen

- redaxo/src/core/lib/error_handler.php
Fände ich besser, so bleibt der Whoops stehen und man kann ihn auch noch selbst weiter analysieren.
> "Report a bug" in neuem Tab öffnen

- .tools/psalm/baseline.xml
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/users/lib/select_element.php
- redaxo/src/core/lib/sql/sql.php
closes #4474
Ich bin jetzt nochmal alle Stellen mit den neuen string-functions durchgegangen, und hab nach bestem Wissen geschaut, ob dort null-values möglich sind.
> handle null values for string functions

- redaxo/src/core/lib/response.php
> Server-Timing-Header nicht mehr senden

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/pages/setup.php
> Setup: Schon bestehende DB-Verbindung schließen

- redaxo/src/core/lib/select.php
- redaxo/src/core/lib/sql/sql.php
phpdoc konkretisieren um db-queries klarer darzustellen.
refs https://github.com/redaxo/redaxo/pull/4528#issuecomment-790768877
> added db-query related phpdocs

- redaxo/src/core/lib/be/controller.php
motivation:
```
93% redaxo/src/core/lib/be/controller.php (37 mixed)
```
> rex_be_controller: more precise phpdoc

- .tools/psalm/baseline-taint.xml
- redaxo/src/core/boot.php
- redaxo/src/core/lib/util/path.php
motivation:
coverage vorher lt. https://github.com/redaxo/redaxo/runs/2038181858?check_suite_focus=true
```
49% redaxo/src/core/lib/util/path.php (50 mixed)
```
> rex_path: added phpdoc

- redaxo/src/addons/media_manager/lib/effects/effect_resize.php
Fixed das Problem "undefined index height/width" wenn z.B nur eines der beiden Werte gesetzt ist.
> check if params width/height are set

- redaxo/src/addons/structure/plugins/content/lib/article_slice.php
Da im slack heut die frage kam „ was passiert wenn ich da true übergeben, bei dem bool parameter“
> more precise phpdoc

- .tools/psalm/baseline.xml
- redaxo/src/addons/media_manager/lib/effect_abstract.php
- redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php
- redaxo/src/addons/media_manager/lib/effects/effect_crop.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_blur.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_colorize.php
- redaxo/src/addons/media_manager/lib/effects/effect_filter_sharpen.php
- redaxo/src/addons/media_manager/lib/effects/effect_flip.php
- redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
- redaxo/src/addons/media_manager/lib/effects/effect_insert_image.php
- redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
- redaxo/src/addons/media_manager/lib/effects/effect_resize.php
- redaxo/src/addons/media_manager/lib/effects/effect_rotate.php
- redaxo/src/addons/media_manager/lib/effects/effect_rounded_corners.php
- redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
- redaxo/src/addons/media_manager/lib/managed_media.php
- redaxo/src/addons/media_manager/pages/effects.php
Eigentlich wollte ich den PR nicht so groß werden lassen, aber irgendwie zogen immer Änderungen andere Änderungen nach sich, und wurde immer größer.
> media manager: more types

- redaxo/src/addons/structure/plugins/content/lib/article_content.php
Aus https://github.com/redaxo/redaxo/pull/4580#discussion_r598242676
> Make sure we don‘t leak a output-buffer on exceptions

- .tools/psalm/baseline.xml
- redaxo/src/core/boot.php
- redaxo/src/core/lib/util/url.php
> rex_url: phpdocs

- redaxo/src/core/lib/sql/sql.php
The same expression is alteady checked tn the previous elseif
triggered by https://github.com/redaxo/redaxo/pull/4612
> removed dead code

- redaxo/src/addons/backup/lib/backup.php
- redaxo/src/addons/backup/pages/export.php
- redaxo/src/addons/backup/pages/import.server.php
- redaxo/src/addons/backup/pages/import.upload.php
Aufgefallen per https://github.com/redaxo/redaxo/pull/4605
> psalm: remove unused vars

- redaxo/src/addons/phpmailer/pages/config.php
Korrektur for-Attribut für E-Mail-Archivierung
> Korrektur for-Attribut für E-Mail-Archivierung

- .github/workflows/code-style.yml
- .github/workflows/rexlint.yml
- .github/workflows/static-analysis.yml
- .github/workflows/styles-compile.yml
- .github/workflows/visual-tests.yml
Alternative zu https://github.com/redaxo/redaxo/pull/4567.
Hiermit würden die dependabot-PRs wie PRs aus Forks behandelt werden.
> Dependabot-PRs ohne Schreibrechte

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lang/en_gb.lang
- redaxo/src/core/pages/system.settings.php
closes: https://github.com/redaxo/redaxo/issues/4699
Ich habe mich gegen ein Input-Feld entschieden, da dieses an dieser Stelle deplatziert wirkt.
Man könnte noch ein Copy to clipboard einbauen. Hier fehlt mir aber noch die geeignete ui Idee.
> Adding path to system settings page

- redaxo/src/addons/backup/CHANGELOG.md
- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/be_style/CHANGELOG.md
- redaxo/src/addons/be_style/package.yml
- redaxo/src/addons/be_style/plugins/customizer/package.yml
- redaxo/src/addons/be_style/plugins/redaxo/package.yml
- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/cronjob/plugins/article_status/package.yml
- redaxo/src/addons/cronjob/plugins/optimize_tables/package.yml
- redaxo/src/addons/debug/CHANGELOG.md
- redaxo/src/addons/debug/package.yml
- redaxo/src/addons/install/package.yml
- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/mediapool/CHANGELOG.md
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/metainfo/CHANGELOG.md
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/phpmailer/CHANGELOG.md
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/addons/structure/CHANGELOG.md
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/addons/users/package.yml
- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/boot.php
https://github.com/redaxo/redaxo/compare/5.12.1...main
> Release 5.13.0-beta1

- .tools/psalm/baseline.xml
- redaxo/src/addons/cronjob/lib/form.php
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/core/lib/form/form.php
- redaxo/src/core/lib/form/form_base.php
Keine Code-Änderungen, nur phpdocs.
> rex_form: phpdocs

- redaxo/src/addons/structure/plugins/content/pages/templates.php
fixes #4928
@mbodon oder @schuer, kann einer von euch das vielleicht gegentesten?
> Templates: Modulzuweisung zu CTypes korrigiert

- redaxo/src/core/lib/setup/setup.php
https://www.php.net/supported-versions.php
> Added php 8.1 eol date

- redaxo/src/core/lib/setup/setup.php
https://en.wikipedia.org/wiki/MariaDB#Versioning
> Added MariaDb 10.6 eol date

- redaxo/src/addons/mediapool/pages/media.list.php
> MP: Dateityp-Filter funktionierte nicht

- .tools/psalm/baseline.xml
- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/mediapool/lang/de_de.lang
- redaxo/src/addons/mediapool/lang/en_gb.lang
- redaxo/src/addons/mediapool/lib/service_media.php
- redaxo/src/addons/mediapool/pages/media.detail.php
- redaxo/src/addons/mediapool/pages/upload.php
> MP: Upload-Errors besser abfangen

- .tools/psalm/baseline.xml
- redaxo/src/addons/cronjob/lang/de_de.lang
- redaxo/src/addons/cronjob/lang/en_gb.lang
- redaxo/src/addons/cronjob/lib/form.php
- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/cronjob/pages/cronjobs.php
> Cronjobs: Validierung Intervall-Felder

- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
> Modul-Aktionen: Alle-Events-Checkbox korrigiert

- redaxo/src/core/lib/console/assets_sync.php
> Cmd-Help: Dynamische Pfade nutzen

- redaxo/src/addons/structure/lib/service_article.php
> category2article: catname und catpriority aktualisieren

- redaxo/src/addons/metainfo/lib/handler/handler.php
> Metainfo: Date-Felder: Checkbox-Status korrigiert

- .tools/psalm/baseline.xml
- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
> MP: Alte Funktionen wieder kompatibel zu 5.12

- redaxo/src/addons/mediapool/lib/service_media.php
Fix https://github.com/redaxo/redaxo/issues/5020
> MP: Standardsortierung nach Updatedate

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/list.php
> Attribute für getColumnLink korrigiert

- .tools/psalm/baseline.xml
- redaxo/src/addons/cronjob/lib/manager_sql.php
Refs https://github.com/redaxo/redaxo/pull/4984#issuecomment-1017767525
> manager-sql: added typehints

- redaxo/src/addons/backup/lib/backup.php
> backup: improve error message on `opendir()` errors

- .gitignore
- .idea/icon.svg
Danke an @eaCe für die SVG-Datei
closes #5042
> Icon für PhpStorm

- README.md
- redaxo/src/addons/backup/update.php
Use: rex_version::compare instead of rex_string::versionCompare
> Typo fixes in README.md

- redaxo/src/core/lib/util/formatter.php
siehe https://github.com/redaxo/redaxo/commit/64dca29550c2247047021da60bed2521424ebc9f#r68653346
> rex_formatter : move 0000-00-00 handling

- redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
https://github.com/redaxo/redaxo/issues/5091#issuecomment-1087205059
> MM image_format: Extension bei jpeg korrigiert

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
> rex_mediapool_saveMedia() korrigiert

- redaxo/src/core/lib/console/assets_sync.php
In beide Richtungen syncen und Ordner ggf. anlegen
closes #5059
> Command assets:sync: Core-Assets-Handling optimiert

- redaxo/src/addons/mediapool/lib/service_media.php
fix https://github.com/redaxo/redaxo/issues/5126
> feat: adds EP to modify the media list query

- redaxo/src/addons/backup/CHANGELOG.md
- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/be_style/package.yml
- redaxo/src/addons/be_style/plugins/customizer/package.yml
- redaxo/src/addons/be_style/plugins/redaxo/package.yml
- redaxo/src/addons/debug/CHANGELOG.md
- redaxo/src/addons/debug/package.yml
- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/mediapool/CHANGELOG.md
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/metainfo/CHANGELOG.md
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/phpmailer/CHANGELOG.md
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/addons/structure/CHANGELOG.md
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/addons/structure/plugins/history/package.yml
- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/boot.php
https://github.com/redaxo/redaxo/compare/5.13.2...bugfix
> Release 5.13.3

- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
- redaxo/src/addons/media_manager/package.yml
> Effekt image_format: Extension korrigiert

- phpstan.neon.dist
this workaround is no longer required
> remove phpstan workaround

- redaxo/src/addons/backup/lang/de_de.lang
> Umlaute lang Backup-Addon

- redaxo/src/core/lib/util/socket/socket.php
add port and ssl parameters (and comments) to example code
> update socket example code

- redaxo/src/addons/backup/lib/cronjob.php
> fixed method name case

- redaxo/src/core/lib/login/backend_login.php
um https://github.com/FriendsOfREDAXO/2factor_auth/issues/51 umsetzen zu können
> extract `rex_backend_login->increaseLoginTries()`

- redaxo/src/core/lib/error_handler.php
closes https://github.com/redaxo/redaxo/issues/5178
> autoload: cache löschen bei uncaught class-not-found errors

- redaxo/src/core/default.config.yml
Zur inspiration wenn man die datei durchschaut
> Mention available `password_policy` config.yml keys

- redaxo/src/core/lib/util/path.php
- redaxo/src/core/tests/path_test.php
extracted from https://github.com/redaxo/redaxo/blob/8aca90055dba55993e4ace438cfa82041d93473d/redaxo/src/addons/media_manager/lib/effects/effect_convert2img.php#L162-L176
> added rex_path::findBinaryPath()

- .github/workflows/code-style.yml
- .github/workflows/remove-automerge-label.yml
- .github/workflows/rexlint.yml
- .github/workflows/sarif-report.yml
- .github/workflows/static-analysis.yml
- .github/workflows/styles-compile.yml
- .github/workflows/unit-tests.yml
- .github/workflows/visual-tests.yml
replaces #5119 
Hatte dort im PR keine Schreibrechte, und hab es noch bisschen angepasst vom Style (Einrückung, Position).
> Set permissions for GitHub actions

- composer.json
- phpstan.neon.dist
see also https://github.com/phpstan/phpstan/issues/7636
> remove attribute ignore rule

- .idea/php.xml
- .idea/redaxo.iml
missed while adding jetbrains/phpstorm-attributes in https://github.com/redaxo/redaxo/pull/5204
> added missing phpstorm settings

- .github/workflows/chatops.yml
- .github/workflows/code-style.yml
- .github/workflows/remove-automerge-label.yml
- .github/workflows/rexlint.yml
- .github/workflows/sarif-report.yml
- .github/workflows/static-analysis.yml
- .github/workflows/styles-compile.yml
- .github/workflows/unit-tests.yml
- .github/workflows/visual-tests.yml
to prevent endless queues on job problems e.g. on pathological static analysis cases
> timeout github actions after 5 minutes

- redaxo/src/addons/mediapool/lib/cache_media.php
Refs https://github.com/redaxo/redaxo/issues/5105
> Use GLOB_NOSORT

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- redaxo/src/core/assets/standard.js
- redaxo/src/core/backend.php
- redaxo/src/core/lib/login/login.php
closes https://github.com/redaxo/redaxo/issues/5182
> use `config.yml` cookie settings for `rex_htaccess_check`-cookie

- redaxo/src/addons/cronjob/pages/log.php
closes https://github.com/redaxo/redaxo/issues/5177
> cronjob: increase log-limit to 100 errors

- redaxo/src/addons/structure/plugins/content/lib/var_template.php
> rex_var_template: Erläuterung für Fake-Param

- redaxo/src/addons/structure/plugins/version/boot.php
> Oops-Seite bei Arbeitsversion-Voransicht

- redaxo/src/addons/structure/plugins/version/boot.php
- redaxo/src/addons/structure/plugins/version/lib/revision.php
> Version-Plugin: Bei Kopieren zw. Live/Arbeitsv. in neue Version wechseln

- .tools/psalm/baseline-taint.xml
- redaxo/src/core/lib/sql/util.php
> slowQueryLogPath() returns a taint-safe file

- .github/tests-visual/visual-record.js
Versuch den `Error: net::ERR_EMPTY_RESPONSE` zu beheben
See https://stackoverflow.com/a/52163615
> Visual tests: remove timeouts

- redaxo/src/core/lib/login/backend_login.php
> Fix für Configaufruf bei setStayLoggedInCookie

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- redaxo/src/addons/metainfo/extensions/extension_cleanup.php
- redaxo/src/addons/metainfo/functions/function_metainfo.php
- redaxo/src/addons/metainfo/lib/handler/category_handler.php
- redaxo/src/addons/metainfo/lib/handler/clang_handler.php
- redaxo/src/addons/metainfo/lib/handler/handler.php
- redaxo/src/addons/metainfo/lib/input.php
- redaxo/src/addons/metainfo/lib/input/date.php
- redaxo/src/addons/metainfo/lib/input/datetime.php
- redaxo/src/addons/metainfo/lib/input/linkbutton.php
- redaxo/src/addons/metainfo/lib/input/linklistbutton.php
- redaxo/src/addons/metainfo/lib/input/mediabutton.php
- redaxo/src/addons/metainfo/lib/input/medialistbutton.php
- redaxo/src/addons/metainfo/lib/input/select.php
- redaxo/src/addons/metainfo/lib/input/time.php
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/lib/table_manager.php
- redaxo/src/core/lib/form/form_base.php
Ergänzung der return types in phpstan level 6 des Addons metainfos, entsprechend https://github.com/redaxo/redaxo/issues/5275
> phpstan return types Core-Addon metainfo

- redaxo/src/addons/phpmailer/README.de.md
- redaxo/src/addons/phpmailer/README.md
Neu: Hinweis zum Datenschutz
Neu: Hinweis zum neuen prefix im Archiv
Ergänzung zu
https://github.com/redaxo/redaxo/pull/5321
> PHPMailer: Readme Ergänzung zu Logging und Archiv-Funkion

- .github/workflows/sarif-report.yml
- .github/workflows/static-analysis.yml
- .github/workflows/visual-tests.yml
see https://github.com/sebastianbergmann/phpunit/issues/5033
> Run static analysis on php 8.2

- redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
analog https://github.com/redaxo/redaxo/pull/5346
> added `@phpstandba-inference-placeholder` to `rex_article_slice_history::getTablePrefix()`

- .tools/psalm/baseline.xml
- redaxo/src/addons/media_manager/lib/effects/effect_crop.php
- redaxo/src/addons/media_manager/lib/effects/effect_resize.php
diese funktion sollte es mittlerweile überall geben
> remove no longer relevant `function_exists('ImageCreateTrueColor')`

- redaxo/src/addons/media_manager/lib/effects/effect_mirror.php
- redaxo/src/addons/media_manager/lib/effects/effect_workspace.php
> removed useless `isset` calls

- .tools/phpstan/baseline.neon
- redaxo/src/addons/mediapool/lib/media_category_select.php
- redaxo/src/addons/structure/lib/select_category.php
> removed always true condition

- redaxo/src/addons/install/lang/de_de.lang
- redaxo/src/addons/install/lang/en_gb.lang
- redaxo/src/addons/install/lang/es_es.lang
- redaxo/src/addons/install/lang/pt_br.lang
- redaxo/src/addons/install/lang/sv_se.lang
- redaxo/src/addons/install/lib/api/api_package_add.php
closes https://github.com/redaxo/redaxo/issues/903
> Install AddOn: AddOns und Plugins installieren #903

- .tools/psalm/baseline.xml
- redaxo/src/addons/cronjob/plugins/article_status/lib/cronjob.php
- redaxo/src/addons/mediapool/assets/mediapool.js
- redaxo/src/addons/metainfo/lib/table_expander.php
- redaxo/src/addons/metainfo/pages/content.metainfo.php
- redaxo/src/addons/structure/plugins/content/boot.php
- redaxo/src/addons/structure/plugins/content/lib/article_slice.php
- redaxo/src/addons/structure/plugins/history/lib/article_slice_history.php
- redaxo/src/core/assets/standard.js
detected via rexstan https://github.com/FriendsOfREDAXO/rexstan/pull/155
ungetestet
> added sql escaping

- redaxo/src/core/lang/de_de.lang
- redaxo/src/core/lib/login/user_session.php
- redaxo/src/core/pages/profile.php
- redaxo/src/core/pages/profile.sessions.php
> Backend User Session Remove

- redaxo/src/core/pages/profile.sessions.php
> prevent user from removing the current backend session

- .tools/phpstan/baseline.neon
- redaxo/src/addons/install/lib/package/package_add.php
- redaxo/src/addons/install/lib/packages.php
param unused since 2b3304b55af8f99bb3c7bbf99ce7907492ec4bd6
> remove unused param & proper naming

- redaxo/src/core/install.php
- redaxo/src/core/lib/setup/import.php
Da es eine neue Tabelle ist, könnten wir eventuell hier auch gleich einen Fremdschlüssel anlegen.
Oder siehst du Probleme @bloep?
> Fremdschlüssel für rex_user_session

- .tools/psalm/baseline.xml
- redaxo/src/addons/users/pages/users.php
für mein empfinden gibt es viele stellen, wo wir wissen, dass es einen User geben muss.
( exemplarisch für eine Datei im `users` gemacht. )
> replace `rex::getUser()` with `rex::requireUser()`

- .tools/phpstan/baseline.neon
- redaxo/src/core/lib/var/var.php
ausgekoppelt aus https://github.com/redaxo/redaxo/pull/5404
> type rex_var

- redaxo/src/core/lib/util/logger.php
> error_log mit function_exists-wrapper

- redaxo/src/core/lib/console/setup/run.php
> Im Console-Setup auch instname setzen

- redaxo/src/addons/be_style/CHANGELOG.md
- redaxo/src/addons/be_style/package.yml
- redaxo/src/addons/be_style/plugins/redaxo/package.yml
- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/structure/CHANGELOG.md
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/addons/structure/plugins/history/package.yml
- redaxo/src/addons/structure/plugins/version/package.yml
- redaxo/src/addons/users/CHANGELOG.md
- redaxo/src/addons/users/package.yml
- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/boot.php
https://github.com/redaxo/redaxo/compare/5.14.1...bugfix
> Release 5.14.2

- .tools/psalm/baseline.xml
- redaxo/src/addons/backup/lib/cronjob.php
> Backup-Cronjob: Deprecated-Meldung entfernt

- redaxo/src/addons/structure/plugins/content/lib/system_setting_default_template_id.php
- redaxo/src/addons/structure/plugins/content/pages/templates.php
> Templates: translate-Labels in Liste übersetzen

- redaxo/src/core/lib/util/markdown.php
> rex_markdown: Fix deprecation suppression

- redaxo/src/addons/phpmailer/README.de.md
- redaxo/src/addons/phpmailer/README.md
PHPMAILER_PRE_SEND und PHPMAILER_POST_SEND
> PHPMAILER : Doc: Beispiele für neue Extensionpoints

- .tools/psalm/baseline.xml
- redaxo/src/core/update.php
> Whoops im Setup vermeiden

- redaxo/src/addons/mediapool/pages/index.php
> MP: Subpages mit zusätzlichen URL-Parametern erlauben

- redaxo/src/core/lib/setup/setup.php
Da ist beim Mergen von bugfix zu main was schief gegangen.
> Fix php eol data

- .tools/psalm/baseline.xml
- redaxo/src/addons/structure/plugins/content/pages/templates.php
> Template speichern korrigiert/optimiert

- redaxo/src/addons/be_style/plugins/customizer/boot.php
Auch wenn ich mir nicht recht erklären kann, wie es zu den Fehlern kommt. Hiermit sollte es jedenfalls vermieden werden.
fixes #5340
> customizer: Abfangen, wenn neue Werte nicht gesetzt

- redaxo/src/addons/install/lib/archive.php
closes #5453
@aeberhard Also du meinst, so klappt es einigermaßen zuverlässig, oder jedenfalls häufiger, als vorher?
> Win: rex_install_archive::extract stabilisieren

- redaxo/src/addons/structure/plugins/content/pages/content.functions.php
https://github.com/redaxo/redaxo/pull/5501#discussion_r1064902354
> Unnötige Var-Setzung entfernt

- redaxo/src/core/lib/console/user/set_password.php
> console user set passwort setzt login tries auf 0 #5528

- redaxo/src/core/boot.php
> Error-Message falls PHP-Version zu klein

- redaxo/src/core/pages/profile.sessions.php
> Prefix bei UserSession Tabelle ergänzt

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/console/package/activate.php
- redaxo/src/core/lib/console/package/deactivate.php
- redaxo/src/core/lib/console/package/delete.php
- redaxo/src/core/lib/console/package/install.php
- redaxo/src/core/lib/console/package/run_update_script.php
- redaxo/src/core/lib/console/package/uninstall.php
refs https://github.com/redaxo/redaxo/issues/4950
> added autocomplete for package commands

- redaxo/src/core/lib/error_handler.php
- redaxo/src/core/lib/login/backend_login.php
- redaxo/src/core/lib/login/login.php
> Whoops: Session-ID und Eingeloggt-bleiben-Cookie verstecken

- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
fixes #5518
Das Problem entstand durch #5070.
> rex_sql: SQL-Mode/Charset über separates Objekt

- redaxo/src/core/lib/login/backend_login.php
> Bessere Fehlermeldung, wenn instname leer

- redaxo/src/addons/users/pages/users.php
> Nach Benutzerwechsel darf man Originaluser nicht löschen

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_select_test.php
> Fix rex_sql::getFieldnames

- .tools/psalm/baseline.xml
- redaxo/src/addons/backup/package.yml
- redaxo/src/addons/be_style/CHANGELOG.md
- redaxo/src/addons/be_style/package.yml
- redaxo/src/addons/be_style/plugins/customizer/package.yml
- redaxo/src/addons/be_style/plugins/redaxo/package.yml
- redaxo/src/addons/cronjob/package.yml
- redaxo/src/addons/cronjob/plugins/article_status/package.yml
- redaxo/src/addons/cronjob/plugins/optimize_tables/package.yml
- redaxo/src/addons/debug/package.yml
- redaxo/src/addons/install/CHANGELOG.md
- redaxo/src/addons/install/package.yml
- redaxo/src/addons/media_manager/CHANGELOG.md
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/mediapool/CHANGELOG.md
- redaxo/src/addons/mediapool/package.yml
- redaxo/src/addons/metainfo/install.php
- redaxo/src/addons/metainfo/package.yml
- redaxo/src/addons/phpmailer/CHANGELOG.md
- redaxo/src/addons/phpmailer/package.yml
- redaxo/src/addons/structure/CHANGELOG.md
- redaxo/src/addons/structure/package.yml
- redaxo/src/addons/structure/plugins/content/package.yml
- redaxo/src/addons/structure/plugins/history/package.yml
- redaxo/src/addons/structure/plugins/version/package.yml
- redaxo/src/addons/users/CHANGELOG.md
- redaxo/src/addons/users/package.yml
- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/boot.php
- redaxo/src/core/update.php
https://github.com/redaxo/redaxo/compare/5.14.3...main
> Release 5.15.0-beta1

- redaxo/src/addons/users/pages/users.php
> Benutzer hinzufügen: Passkeys/Sessions nicht ausgeben

- redaxo/src/addons/media_manager/lib/effects/effect_image_format.php
> MM: in image_format prüfen, ob Formate verfügbar

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/tests/sql/sql_test.php
closes https://github.com/redaxo/redaxo/issues/5613
> Support `PDO::FETCH_KEY_PAIR` in `rex_sql->getArray()`

- README.de.md
- README.md
- redaxo/src/addons/backup/lib/compressor.php
- redaxo/src/addons/backup/lib/tar.php
- redaxo/src/addons/be_style/lib/scss_compiler.php
- redaxo/src/addons/cronjob/lib/types/urlrequest.php
- redaxo/src/core/assets/standard.js
- redaxo/src/core/lib/csrf_token.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/lib/util/formatter.php
- redaxo/src/core/lib/util/stream.php
- redaxo/src/core/lib/util/version.php
> https urls

- phpunit.xml.dist
- redaxo/src/core/fragments/core/Component/Alert.php
- redaxo/src/core/fragments/core/Component/Button.php
- redaxo/src/core/fragments/core/Component/Card.php
- redaxo/src/core/fragments/core/Component/Checkbox.php
- redaxo/src/core/fragments/core/Component/ChoiceCheckbox.php
- redaxo/src/core/fragments/core/Component/ChoiceRadio.php
- redaxo/src/core/fragments/core/Component/ChoiceSelect.php
- redaxo/src/core/fragments/core/Component/Icon.php
- redaxo/src/core/fragments/core/Component/Input.php
- redaxo/src/core/fragments/core/Component/Textarea.php
- redaxo/src/core/lib/Fragment/Attributes.php
- redaxo/src/core/lib/Fragment/Component/Alert.php
- redaxo/src/core/lib/Fragment/Component/Alert/Error.php
- redaxo/src/core/lib/Fragment/Component/Alert/Info.php
- redaxo/src/core/lib/Fragment/Component/Alert/Success.php
- redaxo/src/core/lib/Fragment/Component/Alert/Warning.php
- redaxo/src/core/lib/Fragment/Component/Button.php
- redaxo/src/core/lib/Fragment/Component/Button/Add.php
- redaxo/src/core/lib/Fragment/Component/Button/Save.php
- redaxo/src/core/lib/Fragment/Component/Card.php
- redaxo/src/core/lib/Fragment/Component/Checkbox.php
- redaxo/src/core/lib/Fragment/Component/Choice.php
- redaxo/src/core/lib/Fragment/Component/Input.php
- redaxo/src/core/lib/Fragment/Component/Textarea.php
- redaxo/src/core/lib/Fragment/Fragment.php
- redaxo/src/core/lib/Fragment/HtmlAttributes.php
- redaxo/src/core/pages/system.settings.php
- redaxo/src/core/tests/Fragment/HtmlAttributesTest.php
Ich habe mir nochmal Gedanken gemacht, wie man das mit den Attributen optimieren kann.
Meine Vorschlag ist nun diese neue `Attributes`-Klasse.
Wenn das passt, ziehe ich noch die fehlenden Components nach und schreibe noch Tests.
> Neue `HtmlAttributes`-Klasse

- redaxo/src/core/fragments/core/Component/ChoiceCheckbox.php
> ChoiceCheckbox: fix aria-labeledby

- redaxo/src/addons/install/lib/api/api_core_update.php
- redaxo/src/addons/install/lib/package/package_update.php
- redaxo/src/core/lib/packages/package.php
closes #5452
Ich konnte das Problem nun nachstellen und dadurch beheben.
> Installer: Nach Update Properties definitiv neu laden

- redaxo/src/addons/install/CHANGELOG.md
- redaxo/src/addons/install/package.yml
- redaxo/src/core/CHANGELOG.md
- redaxo/src/core/boot.php
https://github.com/redaxo/redaxo/compare/5.15.0...bugfix
> Release 5.15.1

- redaxo/src/core/update.php
refs https://github.com/redaxo/redaxo/issues/5657#issuecomment-1477524886
Wenn die Session, warum auch immer, schon in der DB ist (also vorheriges Update abgebrochen ist oder so), dann sollte im Update-Skript hier der Fehler einfach ignoriert werden.
Ist jetzt hier nur ein einfacher Fix für die spezifische Stelle. Unabhängig davon können wir trotzdem noch schauen, ob wir die Updates durch Transactions insgesamt verbessern.
> Core-Update: Ignorieren, wenn Session schon in DB

- redaxo/src/core/schemas/package.json
closes https://github.com/redaxo/redaxo/issues/5654
getestet in rexstan via https://github.com/FriendsOfREDAXO/rexstan/pull/460
> package-schema: define installer_ignore pattern

- redaxo/src/core/boot.php
- redaxo/src/core/schemas/package.json
refs https://github.com/FriendsOfREDAXO/rexstan/pull/460#discussion_r1155141366
> fix package.json schema for pages/main-pages

- redaxo/src/core/pages/system.log.redaxo.php
"success"-Level für Rex-Logger ergänzt
> rex_logger: success-Level wieder ergänzt

- redaxo/src/core/fragments/core/navigations/main.php
Pull Request für https://github.com/redaxo/redaxo/pull/5685 (hatte keine push Rechte, daher 2. Pull Request)
> psalm fixes toggle-nav

- redaxo/src/addons/media_manager/lib/effects/effect_header.php
> Effekt `header`: Fehler nach Update vermeiden

- .tools/psalm/baseline-taint.xml
- redaxo/src/core/lib/util/file.php
alternative try to close https://github.com/redaxo/redaxo/pull/5840
> re-try delete to compensate possible race conditions

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- redaxo/src/core/.phpstorm.meta.php
- redaxo/src/core/lib/base/factory_trait.php
- redaxo/src/core/lib/form/elements/prio.php
- redaxo/src/core/lib/form/form.php
- redaxo/src/core/lib/login/backend_password_policy.php
- redaxo/src/core/lib/login/password_policy.php
- redaxo/src/core/lib/phpmailer/mailer.php
- redaxo/src/core/lib/rex.php
- redaxo/src/core/lib/sql/sql.php
- redaxo/src/core/lib/util/formatter.php
- redaxo/src/core/lib/util/log_file.php
- redaxo/src/core/lib/util/string.php
- redaxo/src/core/tests/base/factory_trait_test.php
- redaxo/src/core/tests/login/password_policy_test.php
- redaxo/src/core/tests/util/formatter_test.php
- redaxo/src/core/tests/util/i18n_test.php
- redaxo/src/core/tests/util/log_entry_test.php
- version
- Core: remove deprecated methods, params etc.
> Core: remove deprecated methods, params etc.

- redaxo/src/core/lib/sql/sql.php
https://github.com/php/php-src/blob/87edeed3b9fcb9d066d8e18b10fb0ed8cb976873/ext/pdo_mysql/pdo_mysql.c#L143-L145
> Check ob Konstante MYSQL_ATTR_SSL_VERIFY_SERVER_CERT existiert

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline-taint.xml
- .tools/psalm/baseline.xml
- composer.json
- redaxo/src/addons/debug/composer.json
- redaxo/src/addons/debug/composer.lock
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/IncomingRequest.php
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Request/Request.php
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/FileStorage.php
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/RedisStorage.php
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Storage/Search.php
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/Clockwork.php
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/Clockwork/Support/Vanilla/config.php
- redaxo/src/addons/debug/vendor/itsgoingd/clockwork/composer.json
- redaxo/src/core/lib/util/logger.php
- redaxo/src/core/vendor/composer/installed.php
> Vendor-Updates

- .tools/bin/refresh
- .tools/bin/reinstall-core
> refresh-Skript: Core-DB-Tabellen aktualisieren

- redaxo/src/addons/users/pages/users.php
- redaxo/src/core/pages/login.php
- redaxo/src/core/pages/profile.php
- redaxo/src/core/pages/setup.step5.php
Der PR ergänzt bei den Loginfeldern und Benutzerfeldern (Setup, Profil, Benutzerverwaltung) weitere Attribute, wie maxlength, inputmode, autocorrect und autocapitalize.
refs #604
> Benutzer-Formularfelder: Attribute optimiert

- redaxo/src/addons/cronjob/pages/cronjobs.php
- redaxo/src/addons/media_manager/package.yml
- redaxo/src/addons/media_manager/pages/types.php
- redaxo/src/addons/users/package.yml
- redaxo/src/addons/users/pages/roles.php
- redaxo/src/core/lib/form/elements/element.php
refs https://github.com/redaxo/redaxo/issues/1987
> rex_form: maxlength/minlength-Attribute anhand Validator setzen

- redaxo/src/core/pages/system.clangs.php
> Sprachenverwaltung: Attribute für Inputs optimiert

- redaxo/src/addons/structure/lib/service_article.php
- redaxo/src/addons/structure/plugins/content/install.php
- redaxo/src/addons/structure/plugins/content/tests/article_slice_test.php
Als Vorbereitung für den Strict-Mode: #5822
> Structure: Werte setzen für Spalten, die keinen Default haben

- redaxo/src/addons/mediapool/functions/function_rex_mediapool.php
- redaxo/src/addons/structure/pages/index.php
- redaxo/src/addons/structure/plugins/content/pages/modules.actions.php
- redaxo/src/addons/structure/plugins/content/pages/modules.modules.php
- redaxo/src/addons/structure/plugins/content/pages/templates.php
> Structure/Mediapool: Attribute für Inputs optimiert

- .phpstorm.meta.php
- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- rector.php
- redaxo/src/core/lib/form/elements/element.php
- redaxo/src/core/lib/metainfo/table_expander.php
- redaxo/src/core/pages/cronjob.cronjobs.php
- redaxo/src/core/pages/media_manager.types.php
- redaxo/src/core/pages/phpmailer.config.php
- redaxo/src/core/pages/profile.php
- redaxo/src/core/pages/users.roles.php
- redaxo/src/core/pages/users.users.php
- src/Core.php
- src/Validator/ValidationRule.php
- src/Validator/Validator.php
- tests/Validator/ValidatorTest.php
- Namespace rex_validator -> Redaxo\Core\Validator\Validator
- Baseline
- .phpstorm.meta.php aktualisiert
> Namespace rex_validator -> Redaxo\Core\Validator\Validator

- .phpstorm.meta.php
- .tools/bin/release
- .tools/psalm/baseline.xml
- rector.php
- redaxo/src/addons/install/lib/api/api_core_update.php
- redaxo/src/addons/install/lib/archive.php
- redaxo/src/core/functions/function_rex_other.php
- redaxo/src/core/lib/backup/backup.php
- redaxo/src/core/lib/console/assets_sync.php
- redaxo/src/core/lib/packages/manager.php
- redaxo/src/core/lib/setup/setup.php
- redaxo/src/core/pages/backup.export.php
- redaxo/src/core/pages/mediapool.sync.php
- redaxo/src/core/tests/structure/article_content_test.php
- src/Filesystem/Dir.php
- src/Filesystem/Finder.php
- src/Translation/I18n.php
- tests/Filesystem/FinderTest.php
- Namespace rex_finder -> Redaxo\Core\Filesystem\Finder
- Baseline
> Namespace rex_finder -> Redaxo\Core\Filesystem\Finder

- redaxo/src/core/install.php
> Setup: Fehler bei Charset-Änderung vermeiden (bzgl. Foreign Key)

- redaxo/src/core/lib/login/login.php
> Login-Check: Umgang mit nicht mehr existierendem User korrigiert

- redaxo/src/addons/metainfo/pages/content.metainfo.php
fixes https://github.com/redaxo/redaxo/issues/5738
> Metainfo-Sidebar: Status-Link mit Clang-Berücksichtigung

- .tools/psalm/baseline.xml
- redaxo/src/core/lib/list.php
> rex_list: Bei URLs den Pager-Cursor mitgeben

- redaxo/src/addons/media_manager/pages/effects.php
- redaxo/src/addons/media_manager/pages/types.php
> Media-Manager: Listen erst ab 100 Einträgen paginieren

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- rector.php
- redaxo/src/core/pages/cronjob.cronjobs.php
- src/Cronjob/Form/CronjobForm.php
- src/Cronjob/Form/IntervalField.php
- Klassen verschoben, Namespace gesetzt
- Anpassungen an Dateien
- Baseline
> Namespace rex_cronjob_form_x -> Redaxo\Core\Cronjob\Form\ 

- .tools/phpstan/baseline.neon
- .tools/psalm/baseline.xml
- src/Filesystem/DefaultPathProvider.php
- src/Filesystem/Dir.php
- src/Filesystem/File.php
- src/Filesystem/Finder.php
- src/Filesystem/Path.php
- src/Filesystem/Url.php
- src/Util/Formatter.php
- src/Util/SortableIterator.php
- src/Util/Str.php
- tests/Filesystem/DirTest.php
- tests/Filesystem/FileTest.php
- tests/Filesystem/FinderTest.php
plus ein paar Methoden drum herum.
> Filesystem-Klassen optimiert

- src/Core.php
- src/HttpClient/Request.php
- tests/HttpClient/ProxyRequestTest.php
- tests/HttpClient/RequestTest.php
/cc @tbaddade da fehlten noch einige Stellen ;)
> HttpClient: Config-Key korrigiert

- redaxo/src/core/lib/util/string.php
> php 8.3: fix rex_string::highlight

- redaxo/src/core/lib/login/backend_login.php
> Bei Login über Passkey den Username ignorieren

- redaxo/src/core/lib/util/markdown.php
- redaxo/src/core/lib/util/string.php
> php 8.3: fix php highlighting color (dark mode)

- redaxo/src/addons/structure/plugins/content/pages/content.php
> Artikelbearbeitung: Abfangen, wenn rechte Nav leer

- redaxo/src/core/lib/be/controller.php
> Bessere Exception für includeCurrentPageSubPath bei Main Pages

- redaxo/src/core/assets/standard.js
"So ist das kein gutes Englisch." Feedback von Englisch-Muttersprachlerin.
Alternativen:
```suggestion
$('#rex-js-page-main').prepend('<div class="alert alert-danger" style="margin-top: 20px;">The folder <code>redaxo/' + url + '</code> is insecure. Make sure this folder is not accessible to the public.</div>');
```
oder
```suggestion
$('#rex-js-page-main').prepend('<div class="alert alert-danger" style="margin-top: 20px;">The folder <code>redaxo/' + url + '</code> is insecure. Make sure this folder is not publicly accessible.</div>');
```
> `.htaccess`-check: improve error message - alternativ zu #6242

- redaxo/src/addons/structure/boot.php
> Neue Sprache: Wenn Prio=1 auch Artikel duplizieren

- redaxo/src/addons/metainfo/lib/table_manager.php
Der Fehler entstand in https://github.com/redaxo/redaxo/pull/6224.
> MetaInfo: Fix variable usage

- redaxo/src/addons/mediapool/package.yml
Added to allowed_mime_types: 
```yml
csv: [text/csv]
```
> Mediapool: allowed_mime_types: CSV

- redaxo/src/core/lib/sql/sql.php
closes https://github.com/redaxo/redaxo/issues/6316
> rex_sql: fix wrong error message concatenation

- redaxo/src/addons/install/lib/package/package_update.php
> Addon-Update: Package-Config in rex_config aktualisieren

- redaxo/src/addons/structure/plugins/version/boot.php
> structure/version: Nach Versionskopie korrekte Slices ausgeben
